package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * AllocationOrderDetail generated by hbm2java
 */
@Entity
public class AllocationOrderDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8043349548331506204L;
	@EmbeddedId
	private AllocationOrderDetailId id;
	private Integer itemNum;
	private String allocationOrderDetailItemName;
	private String allocationOrderDetailItemSpec;
	private String allocationOrderDetailItemUnit;
	private BigDecimal allocationOrderDetailQty;
	private BigDecimal allocationOrderDetailPrice;
	private BigDecimal allocationOrderDetailSubtotal;
	private double allocationOrderDetailTaxRate;
	private String allocationOrderDetailMemo;
	private Integer allocationOrderDetailItemMatrixNum;
	private Date allocationOrderDetailProducingDate;
	private String allocationOrderDetailLotNumber;
	private BigDecimal allocationOrderDetailAssistQty;
	private String allocationOrderDetailItemAssistUnit;
	private String allocationOrderDetailUseUnit;
	private BigDecimal allocationOrderDetailUseQty;
	private BigDecimal allocationOrderDetailUsePrice;
	private BigDecimal allocationOrderDetailUseRate;
	private String allocationOrderDetailItemCode;
	private BigDecimal allocationOrderDetailInventoryQty;
	private BigDecimal allocationOrderDetailInvAssistQty;
	private Integer supplierNum;

	public AllocationOrderDetail() {
	}

	public Integer getSupplierNum() {
		return supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public AllocationOrderDetailId getId() {
		return id;
	}


	public void setId(AllocationOrderDetailId id) {
		this.id = id;
	}


	public Integer getItemNum() {
		return itemNum;
	}


	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}


	public String getAllocationOrderDetailItemName() {
		return this.allocationOrderDetailItemName;
	}

	public void setAllocationOrderDetailItemName(
			String allocationOrderDetailItemName) {
		this.allocationOrderDetailItemName = allocationOrderDetailItemName;
	}

	public String getAllocationOrderDetailItemSpec() {
		return this.allocationOrderDetailItemSpec;
	}

	public void setAllocationOrderDetailItemSpec(
			String allocationOrderDetailItemSpec) {
		this.allocationOrderDetailItemSpec = allocationOrderDetailItemSpec;
	}

	public String getAllocationOrderDetailItemUnit() {
		return this.allocationOrderDetailItemUnit;
	}

	public void setAllocationOrderDetailItemUnit(
			String allocationOrderDetailItemUnit) {
		this.allocationOrderDetailItemUnit = allocationOrderDetailItemUnit;
	}

	public BigDecimal getAllocationOrderDetailQty() {
		return this.allocationOrderDetailQty;
	}

	public void setAllocationOrderDetailQty(BigDecimal allocationOrderDetailQty) {
		this.allocationOrderDetailQty = allocationOrderDetailQty;
	}

	public BigDecimal getAllocationOrderDetailPrice() {
		return this.allocationOrderDetailPrice;
	}

	public void setAllocationOrderDetailPrice(
			BigDecimal allocationOrderDetailPrice) {
		this.allocationOrderDetailPrice = allocationOrderDetailPrice;
	}

	public BigDecimal getAllocationOrderDetailSubtotal() {
		return this.allocationOrderDetailSubtotal;
	}

	public void setAllocationOrderDetailSubtotal(
			BigDecimal allocationOrderDetailSubtotal) {
		this.allocationOrderDetailSubtotal = allocationOrderDetailSubtotal;
	}

	public double getAllocationOrderDetailTaxRate() {
		return this.allocationOrderDetailTaxRate;
	}

	public void setAllocationOrderDetailTaxRate(
			double allocationOrderDetailTaxRate) {
		this.allocationOrderDetailTaxRate = allocationOrderDetailTaxRate;
	}

	public String getAllocationOrderDetailMemo() {
		return this.allocationOrderDetailMemo;
	}

	public void setAllocationOrderDetailMemo(String allocationOrderDetailMemo) {
		this.allocationOrderDetailMemo = allocationOrderDetailMemo;
	}

	public Integer getAllocationOrderDetailItemMatrixNum() {
		return this.allocationOrderDetailItemMatrixNum;
	}

	public void setAllocationOrderDetailItemMatrixNum(
			Integer allocationOrderDetailItemMatrixNum) {
		this.allocationOrderDetailItemMatrixNum = allocationOrderDetailItemMatrixNum;
	}

	public Date getAllocationOrderDetailProducingDate() {
		return this.allocationOrderDetailProducingDate;
	}

	public void setAllocationOrderDetailProducingDate(
			Date allocationOrderDetailProducingDate) {
		this.allocationOrderDetailProducingDate = allocationOrderDetailProducingDate;
	}

	public String getAllocationOrderDetailLotNumber() {
		return this.allocationOrderDetailLotNumber;
	}

	public void setAllocationOrderDetailLotNumber(
			String allocationOrderDetailLotNumber) {
		this.allocationOrderDetailLotNumber = allocationOrderDetailLotNumber;
	}

	public BigDecimal getAllocationOrderDetailAssistQty() {
		return this.allocationOrderDetailAssistQty;
	}

	public void setAllocationOrderDetailAssistQty(
			BigDecimal allocationOrderDetailAssistQty) {
		this.allocationOrderDetailAssistQty = allocationOrderDetailAssistQty;
	}

	public String getAllocationOrderDetailItemAssistUnit() {
		return this.allocationOrderDetailItemAssistUnit;
	}

	public void setAllocationOrderDetailItemAssistUnit(
			String allocationOrderDetailItemAssistUnit) {
		this.allocationOrderDetailItemAssistUnit = allocationOrderDetailItemAssistUnit;
	}

	public String getAllocationOrderDetailUseUnit() {
		return this.allocationOrderDetailUseUnit;
	}

	public void setAllocationOrderDetailUseUnit(
			String allocationOrderDetailUseUnit) {
		this.allocationOrderDetailUseUnit = allocationOrderDetailUseUnit;
	}

	public BigDecimal getAllocationOrderDetailUseQty() {
		return this.allocationOrderDetailUseQty;
	}

	public void setAllocationOrderDetailUseQty(
			BigDecimal allocationOrderDetailUseQty) {
		this.allocationOrderDetailUseQty = allocationOrderDetailUseQty;
	}

	public BigDecimal getAllocationOrderDetailUsePrice() {
		return this.allocationOrderDetailUsePrice;
	}

	public void setAllocationOrderDetailUsePrice(
			BigDecimal allocationOrderDetailUsePrice) {
		this.allocationOrderDetailUsePrice = allocationOrderDetailUsePrice;
	}

	public BigDecimal getAllocationOrderDetailUseRate() {
		return this.allocationOrderDetailUseRate;
	}

	public void setAllocationOrderDetailUseRate(
			BigDecimal allocationOrderDetailUseRate) {
		this.allocationOrderDetailUseRate = allocationOrderDetailUseRate;
	}

	public String getAllocationOrderDetailItemCode() {
		return this.allocationOrderDetailItemCode;
	}

	public void setAllocationOrderDetailItemCode(
			String allocationOrderDetailItemCode) {
		this.allocationOrderDetailItemCode = allocationOrderDetailItemCode;
	}

	public BigDecimal getAllocationOrderDetailInventoryQty() {
		return this.allocationOrderDetailInventoryQty;
	}

	public void setAllocationOrderDetailInventoryQty(
			BigDecimal allocationOrderDetailInventoryQty) {
		this.allocationOrderDetailInventoryQty = allocationOrderDetailInventoryQty;
	}

	public BigDecimal getAllocationOrderDetailInvAssistQty() {
		return this.allocationOrderDetailInvAssistQty;
	}

	public void setAllocationOrderDetailInvAssistQty(
			BigDecimal allocationOrderDetailInvAssistQty) {
		this.allocationOrderDetailInvAssistQty = allocationOrderDetailInvAssistQty;
	}

	public static List<AllocationOrderDetail> findDetails(
            List<AllocationOrderDetail> allocationOrderDetails,
            String allocationOrderFid) {
		List<AllocationOrderDetail> list = new ArrayList<AllocationOrderDetail>();
		for(int i = 0;i < allocationOrderDetails.size();i++){
			AllocationOrderDetail allocationOrderDetail = allocationOrderDetails.get(i);
			if(allocationOrderDetail.getId().getAllocationOrderFid().equals(allocationOrderFid)){
				list.add(allocationOrderDetail);
			}
		}
	    return list;
    }

}
