package com.nhsoft.module.report.model;

// Generated 2016-7-6 14:24:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;

/**
 * CardPosConsume generated by hbm2java
 */
@Entity
public class CardPosConsume implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8975869213030185237L;
	@Id
	private String orderNo;
	private Integer cardUserNum;
	private String systemBookCode;
	private Integer branchNum;
	private String shiftTableBizday;
	private BigDecimal orderMoney;

	public CardPosConsume() {
	}

	public CardPosConsume(String orderNo) {
		this.orderNo = orderNo;
	}

	public CardPosConsume(String orderNo, Integer cardUserNum, String systemBookCode, Integer branchNum,
                          String shiftTableBizday, BigDecimal orderMoney) {
		this.orderNo = orderNo;
		this.cardUserNum = cardUserNum;
		this.systemBookCode = systemBookCode;
		this.branchNum = branchNum;
		this.shiftTableBizday = shiftTableBizday;
		this.orderMoney = orderMoney;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getCardUserNum() {
		return this.cardUserNum;
	}

	public void setCardUserNum(Integer cardUserNum) {
		this.cardUserNum = cardUserNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public BigDecimal getOrderMoney() {
		return this.orderMoney;
	}

	public void setOrderMoney(BigDecimal orderMoney) {
		this.orderMoney = orderMoney;
	}

}
