package com.nhsoft.module.report.model;

import com.nhsoft.module.report.query.State;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * CardSettlement generated by hbm2java
 */
@Entity
public class CardSettlement implements java.io.Serializable {

	private static final long serialVersionUID = -687559484474391583L;
	@Id
	private String cardSettlementNo;
	private String systemBookCode;
	private Integer branchNum;
	private String toSystemBookCode;
	private Integer toBranchNum;
	private Date cardSettlementDate;
	private String cardSettlementType;
	private String cardSettlementPaymentType;
	private String cardSettlementMemo;
	private String cardSettlementCreator;
	private Date cardSettlementCreateTime;
	private String cardSettlementAuditor;
	private Date cardSettlementAuditTime;
	@Embedded
	@AttributeOverrides( {
		 			@AttributeOverride(name="stateCode", column = @Column(name="cardSettlementStateCode")), 
		@AttributeOverride(name="stateName", column = @Column(name="cardSettlementStateName")) } )
	private State state;
	private String cardSettlementRefBillNo;
	private BigDecimal cardSettlementDepositCash;
	private BigDecimal cardSettlementDepositMoney;
	private BigDecimal cardSettlementConsumeMoney;
	private BigDecimal cardSettlementMoney;
	private BigDecimal cardSettlementReConsumeMoney;
	private BigDecimal cardSettlementUnConsumeMoney;
	private Integer accountBankNum;
	private String cardSettlementPreNo;
	private BigDecimal cardSettlementPaidMoney;
	private BigDecimal cardSettlementDiscountMoney;
	private Date cardSettlementLastPaymentDate;
	private Boolean cardSettlementSynchFlag;
	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "cardSettlementNo", updatable=false, insertable=false)
	private List<CardSettlementDetail> cardSettlementDetails = new ArrayList<CardSettlementDetail>();

	public Boolean getCardSettlementSynchFlag() {
		return cardSettlementSynchFlag;
	}

	public void setCardSettlementSynchFlag(Boolean cardSettlementSynchFlag) {
		this.cardSettlementSynchFlag = cardSettlementSynchFlag;
	}

	public String getCardSettlementNo() {
		return this.cardSettlementNo;
	}

	public void setCardSettlementNo(String cardSettlementNo) {
		this.cardSettlementNo = cardSettlementNo;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getToSystemBookCode() {
		return this.toSystemBookCode;
	}

	public void setToSystemBookCode(String toSystemBookCode) {
		this.toSystemBookCode = toSystemBookCode;
	}

	public Integer getToBranchNum() {
		return this.toBranchNum;
	}

	public void setToBranchNum(Integer toBranchNum) {
		this.toBranchNum = toBranchNum;
	}

	public Date getCardSettlementDate() {
		return this.cardSettlementDate;
	}

	public void setCardSettlementDate(Date cardSettlementDate) {
		this.cardSettlementDate = cardSettlementDate;
	}

	public String getCardSettlementType() {
		return this.cardSettlementType;
	}

	public void setCardSettlementType(String cardSettlementType) {
		this.cardSettlementType = cardSettlementType;
	}

	public String getCardSettlementPaymentType() {
		return this.cardSettlementPaymentType;
	}

	public void setCardSettlementPaymentType(String cardSettlementPaymentType) {
		this.cardSettlementPaymentType = cardSettlementPaymentType;
	}

	public String getCardSettlementMemo() {
		return this.cardSettlementMemo;
	}

	public void setCardSettlementMemo(String cardSettlementMemo) {
		this.cardSettlementMemo = cardSettlementMemo;
	}

	public String getCardSettlementCreator() {
		return this.cardSettlementCreator;
	}

	public void setCardSettlementCreator(String cardSettlementCreator) {
		this.cardSettlementCreator = cardSettlementCreator;
	}

	public Date getCardSettlementCreateTime() {
		return this.cardSettlementCreateTime;
	}

	public void setCardSettlementCreateTime(Date cardSettlementCreateTime) {
		this.cardSettlementCreateTime = cardSettlementCreateTime;
	}

	public String getCardSettlementAuditor() {
		return this.cardSettlementAuditor;
	}

	public void setCardSettlementAuditor(String cardSettlementAuditor) {
		this.cardSettlementAuditor = cardSettlementAuditor;
	}

	public Date getCardSettlementAuditTime() {
		return this.cardSettlementAuditTime;
	}

	public void setCardSettlementAuditTime(Date cardSettlementAuditTime) {
		this.cardSettlementAuditTime = cardSettlementAuditTime;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getCardSettlementRefBillNo() {
		return this.cardSettlementRefBillNo;
	}

	public void setCardSettlementRefBillNo(String cardSettlementRefBillNo) {
		this.cardSettlementRefBillNo = cardSettlementRefBillNo;
	}

	public BigDecimal getCardSettlementDepositCash() {
		return this.cardSettlementDepositCash;
	}

	public void setCardSettlementDepositCash(
			BigDecimal cardSettlementDepositCash) {
		this.cardSettlementDepositCash = cardSettlementDepositCash;
	}

	public BigDecimal getCardSettlementDepositMoney() {
		return this.cardSettlementDepositMoney;
	}

	public void setCardSettlementDepositMoney(
			BigDecimal cardSettlementDepositMoney) {
		this.cardSettlementDepositMoney = cardSettlementDepositMoney;
	}

	public BigDecimal getCardSettlementConsumeMoney() {
		return this.cardSettlementConsumeMoney;
	}

	public void setCardSettlementConsumeMoney(
			BigDecimal cardSettlementConsumeMoney) {
		this.cardSettlementConsumeMoney = cardSettlementConsumeMoney;
	}

	public BigDecimal getCardSettlementMoney() {
		return this.cardSettlementMoney;
	}

	public void setCardSettlementMoney(BigDecimal cardSettlementMoney) {
		this.cardSettlementMoney = cardSettlementMoney;
	}

	public Integer getAccountBankNum() {
		return this.accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public String getCardSettlementPreNo() {
		return this.cardSettlementPreNo;
	}

	public void setCardSettlementPreNo(String cardSettlementPreNo) {
		this.cardSettlementPreNo = cardSettlementPreNo;
	}

	public BigDecimal getCardSettlementPaidMoney() {
		return this.cardSettlementPaidMoney;
	}

	public void setCardSettlementPaidMoney(BigDecimal cardSettlementPaidMoney) {
		if(cardSettlementPaidMoney != null){
			cardSettlementPaidMoney = cardSettlementPaidMoney.setScale(2, BigDecimal.ROUND_HALF_UP);
		}
		this.cardSettlementPaidMoney = cardSettlementPaidMoney;
	}

	public BigDecimal getCardSettlementDiscountMoney() {
		return this.cardSettlementDiscountMoney;
	}

	public void setCardSettlementDiscountMoney(
			BigDecimal cardSettlementDiscountMoney) {
		if(cardSettlementDiscountMoney != null){
			cardSettlementDiscountMoney = cardSettlementDiscountMoney.setScale(2, BigDecimal.ROUND_HALF_UP);
		}
		this.cardSettlementDiscountMoney = cardSettlementDiscountMoney;
	}

	public Date getCardSettlementLastPaymentDate() {
		return this.cardSettlementLastPaymentDate;
	}

	public void setCardSettlementLastPaymentDate(
			Date cardSettlementLastPaymentDate) {
		this.cardSettlementLastPaymentDate = cardSettlementLastPaymentDate;
	}

	public List<CardSettlementDetail> getCardSettlementDetails() {
		return cardSettlementDetails;
	}

	public void setCardSettlementDetails(
			List<CardSettlementDetail> cardSettlementDetails) {
		this.cardSettlementDetails = cardSettlementDetails;
	}

	public BigDecimal getCardSettlementReConsumeMoney() {
		return cardSettlementReConsumeMoney;
	}

	public void setCardSettlementReConsumeMoney(
			BigDecimal cardSettlementReConsumeMoney) {
		this.cardSettlementReConsumeMoney = cardSettlementReConsumeMoney;
	}

	public BigDecimal getCardSettlementUnConsumeMoney() {
		return cardSettlementUnConsumeMoney;
	}

	public void setCardSettlementUnConsumeMoney(
			BigDecimal cardSettlementUnConsumeMoney) {
		this.cardSettlementUnConsumeMoney = cardSettlementUnConsumeMoney;
	}

	public static List<CardSettlementDetail> findDetails(List<CardSettlementDetail> cardSettlementDetails, String cardSettlementNo) {
		List<CardSettlementDetail> list = new ArrayList<CardSettlementDetail>();
		CardSettlementDetail detail = null;
		for(int i = cardSettlementDetails.size() - 1;i >= 0;i--){
			detail = cardSettlementDetails.get(i);
			if(detail.getId().getCardSettlementNo().equals(cardSettlementNo)){
				list.add(detail);
				cardSettlementDetails.remove(i);
			}
		}
		return list;
	}

}
