package com.nhsoft.module.report.model;


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * CardUserLog generated by hbm2java
 */
@Entity
public class CardUserLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4259835430645423064L;
	@Id
	private String cardUserLogFid;
	private Integer cardUserNum;
	private String systemBookCode;
	private Integer branchNum;
	private String cardUserLogType;
	private String cardUserLogOperator;
	private Date cardUserLogTime;
	private String cardUserLogBranchName;
	private String cardUserLogMemo;
	private String cardUserLogContext;
	private String shiftTableBizday;
	private Integer shiftTableNum;
	private BigDecimal cardUserRevokeMoney;

	//临时属性
	@Transient
	private String cardUserCustName;
	@Transient
	private String cardUserPrintedNum;
	@Transient
	private Integer cardUserCardType;
	
	//查询用
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="cardUserNum", insertable=false, updatable=false)
	private CardUser cardUser;

	public CardUserLog() {
	}

	public String getShiftTableBizday() {
		return shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public Integer getShiftTableNum() {
		return shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public BigDecimal getCardUserRevokeMoney() {
		return cardUserRevokeMoney;
	}

	public void setCardUserRevokeMoney(BigDecimal cardUserRevokeMoney) {
		this.cardUserRevokeMoney = cardUserRevokeMoney;
	}

	public CardUser getCardUser() {
		return cardUser;
	}

	public void setCardUser(CardUser cardUser) {
		this.cardUser = cardUser;
	}

	public Integer getCardUserCardType() {
		return cardUserCardType;
	}

	public void setCardUserCardType(Integer cardUserCardType) {
		this.cardUserCardType = cardUserCardType;
	}

	public String getCardUserCustName() {
		return cardUserCustName;
	}

	public void setCardUserCustName(String cardUserCustName) {
		this.cardUserCustName = cardUserCustName;
	}

	public String getCardUserPrintedNum() {
		return cardUserPrintedNum;
	}

	public void setCardUserPrintedNum(String cardUserPrintedNum) {
		this.cardUserPrintedNum = cardUserPrintedNum;
	}

	public String getCardUserLogFid() {
		return this.cardUserLogFid;
	}

	public void setCardUserLogFid(String cardUserLogFid) {
		this.cardUserLogFid = cardUserLogFid;
	}

	public Integer getCardUserNum() {
		return this.cardUserNum;
	}

	public void setCardUserNum(Integer cardUserNum) {
		this.cardUserNum = cardUserNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getCardUserLogType() {
		return this.cardUserLogType;
	}

	public void setCardUserLogType(String cardUserLogType) {
		this.cardUserLogType = cardUserLogType;
	}

	public String getCardUserLogOperator() {
		return this.cardUserLogOperator;
	}

	public void setCardUserLogOperator(String cardUserLogOperator) {
		this.cardUserLogOperator = cardUserLogOperator;
	}

	public Date getCardUserLogTime() {
		return this.cardUserLogTime;
	}

	public void setCardUserLogTime(Date cardUserLogTime) {
		this.cardUserLogTime = cardUserLogTime;
	}

	public String getCardUserLogBranchName() {
		return this.cardUserLogBranchName;
	}

	public void setCardUserLogBranchName(String cardUserLogBranchName) {
		this.cardUserLogBranchName = cardUserLogBranchName;
	}

	public String getCardUserLogMemo() {
		return this.cardUserLogMemo;
	}

	public void setCardUserLogMemo(String cardUserLogMemo) {
		this.cardUserLogMemo = cardUserLogMemo;
	}

	public String getCardUserLogContext() {
		return this.cardUserLogContext;
	}

	public void setCardUserLogContext(String cardUserLogContext) {
		this.cardUserLogContext = cardUserLogContext;
	}

}
