package com.nhsoft.module.report.model;


import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

/**
 * CardLoss generated by hbm2java
 */
@Entity
public class CardLoss implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2520198209178746665L;
	@Id
	private String cardLossFid;
	private Integer cardUserNum;
	private String systemBookCode;
	private Date cardLossOperateTime;
	private String cardLossOperator;
	private String cardLossBranchName;
	private String cardLossPrintedNum;
	private String cardLossPhysicalNum;
	private String cardLossCustName;
	private Integer cardLossCardType;
	private String cardLossOperateName;
	private String cardLossMemo;

	public CardLoss() {
	}

	public Integer getCardUserNum() {
		return cardUserNum;
	}

	public void setCardUserNum(Integer cardUserNum) {
		this.cardUserNum = cardUserNum;
	}

	public String getSystemBookCode() {
		return systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getCardLossFid() {
		return this.cardLossFid;
	}

	public void setCardLossFid(String cardLossFid) {
		this.cardLossFid = cardLossFid;
	}

	public Date getCardLossOperateTime() {
		return this.cardLossOperateTime;
	}

	public void setCardLossOperateTime(Date cardLossOperateTime) {
		this.cardLossOperateTime = cardLossOperateTime;
	}

	public String getCardLossOperator() {
		return this.cardLossOperator;
	}

	public void setCardLossOperator(String cardLossOperator) {
		this.cardLossOperator = cardLossOperator;
	}

	public String getCardLossBranchName() {
		return this.cardLossBranchName;
	}

	public void setCardLossBranchName(String cardLossBranchName) {
		this.cardLossBranchName = cardLossBranchName;
	}

	public String getCardLossPrintedNum() {
		return this.cardLossPrintedNum;
	}

	public void setCardLossPrintedNum(String cardLossPrintedNum) {
		this.cardLossPrintedNum = cardLossPrintedNum;
	}

	public String getCardLossPhysicalNum() {
		return this.cardLossPhysicalNum;
	}

	public void setCardLossPhysicalNum(String cardLossPhysicalNum) {
		this.cardLossPhysicalNum = cardLossPhysicalNum;
	}

	public String getCardLossCustName() {
		return this.cardLossCustName;
	}

	public void setCardLossCustName(String cardLossCustName) {
		this.cardLossCustName = cardLossCustName;
	}

	public Integer getCardLossCardType() {
		return this.cardLossCardType;
	}

	public void setCardLossCardType(Integer cardLossCardType) {
		this.cardLossCardType = cardLossCardType;
	}

	public String getCardLossOperateName() {
		return this.cardLossOperateName;
	}

	public void setCardLossOperateName(String cardLossOperateName) {
		this.cardLossOperateName = cardLossOperateName;
	}

	public String getCardLossMemo() {
		return this.cardLossMemo;
	}

	public void setCardLossMemo(String cardLossMemo) {
		this.cardLossMemo = cardLossMemo;
	}

}
