package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;


/**
 * CheckOrderDetailId generated by hbm2java
 */
@Embeddable
public class CheckOrderDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 352533659958642627L;
	private String checkOrderFid;
	private Integer checkOrderDetailNum;

	public CheckOrderDetailId() {
	}

	public CheckOrderDetailId(String checkOrderFid, Integer checkOrderDetailNum) {
		this.checkOrderFid = checkOrderFid;
		this.checkOrderDetailNum = checkOrderDetailNum;
	}

	public String getCheckOrderFid() {
		return this.checkOrderFid;
	}

	public void setCheckOrderFid(String checkOrderFid) {
		this.checkOrderFid = checkOrderFid;
	}

	public Integer getCheckOrderDetailNum() {
		return this.checkOrderDetailNum;
	}

	public void setCheckOrderDetailNum(Integer checkOrderDetailNum) {
		this.checkOrderDetailNum = checkOrderDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CheckOrderDetailId))
			return false;
		CheckOrderDetailId castOther = (CheckOrderDetailId) other;

		return ((this.getCheckOrderFid() == castOther.getCheckOrderFid()) || (this
				.getCheckOrderFid() != null
				&& castOther.getCheckOrderFid() != null && this
				.getCheckOrderFid().equals(castOther.getCheckOrderFid())))
				&& ((this.getCheckOrderDetailNum() == castOther
						.getCheckOrderDetailNum()) || (this
						.getCheckOrderDetailNum() != null
						&& castOther.getCheckOrderDetailNum() != null && this
						.getCheckOrderDetailNum().equals(
								castOther.getCheckOrderDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCheckOrderFid() == null ? 0 : this.getCheckOrderFid()
						.hashCode());
		result = 37
				* result
				+ (getCheckOrderDetailNum() == null ? 0 : this
						.getCheckOrderDetailNum().hashCode());
		return result;
	}

}
