package com.nhsoft.module.report.model;



/**
 * ClientSettlementDetailId generated by hbm2java
 */
public class ClientSettlementDetailId implements java.io.Serializable {

	private static final long serialVersionUID = 4291511543653288178L;
	private String clientSettlementNo;
	private Integer clientSettlementDetailNum;

	public ClientSettlementDetailId() {
	}

	public ClientSettlementDetailId(String clientSettlementNo,
			Integer clientSettlementDetailNum) {
		this.clientSettlementNo = clientSettlementNo;
		this.clientSettlementDetailNum = clientSettlementDetailNum;
	}

	public String getClientSettlementNo() {
		return this.clientSettlementNo;
	}

	public void setClientSettlementNo(String clientSettlementNo) {
		this.clientSettlementNo = clientSettlementNo;
	}

	public Integer getClientSettlementDetailNum() {
		return this.clientSettlementDetailNum;
	}

	public void setClientSettlementDetailNum(Integer clientSettlementDetailNum) {
		this.clientSettlementDetailNum = clientSettlementDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientSettlementDetailId))
			return false;
		ClientSettlementDetailId castOther = (ClientSettlementDetailId) other;

		return ((this.getClientSettlementNo() == castOther
				.getClientSettlementNo()) || (this.getClientSettlementNo() != null
				&& castOther.getClientSettlementNo() != null && this
				.getClientSettlementNo().equals(
						castOther.getClientSettlementNo())))
				&& ((this.getClientSettlementDetailNum() == castOther
						.getClientSettlementDetailNum()) || (this
						.getClientSettlementDetailNum() != null
						&& castOther.getClientSettlementDetailNum() != null && this
						.getClientSettlementDetailNum().equals(
								castOther.getClientSettlementDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getClientSettlementNo() == null ? 0 : this
						.getClientSettlementNo().hashCode());
		result = 37
				* result
				+ (getClientSettlementDetailNum() == null ? 0 : this
						.getClientSettlementDetailNum().hashCode());
		return result;
	}

}
