package com.nhsoft.module.report.model;



import com.nhsoft.module.report.query.State;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * ClientSettlement generated by hbm2java
 */
public class ClientSettlement implements java.io.Serializable {

	private static final long serialVersionUID = 9211389737987796152L;
	private String clientSettlementNo;
	private String clientFid;
	private String systemBookCode;
	private Integer branchNum;
	private String clientSettlementClientAddress;
	private String clientSettlementClientName;
	private Date clientSettlementDate;
	private String clientSettlementPaymentType;
	private String clientSettlementMemo;
	private String clientSettlementCreator;
	private Date clientSettlementCreateTime;
	private String clientSettlementAuditor;
	private Date clientSettlementAuditTime;
	private State state;
	private String clientSettlementRefBillNo;
	private String clientSettlementAccountNo;
	private String clientSettlementBankName;
	private BigDecimal clientSettlementTotalMoney;
	private BigDecimal clientSettlementTotalDiscount;
	private Integer accountBankNum;
	private Boolean clientSettlementSyncFlag;
	private String clientSettlementUuid;
	private List<ClientSettlementDetail> clientSettlementDetails = new ArrayList<ClientSettlementDetail>(0);
	private List<ClientPreSettlementDetail> clientPreSettlementDetails = new ArrayList<ClientPreSettlementDetail>();
	
	private Boolean flag;//标记用于判断审核时是否更新明细
	
	public ClientSettlement() {
	}

	public Boolean getFlag() {
		return flag;
	}

	public void setFlag(Boolean flag) {
		this.flag = flag;
	}

	public String getClientSettlementNo() {
		return this.clientSettlementNo;
	}

	public void setClientSettlementNo(String clientSettlementNo) {
		this.clientSettlementNo = clientSettlementNo;
	}

	public String getClientFid() {
		return this.clientFid;
	}

	public void setClientFid(String clientFid) {
		this.clientFid = clientFid;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getClientSettlementClientAddress() {
		return this.clientSettlementClientAddress;
	}

	public void setClientSettlementClientAddress(
			String clientSettlementClientAddress) {
		this.clientSettlementClientAddress = clientSettlementClientAddress;
	}

	public String getClientSettlementClientName() {
		return this.clientSettlementClientName;
	}

	public void setClientSettlementClientName(String clientSettlementClientName) {
		this.clientSettlementClientName = clientSettlementClientName;
	}

	public Date getClientSettlementDate() {
		return this.clientSettlementDate;
	}

	public void setClientSettlementDate(Date clientSettlementDate) {
		this.clientSettlementDate = clientSettlementDate;
	}

	public String getClientSettlementPaymentType() {
		return this.clientSettlementPaymentType;
	}

	public void setClientSettlementPaymentType(
			String clientSettlementPaymentType) {
		this.clientSettlementPaymentType = clientSettlementPaymentType;
	}

	public String getClientSettlementMemo() {
		return this.clientSettlementMemo;
	}

	public void setClientSettlementMemo(String clientSettlementMemo) {
		this.clientSettlementMemo = clientSettlementMemo;
	}

	public String getClientSettlementCreator() {
		return this.clientSettlementCreator;
	}

	public void setClientSettlementCreator(String clientSettlementCreator) {
		this.clientSettlementCreator = clientSettlementCreator;
	}

	public Date getClientSettlementCreateTime() {
		return this.clientSettlementCreateTime;
	}

	public void setClientSettlementCreateTime(Date clientSettlementCreateTime) {
		this.clientSettlementCreateTime = clientSettlementCreateTime;
	}

	public String getClientSettlementAuditor() {
		return this.clientSettlementAuditor;
	}

	public void setClientSettlementAuditor(String clientSettlementAuditor) {
		this.clientSettlementAuditor = clientSettlementAuditor;
	}

	public Date getClientSettlementAuditTime() {
		return this.clientSettlementAuditTime;
	}

	public void setClientSettlementAuditTime(Date clientSettlementAuditTime) {
		this.clientSettlementAuditTime = clientSettlementAuditTime;
	}

	public String getClientSettlementRefBillNo() {
		return this.clientSettlementRefBillNo;
	}

	public void setClientSettlementRefBillNo(String clientSettlementRefBillNo) {
		this.clientSettlementRefBillNo = clientSettlementRefBillNo;
	}

	public String getClientSettlementAccountNo() {
		return this.clientSettlementAccountNo;
	}

	public void setClientSettlementAccountNo(String clientSettlementAccountNo) {
		this.clientSettlementAccountNo = clientSettlementAccountNo;
	}

	public String getClientSettlementBankName() {
		return this.clientSettlementBankName;
	}

	public void setClientSettlementBankName(String clientSettlementBankName) {
		this.clientSettlementBankName = clientSettlementBankName;
	}

	public BigDecimal getClientSettlementTotalMoney() {
		return this.clientSettlementTotalMoney;
	}

	public void setClientSettlementTotalMoney(
			BigDecimal clientSettlementTotalMoney) {
		this.clientSettlementTotalMoney = clientSettlementTotalMoney;
	}

	public BigDecimal getClientSettlementTotalDiscount() {
		return this.clientSettlementTotalDiscount;
	}

	public void setClientSettlementTotalDiscount(
			BigDecimal clientSettlementTotalDiscount) {
		this.clientSettlementTotalDiscount = clientSettlementTotalDiscount;
	}

	public Integer getAccountBankNum() {
		return this.accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public Boolean getClientSettlementSyncFlag() {
		return this.clientSettlementSyncFlag;
	}

	public void setClientSettlementSyncFlag(Boolean clientSettlementSyncFlag) {
		this.clientSettlementSyncFlag = clientSettlementSyncFlag;
	}

	public String getClientSettlementUuid() {
		return this.clientSettlementUuid;
	}

	public void setClientSettlementUuid(String clientSettlementUuid) {
		this.clientSettlementUuid = clientSettlementUuid;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public List<ClientSettlementDetail> getClientSettlementDetails() {
		return clientSettlementDetails;
	}

	public void setClientSettlementDetails(
			List<ClientSettlementDetail> clientSettlementDetails) {
		this.clientSettlementDetails = clientSettlementDetails;
	}

	public List<ClientPreSettlementDetail> getClientPreSettlementDetails() {
		return clientPreSettlementDetails;
	}

	public void setClientPreSettlementDetails(
			List<ClientPreSettlementDetail> clientPreSettlementDetails) {
		this.clientPreSettlementDetails = clientPreSettlementDetails;
	}

	public boolean checkMoney(){
		if(clientPreSettlementDetails.size() == 0){
			return false;
		}
		BigDecimal preMoney = BigDecimal.ZERO;
		BigDecimal detailMoney = BigDecimal.ZERO;
		for(int i = 0;i < clientPreSettlementDetails.size();i++){
			ClientPreSettlementDetail clientPreSettlementDetail = clientPreSettlementDetails.get(i);
			preMoney = preMoney.add(clientPreSettlementDetail.getPreSettlementDetailMoney().setScale(2, BigDecimal.ROUND_HALF_UP));
		}
		
		for(int i = 0;i < clientSettlementDetails.size();i++){
			ClientSettlementDetail clientSettlementDetail = clientSettlementDetails.get(i);
			detailMoney = detailMoney.add(clientSettlementDetail.getClientSettlementDetailMoney().setScale(2, BigDecimal.ROUND_HALF_UP));
		}
		if(preMoney.compareTo(detailMoney) != 0){
			return true;
		}		
		return false;
	}
}
