package com.nhsoft.module.report.model;


import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.math.BigDecimal;

/**
 * ClientSettlementDetail generated by hbm2java
 */
@Entity
public class ClientSettlementDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7120828164322583411L;
	@EmbeddedId
	private ClientSettlementDetailId id;
	private BigDecimal clientSettlementDetailMoney;
	private BigDecimal clientSettlementDetailDiscount;
	private String clientSettlementDetailMemo;
	private Integer clientSettlementBranchNum;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="wholesaleOrderFid")
	private WholesaleOrder wholesaleOrder;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="wholesaleReturnFid")
	private WholesaleReturn wholesaleReturn;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="otherInoutBillNo")
	private OtherInout otherInout;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="paymentNo")
	private Payment payment;

	public ClientSettlementDetail() {
	}

	public ClientSettlementDetailId getId() {
		return this.id;
	}

	public void setId(ClientSettlementDetailId id) {
		this.id = id;
	}

	public BigDecimal getClientSettlementDetailMoney() {
		return this.clientSettlementDetailMoney;
	}

	public void setClientSettlementDetailMoney(
			BigDecimal clientSettlementDetailMoney) {
		this.clientSettlementDetailMoney = clientSettlementDetailMoney;
	}

	public BigDecimal getClientSettlementDetailDiscount() {
		return this.clientSettlementDetailDiscount;
	}

	public void setClientSettlementDetailDiscount(
			BigDecimal clientSettlementDetailDiscount) {
		this.clientSettlementDetailDiscount = clientSettlementDetailDiscount;
	}

	public String getClientSettlementDetailMemo() {
		return this.clientSettlementDetailMemo;
	}

	public void setClientSettlementDetailMemo(String clientSettlementDetailMemo) {
		this.clientSettlementDetailMemo = clientSettlementDetailMemo;
	}

	public Integer getClientSettlementBranchNum() {
		return this.clientSettlementBranchNum;
	}

	public void setClientSettlementBranchNum(Integer clientSettlementBranchNum) {
		this.clientSettlementBranchNum = clientSettlementBranchNum;
	}

	public WholesaleOrder getWholesaleOrder() {
		return wholesaleOrder;
	}

	public void setWholesaleOrder(WholesaleOrder wholesaleOrder) {
		this.wholesaleOrder = wholesaleOrder;
	}

	public WholesaleReturn getWholesaleReturn() {
		return wholesaleReturn;
	}

	public void setWholesaleReturn(WholesaleReturn wholesaleReturn) {
		this.wholesaleReturn = wholesaleReturn;
	}

	public OtherInout getOtherInout() {
		return otherInout;
	}

	public void setOtherInout(OtherInout otherInout) {
		this.otherInout = otherInout;
	}

	public Payment getPayment() {
		return payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

}
