package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import java.math.BigDecimal;

/**
 * DistributionCentreMatrix generated by hbm2java
 */
@Entity
public class DistributionCentreMatrix implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4285438032940728463L;
	@EmbeddedId
	private DistributionCentreMatrixId id;
	private boolean dcmRecommended;
	private boolean dcmRequestNew;
	private BigDecimal dcmRequestLowerLimit;
	private BigDecimal dcmRequestUpperLimit;
	private BigDecimal dcmOutAmountOne;
	private BigDecimal dcmOutAmountTwo;
	private BigDecimal dcmTotalOutAmount;
	private BigDecimal dcmRequestAmountOne;
	private BigDecimal dcmRequestAmountTwo;
	private BigDecimal dcmTotalRequestAmount;
	private BigDecimal dcmWholesaleAmountOne;
	private BigDecimal dcmWholesaleAmountTwo;
	private BigDecimal dcmTotalWholesaleAmount;

	public DistributionCentreMatrix() {
		dcmOutAmountOne = BigDecimal.ZERO;
		dcmOutAmountTwo = BigDecimal.ZERO;
		dcmTotalOutAmount = BigDecimal.ZERO;
		dcmRequestAmountOne = BigDecimal.ZERO;
		dcmRequestAmountTwo = BigDecimal.ZERO;
		dcmTotalRequestAmount = BigDecimal.ZERO;
		dcmWholesaleAmountOne = BigDecimal.ZERO;
		dcmWholesaleAmountTwo = BigDecimal.ZERO;
		dcmTotalWholesaleAmount = BigDecimal.ZERO;
		dcmRecommended = false;
		dcmRequestNew = false;
	}

	public DistributionCentreMatrix(DistributionCentreMatrixId id,
			boolean dcmRecommended, boolean dcmRequestNew) {
		this.id = id;
		this.dcmRecommended = dcmRecommended;
		this.dcmRequestNew = dcmRequestNew;
	}

	public DistributionCentreMatrixId getId() {
		return this.id;
	}

	public void setId(DistributionCentreMatrixId id) {
		this.id = id;
	}

	public boolean isDcmRecommended() {
		return this.dcmRecommended;
	}

	public void setDcmRecommended(boolean dcmRecommended) {
		this.dcmRecommended = dcmRecommended;
	}

	public boolean isDcmRequestNew() {
		return this.dcmRequestNew;
	}

	public void setDcmRequestNew(boolean dcmRequestNew) {
		this.dcmRequestNew = dcmRequestNew;
	}

	public BigDecimal getDcmRequestLowerLimit() {
		return this.dcmRequestLowerLimit;
	}

	public void setDcmRequestLowerLimit(BigDecimal dcmRequestLowerLimit) {
		this.dcmRequestLowerLimit = dcmRequestLowerLimit;
	}

	public BigDecimal getDcmRequestUpperLimit() {
		return this.dcmRequestUpperLimit;
	}

	public void setDcmRequestUpperLimit(BigDecimal dcmRequestUpperLimit) {
		this.dcmRequestUpperLimit = dcmRequestUpperLimit;
	}

	public BigDecimal getDcmOutAmountOne() {
		return this.dcmOutAmountOne;
	}

	public void setDcmOutAmountOne(BigDecimal dcmOutAmountOne) {
		this.dcmOutAmountOne = dcmOutAmountOne;
	}

	public BigDecimal getDcmOutAmountTwo() {
		return this.dcmOutAmountTwo;
	}

	public void setDcmOutAmountTwo(BigDecimal dcmOutAmountTwo) {
		this.dcmOutAmountTwo = dcmOutAmountTwo;
	}

	public BigDecimal getDcmTotalOutAmount() {
		
		return this.dcmTotalOutAmount == null?BigDecimal.ZERO:this.dcmTotalOutAmount;
	}

	public void setDcmTotalOutAmount(BigDecimal dcmTotalOutAmount) {
		this.dcmTotalOutAmount = dcmTotalOutAmount;
	}

	public BigDecimal getDcmRequestAmountOne() {
		return this.dcmRequestAmountOne;
	}

	public void setDcmRequestAmountOne(BigDecimal dcmRequestAmountOne) {
		this.dcmRequestAmountOne = dcmRequestAmountOne;
	}

	public BigDecimal getDcmRequestAmountTwo() {
		return this.dcmRequestAmountTwo;
	}

	public void setDcmRequestAmountTwo(BigDecimal dcmRequestAmountTwo) {
		this.dcmRequestAmountTwo = dcmRequestAmountTwo;
	}

	public BigDecimal getDcmTotalRequestAmount() {
		return this.dcmTotalRequestAmount == null?BigDecimal.ZERO:this.dcmTotalRequestAmount;
	}

	public void setDcmTotalRequestAmount(BigDecimal dcmTotalRequestAmount) {
		this.dcmTotalRequestAmount = dcmTotalRequestAmount;
	}

	public BigDecimal getDcmWholesaleAmountOne() {
		return dcmWholesaleAmountOne;
	}

	public void setDcmWholesaleAmountOne(BigDecimal dcmWholesaleAmountOne) {
		this.dcmWholesaleAmountOne = dcmWholesaleAmountOne;
	}

	public BigDecimal getDcmWholesaleAmountTwo() {
		return dcmWholesaleAmountTwo;
	}

	public void setDcmWholesaleAmountTwo(BigDecimal dcmWholesaleAmountTwo) {
		this.dcmWholesaleAmountTwo = dcmWholesaleAmountTwo;
	}

	public BigDecimal getDcmTotalWholesaleAmount() {
		return this.dcmTotalWholesaleAmount == null?BigDecimal.ZERO:this.dcmTotalWholesaleAmount;

	}

	public void setDcmTotalWholesaleAmount(BigDecimal dcmTotalWholesaleAmount) {
		this.dcmTotalWholesaleAmount = dcmTotalWholesaleAmount;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DistributionCentreMatrix other = (DistributionCentreMatrix) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
