package com.nhsoft.module.report.model;



import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * InOrderDetail generated by hbm2java
 */
public class InOrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 4009918228940168544L;
	private InOrderDetailId id;
	private Integer itemNum;
	private String inOrderDetailItemName;
	private BigDecimal inOrderDetailQty;
	private BigDecimal inOrderDetailAssistQty;
	private BigDecimal inOrderDetailInventoryQty;
	private BigDecimal inOrderDetailInventoryAssistQty;
	private BigDecimal inOrderDetailCustOrderQty;
	private Integer inOrderDetailItemMatrixNum;
	private BigDecimal inOrderDetailCost;
	private BigDecimal inOrderDetailSubtotal;
	private String inOrderDetailItemUnit;
	private String inOrderDetailItemAssistUnit;
	private String inOrderDetailMemo;
	private Date inOrderDetailInvalidDate;
	private BigDecimal inOrderDetailPrice;
	private BigDecimal inOrderDetailSaleSubtotal;
	private BigDecimal inOrderDetailTaxRate;
	private Date inOrderDetailProducingDate;
	private String inOrderDetailLotNumber;
	private String inOrderDetailUseUnit;
	private BigDecimal inOrderDetailUseQty;
	private BigDecimal inOrderDetailUsePrice;
	private BigDecimal inOrderDetailUseRate;
	private String inOrderDetailItemCode;
	private String inOrderDetailItemSpec;
	private String inOrderDetailPeriod;
	private BigDecimal inOrderDetailSalePrice;
	private String inOrderDetailPresentUnit;
	private BigDecimal inOrderDetailPresentUseQty;
	private BigDecimal inOrderDetailPresentQty;
	private BigDecimal inOrderDetailPresentAssistQty;
	private String inOrderDetailRefBill; //order_task_detail_fid
	private BigDecimal inOrderDetailOtherFee;
	private BigDecimal inOrderDetailTare;
	private Boolean inOrderDetailConfirm; 
	private Integer supplierNum;
	private BigDecimal inOrderDetailActualTare;

	//临时属性
	private TransferInOrder transferInOrder;
	private BigDecimal itemInventoryRate;
	private ItemMatrix itemMatrix;

    public InOrderDetail() {
	}
	
	public BigDecimal getInOrderDetailActualTare() {
		return inOrderDetailActualTare;
	}

	public void setInOrderDetailActualTare(BigDecimal inOrderDetailActualTare) {
		this.inOrderDetailActualTare = inOrderDetailActualTare;
	}

	public Integer getSupplierNum() {
		return supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public Boolean getInOrderDetailConfirm() {
		return inOrderDetailConfirm;
	}

	public void setInOrderDetailConfirm(Boolean inOrderDetailConfirm) {
		this.inOrderDetailConfirm = inOrderDetailConfirm;
	}

	public BigDecimal getInOrderDetailTare() {
		return inOrderDetailTare;
	}

	public void setInOrderDetailTare(BigDecimal inOrderDetailTare) {
		this.inOrderDetailTare = inOrderDetailTare;
	}

	public BigDecimal getInOrderDetailOtherFee() {
		return inOrderDetailOtherFee;
	}

	public void setInOrderDetailOtherFee(BigDecimal inOrderDetailOtherFee) {
		this.inOrderDetailOtherFee = inOrderDetailOtherFee;
	}

	public TransferInOrder getTransferInOrder() {
		return transferInOrder;
	}

	public void setTransferInOrder(TransferInOrder transferInOrder) {
		this.transferInOrder = transferInOrder;
	}

	public String getInOrderDetailRefBill() {
		return inOrderDetailRefBill;
	}

	public void setInOrderDetailRefBill(String inOrderDetailRefBill) {
		this.inOrderDetailRefBill = inOrderDetailRefBill;
	}

	public InOrderDetailId getId() {
		return this.id;
	}

	public void setId(InOrderDetailId id) {
		this.id = id;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getInOrderDetailItemName() {
		return this.inOrderDetailItemName;
	}

	public void setInOrderDetailItemName(String inOrderDetailItemName) {
		this.inOrderDetailItemName = inOrderDetailItemName;
	}

	public BigDecimal getInOrderDetailQty() {
		return this.inOrderDetailQty;
	}

	public void setInOrderDetailQty(BigDecimal inOrderDetailQty) {
		this.inOrderDetailQty = inOrderDetailQty;
	}

	public BigDecimal getInOrderDetailAssistQty() {
		return this.inOrderDetailAssistQty;
	}

	public void setInOrderDetailAssistQty(BigDecimal inOrderDetailAssistQty) {
		this.inOrderDetailAssistQty = inOrderDetailAssistQty;
	}

	public BigDecimal getInOrderDetailInventoryQty() {
		return this.inOrderDetailInventoryQty;
	}

	public void setInOrderDetailInventoryQty(
			BigDecimal inOrderDetailInventoryQty) {
		this.inOrderDetailInventoryQty = inOrderDetailInventoryQty;
	}

	public BigDecimal getInOrderDetailInventoryAssistQty() {
		return this.inOrderDetailInventoryAssistQty;
	}

	public void setInOrderDetailInventoryAssistQty(
			BigDecimal inOrderDetailInventoryAssistQty) {
		this.inOrderDetailInventoryAssistQty = inOrderDetailInventoryAssistQty;
	}

	public BigDecimal getInOrderDetailCustOrderQty() {
		return this.inOrderDetailCustOrderQty;
	}

	public void setInOrderDetailCustOrderQty(
			BigDecimal inOrderDetailCustOrderQty) {
		this.inOrderDetailCustOrderQty = inOrderDetailCustOrderQty;
	}

	public Integer getInOrderDetailItemMatrixNum() {
		return this.inOrderDetailItemMatrixNum;
	}

	public void setInOrderDetailItemMatrixNum(Integer inOrderDetailItemMatrixNum) {
		this.inOrderDetailItemMatrixNum = inOrderDetailItemMatrixNum;
	}

	public BigDecimal getInOrderDetailCost() {
		return this.inOrderDetailCost;
	}

	public void setInOrderDetailCost(BigDecimal inOrderDetailCost) {
		this.inOrderDetailCost = inOrderDetailCost;
	}

	public BigDecimal getInOrderDetailSubtotal() {
		return this.inOrderDetailSubtotal;
	}

	public void setInOrderDetailSubtotal(BigDecimal inOrderDetailSubtotal) {
		this.inOrderDetailSubtotal = inOrderDetailSubtotal;
	}

	public String getInOrderDetailItemUnit() {
		return this.inOrderDetailItemUnit;
	}

	public void setInOrderDetailItemUnit(String inOrderDetailItemUnit) {
		this.inOrderDetailItemUnit = inOrderDetailItemUnit;
	}

	public String getInOrderDetailItemAssistUnit() {
		return this.inOrderDetailItemAssistUnit;
	}

	public void setInOrderDetailItemAssistUnit(
			String inOrderDetailItemAssistUnit) {
		this.inOrderDetailItemAssistUnit = inOrderDetailItemAssistUnit;
	}

	public String getInOrderDetailMemo() {
		return this.inOrderDetailMemo;
	}

	public void setInOrderDetailMemo(String inOrderDetailMemo) {
		this.inOrderDetailMemo = inOrderDetailMemo;
	}

	public Date getInOrderDetailInvalidDate() {
		return this.inOrderDetailInvalidDate;
	}

	public void setInOrderDetailInvalidDate(Date inOrderDetailInvalidDate) {
		this.inOrderDetailInvalidDate = inOrderDetailInvalidDate;
	}

	public BigDecimal getInOrderDetailPrice() {
		return this.inOrderDetailPrice;
	}

	public void setInOrderDetailPrice(BigDecimal inOrderDetailPrice) {
		this.inOrderDetailPrice = inOrderDetailPrice;
	}

	public BigDecimal getInOrderDetailSaleSubtotal() {
		return this.inOrderDetailSaleSubtotal;
	}

	public void setInOrderDetailSaleSubtotal(
			BigDecimal inOrderDetailSaleSubtotal) {
		this.inOrderDetailSaleSubtotal = inOrderDetailSaleSubtotal;
	}


	public BigDecimal getInOrderDetailTaxRate() {
		return inOrderDetailTaxRate;
	}

	public void setInOrderDetailTaxRate(BigDecimal inOrderDetailTaxRate) {
		this.inOrderDetailTaxRate = inOrderDetailTaxRate;
	}

	public Date getInOrderDetailProducingDate() {
		return this.inOrderDetailProducingDate;
	}

	public void setInOrderDetailProducingDate(Date inOrderDetailProducingDate) {
		this.inOrderDetailProducingDate = inOrderDetailProducingDate;
	}

	public String getInOrderDetailLotNumber() {
		return this.inOrderDetailLotNumber;
	}

	public void setInOrderDetailLotNumber(String inOrderDetailLotNumber) {
		this.inOrderDetailLotNumber = inOrderDetailLotNumber;
	}

	public String getInOrderDetailUseUnit() {
		return this.inOrderDetailUseUnit;
	}

	public void setInOrderDetailUseUnit(String inOrderDetailUseUnit) {
		this.inOrderDetailUseUnit = inOrderDetailUseUnit;
	}

	public BigDecimal getInOrderDetailUseQty() {
		return this.inOrderDetailUseQty;
	}

	public void setInOrderDetailUseQty(BigDecimal inOrderDetailUseQty) {
		this.inOrderDetailUseQty = inOrderDetailUseQty;
	}

	public BigDecimal getInOrderDetailUsePrice() {
		return this.inOrderDetailUsePrice;
	}

	public void setInOrderDetailUsePrice(BigDecimal inOrderDetailUsePrice) {
		this.inOrderDetailUsePrice = inOrderDetailUsePrice;
	}

	public BigDecimal getInOrderDetailUseRate() {
		return this.inOrderDetailUseRate;
	}

	public void setInOrderDetailUseRate(BigDecimal inOrderDetailUseRate) {
		this.inOrderDetailUseRate = inOrderDetailUseRate;
	}

	public String getInOrderDetailItemCode() {
		return this.inOrderDetailItemCode;
	}

	public void setInOrderDetailItemCode(String inOrderDetailItemCode) {
		this.inOrderDetailItemCode = inOrderDetailItemCode;
	}

	public String getInOrderDetailItemSpec() {
		return this.inOrderDetailItemSpec;
	}

	public void setInOrderDetailItemSpec(String inOrderDetailItemSpec) {
		this.inOrderDetailItemSpec = inOrderDetailItemSpec;
	}

	public String getInOrderDetailPeriod() {
		return this.inOrderDetailPeriod;
	}

	public void setInOrderDetailPeriod(String inOrderDetailPeriod) {
		this.inOrderDetailPeriod = inOrderDetailPeriod;
	}

	public BigDecimal getInOrderDetailSalePrice() {
		return this.inOrderDetailSalePrice;
	}

	public void setInOrderDetailSalePrice(BigDecimal inOrderDetailSalePrice) {
		this.inOrderDetailSalePrice = inOrderDetailSalePrice;
	}

	public BigDecimal getItemInventoryRate() {
		return itemInventoryRate;
	}

	public void setItemInventoryRate(BigDecimal itemInventoryRate) {
		this.itemInventoryRate = itemInventoryRate;
	}

	public ItemMatrix getItemMatrix() {
		return itemMatrix;
	}

	public void setItemMatrix(ItemMatrix itemMatrix) {
		this.itemMatrix = itemMatrix;
	}

	public String getInOrderDetailPresentUnit() {
		return inOrderDetailPresentUnit;
	}

	public void setInOrderDetailPresentUnit(String inOrderDetailPresentUnit) {
		this.inOrderDetailPresentUnit = inOrderDetailPresentUnit;
	}

	public BigDecimal getInOrderDetailPresentUseQty() {
		return inOrderDetailPresentUseQty;
	}

	public void setInOrderDetailPresentUseQty(BigDecimal inOrderDetailPresentUseQty) {
		this.inOrderDetailPresentUseQty = inOrderDetailPresentUseQty;
	}

	public BigDecimal getInOrderDetailPresentQty() {
		return inOrderDetailPresentQty;
	}

	public void setInOrderDetailPresentQty(BigDecimal inOrderDetailPresentQty) {
		this.inOrderDetailPresentQty = inOrderDetailPresentQty;
	}

	public BigDecimal getInOrderDetailPresentAssistQty() {
		return inOrderDetailPresentAssistQty;
	}

	public void setInOrderDetailPresentAssistQty(BigDecimal inOrderDetailPresentAssistQty) {
		this.inOrderDetailPresentAssistQty = inOrderDetailPresentAssistQty;
	}
	
	public static List<InOrderDetail> findDetails(List<InOrderDetail> inOrderDetails, String inOrderFid){
		List<InOrderDetail> list= new ArrayList<InOrderDetail>();
		for(int i = 0;i < inOrderDetails.size();i++){
			InOrderDetail inOrderDetail = inOrderDetails.get(i);
			if(inOrderDetail.getId().getInOrderFid().equals(inOrderFid)){
				list.add(inOrderDetail);
			}
		}
		return list;
	}

}
