package com.nhsoft.module.report.model;



/**
 * InvoiceChangeId generated by hbm2java
 */
public class InvoiceChangeId implements java.io.Serializable {

	private static final long serialVersionUID = 3473473648892979059L;
	private String invoiceChangeNo;
	private String systemBookCode;
	private Integer branchNum;
	private Integer shiftTableNum;
	private String shiftTableBizday;

	public InvoiceChangeId() {
	}

	public String getInvoiceChangeNo() {
		return this.invoiceChangeNo;
	}

	public void setInvoiceChangeNo(String invoiceChangeNo) {
		this.invoiceChangeNo = invoiceChangeNo;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getShiftTableNum() {
		return this.shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((branchNum == null) ? 0 : branchNum.hashCode());
		result = prime * result + ((invoiceChangeNo == null) ? 0 : invoiceChangeNo.hashCode());
		result = prime * result + ((shiftTableBizday == null) ? 0 : shiftTableBizday.hashCode());
		result = prime * result + ((shiftTableNum == null) ? 0 : shiftTableNum.hashCode());
		result = prime * result + ((systemBookCode == null) ? 0 : systemBookCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		InvoiceChangeId other = (InvoiceChangeId) obj;
		if (branchNum == null) {
			if (other.branchNum != null)
				return false;
		} else if (!branchNum.equals(other.branchNum))
			return false;
		if (invoiceChangeNo == null) {
			if (other.invoiceChangeNo != null)
				return false;
		} else if (!invoiceChangeNo.equals(other.invoiceChangeNo))
			return false;
		if (shiftTableBizday == null) {
			if (other.shiftTableBizday != null)
				return false;
		} else if (!shiftTableBizday.equals(other.shiftTableBizday))
			return false;
		if (shiftTableNum == null) {
			if (other.shiftTableNum != null)
				return false;
		} else if (!shiftTableNum.equals(other.shiftTableNum))
			return false;
		if (systemBookCode == null) {
			if (other.systemBookCode != null)
				return false;
		} else if (!systemBookCode.equals(other.systemBookCode))
			return false;
		return true;
	}


}
