package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * InvoiceChange generated by hbm2java
 */
@Entity
public class InvoiceChange implements java.io.Serializable {

	private static final long serialVersionUID = -1586730787330588406L;
	@EmbeddedId
	private InvoiceChangeId id;
	private String orderNo;
	private String invoiceChangeContent;
	private Date invoiceChangeDate;
	private String invoiceChangeAuditor;
	private String invoiceChangeMachine;
	private BigDecimal invoiceChangeMoney;
	
	//临时属性
	@Transient
	private String reSendFid;

	public InvoiceChange() {
	}

	public String getReSendFid() {
		return reSendFid;
	}

	public void setReSendFid(String reSendFid) {
		this.reSendFid = reSendFid;
	}

	public BigDecimal getInvoiceChangeMoney() {
		return invoiceChangeMoney;
	}

	public void setInvoiceChangeMoney(BigDecimal invoiceChangeMoney) {
		this.invoiceChangeMoney = invoiceChangeMoney;
	}

	public InvoiceChangeId getId() {
		return this.id;
	}

	public void setId(InvoiceChangeId id) {
		this.id = id;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getInvoiceChangeContent() {
		return invoiceChangeContent;
	}

	public void setInvoiceChangeContent(String invoiceChangeContent) {
		this.invoiceChangeContent = invoiceChangeContent;
	}

	public Date getInvoiceChangeDate() {
		return this.invoiceChangeDate;
	}

	public void setInvoiceChangeDate(Date invoiceChangeDate) {
		this.invoiceChangeDate = invoiceChangeDate;
	}

	public String getInvoiceChangeAuditor() {
		return this.invoiceChangeAuditor;
	}

	public void setInvoiceChangeAuditor(String invoiceChangeAuditor) {
		this.invoiceChangeAuditor = invoiceChangeAuditor;
	}

	public String getInvoiceChangeMachine() {
		return this.invoiceChangeMachine;
	}

	public void setInvoiceChangeMachine(String invoiceChangeMachine) {
		this.invoiceChangeMachine = invoiceChangeMachine;
	}
	
	public static List<InvoiceChange> find(
			List<InvoiceChange> invoiceChanges, String orderNo) {
		List<InvoiceChange> list = new ArrayList<InvoiceChange>();
		for(int i = 0;i < invoiceChanges.size();i++){
			InvoiceChange invoiceChange = invoiceChanges.get(i);
			if(invoiceChange.getOrderNo().equals(orderNo)){
				list.add(invoiceChange);
			}
		}
		return list;
	}

}
