package com.nhsoft.module.report.model;



import org.apache.commons.lang3.StringUtils;

import java.math.BigDecimal;
import java.util.List;

/**
 * OnlineOrderDetail generated by hbm2java
 */
public class OnlineOrderDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3690962378155370078L;
	private OnlineOrderDetailId id;
	private Integer itemNum;
	private String onlineOrderDetailItem;
	private Integer onlineOrderDetailStateCode;
	private String onlineOrderDetailStateName;
	private BigDecimal onlineOrderDetailPrice;
	private BigDecimal onlineOrderDetailQty;
	private String onlineOrderDetailOutItem;
	private String onlineOrderDetailThumbUrl;
	private String onlineOrderDetailPicUrl;
	private BigDecimal onlineOrderDetailDiscountMoney;
	private BigDecimal onlineOrderDetailTotalMoney;
	private String onlineOrderDetailUnit;
	private BigDecimal onlineOrderDetailRate;
	private String onlineOrderDetailSpec;
	private BigDecimal onlineOrderDetailUseQty;
	private String onlineOrderDetailMemo;
	private BigDecimal onlineOrderDetailUsePrice;
	private Integer weixinItemNum;
	private String onlineOrderDetailTicketUuid;
	private String onlineOrderDetailLotNumber;
	
	private Integer weixinItemBatch;
	private Boolean weixinItemTeamOnce;

	public OnlineOrderDetail() {
	}

	public String getOnlineOrderDetailLotNumber() {
		return onlineOrderDetailLotNumber;
	}

	public void setOnlineOrderDetailLotNumber(String onlineOrderDetailLotNumber) {
		this.onlineOrderDetailLotNumber = onlineOrderDetailLotNumber;
	}

	public String getOnlineOrderDetailTicketUuid() {
		return onlineOrderDetailTicketUuid;
	}

	public void setOnlineOrderDetailTicketUuid(String onlineOrderDetailTicketUuid) {
		this.onlineOrderDetailTicketUuid = onlineOrderDetailTicketUuid;
	}

	public Integer getWeixinItemNum() {
		return weixinItemNum;
	}

	public void setWeixinItemNum(Integer weixinItemNum) {
		this.weixinItemNum = weixinItemNum;
	}

	public BigDecimal getOnlineOrderDetailUsePrice() {
		return onlineOrderDetailUsePrice;
	}

	public void setOnlineOrderDetailUsePrice(BigDecimal onlineOrderDetailUsePrice) {
		this.onlineOrderDetailUsePrice = onlineOrderDetailUsePrice;
	}

	public String getOnlineOrderDetailSpec() {
		return onlineOrderDetailSpec;
	}

	public void setOnlineOrderDetailSpec(String onlineOrderDetailSpec) {
		this.onlineOrderDetailSpec = onlineOrderDetailSpec;
	}

	public BigDecimal getOnlineOrderDetailUseQty() {
		return onlineOrderDetailUseQty;
	}

	public void setOnlineOrderDetailUseQty(BigDecimal onlineOrderDetailUseQty) {
		this.onlineOrderDetailUseQty = onlineOrderDetailUseQty;
	}

	public String getOnlineOrderDetailMemo() {
		return onlineOrderDetailMemo;
	}

	public void setOnlineOrderDetailMemo(String onlineOrderDetailMemo) {
		this.onlineOrderDetailMemo = onlineOrderDetailMemo;
	}

	public String getOnlineOrderDetailUnit() {
		return onlineOrderDetailUnit;
	}

	public void setOnlineOrderDetailUnit(String onlineOrderDetailUnit) {
		this.onlineOrderDetailUnit = onlineOrderDetailUnit;
	}

	public BigDecimal getOnlineOrderDetailRate() {
		return onlineOrderDetailRate;
	}

	public void setOnlineOrderDetailRate(BigDecimal onlineOrderDetailRate) {
		this.onlineOrderDetailRate = onlineOrderDetailRate;
	}

	public OnlineOrderDetailId getId() {
		return this.id;
	}

	public void setId(OnlineOrderDetailId id) {
		this.id = id;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getOnlineOrderDetailItem() {
		return this.onlineOrderDetailItem;
	}

	public void setOnlineOrderDetailItem(String onlineOrderDetailItem) {
		this.onlineOrderDetailItem = onlineOrderDetailItem;
	}

	public BigDecimal getOnlineOrderDetailPrice() {
		return this.onlineOrderDetailPrice;
	}

	public void setOnlineOrderDetailPrice(BigDecimal onlineOrderDetailPrice) {
		this.onlineOrderDetailPrice = onlineOrderDetailPrice;
	}

	public BigDecimal getOnlineOrderDetailQty() {
		return this.onlineOrderDetailQty;
	}

	public void setOnlineOrderDetailQty(BigDecimal onlineOrderDetailQty) {
		this.onlineOrderDetailQty = onlineOrderDetailQty;
	}

	public String getOnlineOrderDetailOutItem() {
		return this.onlineOrderDetailOutItem;
	}

	public void setOnlineOrderDetailOutItem(String onlineOrderDetailOutItem) {
		this.onlineOrderDetailOutItem = onlineOrderDetailOutItem;
	}

	public String getOnlineOrderDetailThumbUrl() {
		return this.onlineOrderDetailThumbUrl;
	}

	public void setOnlineOrderDetailThumbUrl(String onlineOrderDetailThumbUrl) {
		this.onlineOrderDetailThumbUrl = onlineOrderDetailThumbUrl;
	}

	public String getOnlineOrderDetailPicUrl() {
		return this.onlineOrderDetailPicUrl;
	}

	public void setOnlineOrderDetailPicUrl(String onlineOrderDetailPicUrl) {
		this.onlineOrderDetailPicUrl = onlineOrderDetailPicUrl;
	}

	public BigDecimal getOnlineOrderDetailDiscountMoney() {
		if(onlineOrderDetailDiscountMoney == null){
			onlineOrderDetailDiscountMoney = BigDecimal.ZERO;
		}
		return this.onlineOrderDetailDiscountMoney;
	}

	public void setOnlineOrderDetailDiscountMoney(BigDecimal onlineOrderDetailDiscountMoney) {
		this.onlineOrderDetailDiscountMoney = onlineOrderDetailDiscountMoney;
	}

	public BigDecimal getOnlineOrderDetailTotalMoney() {
		return this.onlineOrderDetailTotalMoney;
	}

	public void setOnlineOrderDetailTotalMoney(BigDecimal onlineOrderDetailTotalMoney) {
		this.onlineOrderDetailTotalMoney = onlineOrderDetailTotalMoney;
	}

	public Integer getOnlineOrderDetailStateCode() {
		return onlineOrderDetailStateCode;
	}

	public void setOnlineOrderDetailStateCode(Integer onlineOrderDetailStateCode) {
		this.onlineOrderDetailStateCode = onlineOrderDetailStateCode;
	}

	public String getOnlineOrderDetailStateName() {
		return onlineOrderDetailStateName;
	}

	public void setOnlineOrderDetailStateName(String onlineOrderDetailStateName) {
		this.onlineOrderDetailStateName = onlineOrderDetailStateName;
	}

	public Boolean getWeixinItemTeamOnce() {
		return weixinItemTeamOnce;
	}

	public void setWeixinItemTeamOnce(Boolean weixinItemTeamOnce) {
		this.weixinItemTeamOnce = weixinItemTeamOnce;
	}

	public Integer getWeixinItemBatch() {
		return weixinItemBatch;
	}

	public void setWeixinItemBatch(Integer weixinItemBatch) {
		this.weixinItemBatch = weixinItemBatch;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OnlineOrderDetail other = (OnlineOrderDetail) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public static OnlineOrderDetail get(List<OnlineOrderDetail> onlineOrderDetails, OnlineOrderDetailId id) {
		if(onlineOrderDetails == null){
			return null;
		}
		for(int i = 0;i < onlineOrderDetails.size();i++){
			OnlineOrderDetail onlineOrderDetail = onlineOrderDetails.get(i);
			if(onlineOrderDetail.getId().equals(id)){
				return onlineOrderDetail;
			}
		}
		return null;
	}

	public static OnlineOrderDetail getByOutItem(List<OnlineOrderDetail> onlineOrderDetails, String onlineOrderDetailOutItem) {
		for(int i = 0;i < onlineOrderDetails.size();i++){
			OnlineOrderDetail onlineOrderDetail = onlineOrderDetails.get(i);
			if(StringUtils.equals(onlineOrderDetail.getOnlineOrderDetailOutItem(), onlineOrderDetailOutItem)){
				return onlineOrderDetail;
			}
		}
		return null;
	}

}
