package com.nhsoft.module.report.model;

import com.nhsoft.module.report.query.State;
import com.nhsoft.module.report.util.AppUtil;
import com.nhsoft.module.report.util.DateUtil;
import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PolicyPromotionQuantity generated by hbm2java
 */
@Entity
public class PolicyPromotionQuantity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5669776802932072290L;
	@Id
	private String promotionQuantityNo;
	private String systemBookCode;
	private Date promotionQuantityDateFrom;
	private Date promotionQuantityDateTo;
	private Date promotionQuantityTimeFrom;
	private Date promotionQuantityTimeTo;
	private String promotionQuantityAppliedBranch;
	private boolean promotionQuantityMonActived;
	private boolean promotionQuantityTuesActived;
	private boolean promotionQuantityWedActived;
	private boolean promotionQuantityThursActived;
	private boolean promotionQuantityFridayActived;
	private boolean promotionQuantitySatActived;
	private boolean promotionQuantitySunActived;
	@Embedded
	@AttributeOverrides( {
		 			@AttributeOverride(name="stateCode", column = @Column(name="promotionQuantityStateCode")), 
		@AttributeOverride(name="stateName", column = @Column(name="promotionQuantityStateName")) } )
	private State state;
	private Date promotionQuantityCreateTime;
	private String promotionQuantityCreator;
	private Date promotionQuantityAuditTime;
	private String promotionQuantityAuditor;
	private String promotionQuantityMemo;
	private Date promotionQuantityCancelTime;
	private String promotionQuantityCancelOperator;
	private Integer branchNum;
	private String promotionQuantityType;
	private Boolean promotionQuantityCardOnly;
	private String promotionQuantityCardType;
	private String promotionQuantityCategory;
	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "promotionQuantityNo", updatable=false, insertable=false)
	private List<PolicyPromotionQuantityDetail> policyPromotionQuantityDetails = new ArrayList<PolicyPromotionQuantityDetail>(0);

	public PolicyPromotionQuantity() {
	}

	public String getPromotionQuantityCategory() {
		return promotionQuantityCategory;
	}

	public void setPromotionQuantityCategory(String promotionQuantityCategory) {
		this.promotionQuantityCategory = promotionQuantityCategory;
	}

	public Boolean getPromotionQuantityCardOnly() {
		return promotionQuantityCardOnly;
	}

	public void setPromotionQuantityCardOnly(Boolean promotionQuantityCardOnly) {
		this.promotionQuantityCardOnly = promotionQuantityCardOnly;
	}

	public String getPromotionQuantityCardType() {
		return promotionQuantityCardType;
	}

	public void setPromotionQuantityCardType(String promotionQuantityCardType) {
		this.promotionQuantityCardType = promotionQuantityCardType;
	}

	public String getPromotionQuantityType() {
		return promotionQuantityType;
	}

	public void setPromotionQuantityType(String promotionQuantityType) {
		this.promotionQuantityType = promotionQuantityType;
	}

	public String getPromotionQuantityNo() {
		return this.promotionQuantityNo;
	}

	public void setPromotionQuantityNo(String promotionQuantityNo) {
		this.promotionQuantityNo = promotionQuantityNo;
	}

	public Date getPromotionQuantityDateFrom() {
		return this.promotionQuantityDateFrom;
	}

	public void setPromotionQuantityDateFrom(Date promotionQuantityDateFrom) {
		this.promotionQuantityDateFrom = promotionQuantityDateFrom;
	}

	public Date getPromotionQuantityDateTo() {
		return this.promotionQuantityDateTo;
	}

	public void setPromotionQuantityDateTo(Date promotionQuantityDateTo) {
		this.promotionQuantityDateTo = promotionQuantityDateTo;
	}

	public Date getPromotionQuantityTimeFrom() {
		return this.promotionQuantityTimeFrom;
	}

	public void setPromotionQuantityTimeFrom(Date promotionQuantityTimeFrom) {
		this.promotionQuantityTimeFrom = promotionQuantityTimeFrom;
	}

	public Date getPromotionQuantityTimeTo() {
		return this.promotionQuantityTimeTo;
	}

	public void setPromotionQuantityTimeTo(Date promotionQuantityTimeTo) {
		this.promotionQuantityTimeTo = promotionQuantityTimeTo;
	}

	public boolean isPromotionQuantityMonActived() {
		return this.promotionQuantityMonActived;
	}

	public void setPromotionQuantityMonActived(
			boolean promotionQuantityMonActived) {
		this.promotionQuantityMonActived = promotionQuantityMonActived;
	}

	public boolean isPromotionQuantityTuesActived() {
		return this.promotionQuantityTuesActived;
	}

	public void setPromotionQuantityTuesActived(
			boolean promotionQuantityTuesActived) {
		this.promotionQuantityTuesActived = promotionQuantityTuesActived;
	}

	public boolean isPromotionQuantityWedActived() {
		return this.promotionQuantityWedActived;
	}

	public void setPromotionQuantityWedActived(
			boolean promotionQuantityWedActived) {
		this.promotionQuantityWedActived = promotionQuantityWedActived;
	}

	public boolean isPromotionQuantityThursActived() {
		return this.promotionQuantityThursActived;
	}

	public void setPromotionQuantityThursActived(
			boolean promotionQuantityThursActived) {
		this.promotionQuantityThursActived = promotionQuantityThursActived;
	}

	public boolean isPromotionQuantityFridayActived() {
		return this.promotionQuantityFridayActived;
	}

	public void setPromotionQuantityFridayActived(
			boolean promotionQuantityFridayActived) {
		this.promotionQuantityFridayActived = promotionQuantityFridayActived;
	}

	public boolean isPromotionQuantitySatActived() {
		return this.promotionQuantitySatActived;
	}

	public void setPromotionQuantitySatActived(
			boolean promotionQuantitySatActived) {
		this.promotionQuantitySatActived = promotionQuantitySatActived;
	}

	public boolean isPromotionQuantitySunActived() {
		return this.promotionQuantitySunActived;
	}

	public void setPromotionQuantitySunActived(
			boolean promotionQuantitySunActived) {
		this.promotionQuantitySunActived = promotionQuantitySunActived;
	}

	public String getSystemBookCode() {
		return systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getPromotionQuantityAppliedBranch() {
		return promotionQuantityAppliedBranch;
	}

	public void setPromotionQuantityAppliedBranch(
			String promotionQuantityAppliedBranch) {
		this.promotionQuantityAppliedBranch = promotionQuantityAppliedBranch;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public Date getPromotionQuantityCreateTime() {
		return this.promotionQuantityCreateTime;
	}

	public void setPromotionQuantityCreateTime(Date promotionQuantityCreateTime) {
		this.promotionQuantityCreateTime = promotionQuantityCreateTime;
	}

	public String getPromotionQuantityCreator() {
		return this.promotionQuantityCreator;
	}

	public void setPromotionQuantityCreator(String promotionQuantityCreator) {
		this.promotionQuantityCreator = promotionQuantityCreator;
	}

	public Date getPromotionQuantityAuditTime() {
		return this.promotionQuantityAuditTime;
	}

	public void setPromotionQuantityAuditTime(Date promotionQuantityAuditTime) {
		this.promotionQuantityAuditTime = promotionQuantityAuditTime;
	}

	public String getPromotionQuantityAuditor() {
		return this.promotionQuantityAuditor;
	}

	public void setPromotionQuantityAuditor(String promotionQuantityAuditor) {
		this.promotionQuantityAuditor = promotionQuantityAuditor;
	}

	public String getPromotionQuantityMemo() {
		return this.promotionQuantityMemo;
	}

	public void setPromotionQuantityMemo(String promotionQuantityMemo) {
		this.promotionQuantityMemo = promotionQuantityMemo;
	}

	public Date getPromotionQuantityCancelTime() {
		return this.promotionQuantityCancelTime;
	}

	public void setPromotionQuantityCancelTime(Date promotionQuantityCancelTime) {
		this.promotionQuantityCancelTime = promotionQuantityCancelTime;
	}

	public String getPromotionQuantityCancelOperator() {
		return this.promotionQuantityCancelOperator;
	}

	public void setPromotionQuantityCancelOperator(
			String promotionQuantityCancelOperator) {
		this.promotionQuantityCancelOperator = promotionQuantityCancelOperator;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public List<PolicyPromotionQuantityDetail> getPolicyPromotionQuantityDetails() {
		return policyPromotionQuantityDetails;
	}

	public void setPolicyPromotionQuantityDetails(
			List<PolicyPromotionQuantityDetail> policyPromotionQuantityDetails) {
		this.policyPromotionQuantityDetails = policyPromotionQuantityDetails;
	}

	public String createNoticeText(List<PosItem> posItems){
		StringBuffer sb = new StringBuffer();
		sb.append("促销政策—超量特价");
		if(StringUtils.isNotEmpty(promotionQuantityType)){
			sb.append("(").append(promotionQuantityType).append(")");
		}
		sb.append(String.format("  单据号[%s]即将到期", promotionQuantityNo)).append(AppUtil.getSeperate());
		sb.append(String.format("促销日期:%s 至 %s 促销时间:%s 至 %s", DateUtil.getDateStr(promotionQuantityDateFrom), DateUtil.getDateStr(promotionQuantityDateTo)
				, DateUtil.getHHmmStr(promotionQuantityTimeFrom), DateUtil.getHHmmStr(promotionQuantityTimeTo))).append(AppUtil.getSeperate());
		sb.append(AppUtil.getSeperate());
		String blank = AppUtil.getString(8);
		int maxItemNameLength = 0;
		for(int i = 0;i < policyPromotionQuantityDetails.size();i++){
			PolicyPromotionQuantityDetail policyPromotionQuantityDetail = policyPromotionQuantityDetails.get(i);
			Integer itemNum = policyPromotionQuantityDetail.getItemNum();
			PosItem posItem = PosItem.get(itemNum, posItems);
			if(posItem == null){
				continue;
			}
			policyPromotionQuantityDetail.setPosItem(posItem);
			String itemName = posItem.getItemCode() + "|" + posItem.getItemName();
			int length = AppUtil.getStringWidth(itemName);
			if(length > maxItemNameLength){
				maxItemNameLength = length;
			}
		}
		sb.append("商品").append(AppUtil.getString(maxItemNameLength + 5)).append("原价").append(blank).append("特价").append(blank).append("起始数量");
		sb.append(AppUtil.getSeperate());
		for(int i = 0;i < policyPromotionQuantityDetails.size();i++){
			PolicyPromotionQuantityDetail policyPromotionQuantityDetail = policyPromotionQuantityDetails.get(i);
			if(policyPromotionQuantityDetail.getPosItem() == null){
				continue;
			}
			String item = policyPromotionQuantityDetail.getPosItem().getItemCode() + "|" + policyPromotionQuantityDetail.getPosItem().getItemName();
			sb.append(item);
			sb.append(AppUtil.getString(4 + maxItemNameLength + 5 - AppUtil.getStringWidth(item)));
			
			item = policyPromotionQuantityDetail.getPromotionQuantityDetailStdPrice().setScale(2, BigDecimal.ROUND_HALF_UP).toString();
			sb.append(item);
			sb.append(AppUtil.getString(4 + 8 - item.length()));
			
			item = policyPromotionQuantityDetail.getPromotionQuantityDetailSpecialPrice().setScale(2, BigDecimal.ROUND_HALF_UP).toString();
			sb.append(item);
			sb.append(AppUtil.getString(4 + 8 - item.length()));
			
			item = policyPromotionQuantityDetail.getPromotionQuantityDetailMinAmount().setScale(2, BigDecimal.ROUND_HALF_UP).toString();
			sb.append(item);
			sb.append(AppUtil.getSeperate());
		}
		return sb.toString();
	}
}
