package com.nhsoft.module.report.model;

import com.nhsoft.module.report.query.State;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PolicyPromotionMoney generated by hbm2java
 */
@Entity
public class PolicyPromotionMoney implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8537913384544836472L;
	@Id
	private String promotionMoneyNo;
	private String systemBookCode;
	private Date promotionMoneyDateFrom;
	private Date promotionMoneyDateTo;
	private Date promotionMoneyTimeFrom;
	private Date promotionMoneyTimeTo;
	private BigDecimal promotionMoneyBillMoney;
	private String promotionMoneyAppliedBranch;
	private boolean promotionMoneyMonActived;
	private boolean promotionMoneyTuesActived;
	private boolean promotionMoneyWedActived;
	private boolean promotionMoneyThursActived;
	private boolean promotionMoneyFridayActived;
	private boolean promotionMoneySatActived;
	private boolean promotionMoneySunActived;
	private String promotionMoneyCreator;
	private Date promotionMoneyCreateTime;
	private String promotionMoneyAuditor;
	private Date promotionMoneyAuditTime;
	@Embedded
	@AttributeOverrides( {
		 			@AttributeOverride(name="stateCode", column = @Column(name="promotionMoneyStateCode")), 
		@AttributeOverride(name="stateName", column = @Column(name="promotionMoneyStateName")) } )
	private State state;
	private String promotionMoneyMemo;
	private Date promotionMoneyCancelTime;
	private String promotionMoneyCancelOperator;
	private String promotionMoneyItems;
	private Integer branchNum;
	private Integer promotionItemCount;
	private Boolean promotionMoneyCardOnly;
	private String promotionMoneyCardType;
	private Boolean promotionMoneyAppend;
	private String promotionMoneyAssignedType;
	private String promotionMoneyAssignedCategory;
	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "promotionMoneyNo", updatable=false, insertable=false)
	private List<PolicyPromotionMoneyDetail> policyPromotionMoneyDetails = new ArrayList<PolicyPromotionMoneyDetail>();
	
	public String getPromotionMoneyAssignedType() {
		return promotionMoneyAssignedType;
	}
	
	public void setPromotionMoneyAssignedType(String promotionMoneyAssignedType) {
		this.promotionMoneyAssignedType = promotionMoneyAssignedType;
	}
	
	public String getPromotionMoneyAssignedCategory() {
		return promotionMoneyAssignedCategory;
	}
	
	public void setPromotionMoneyAssignedCategory(String promotionMoneyAssignedCategory) {
		this.promotionMoneyAssignedCategory = promotionMoneyAssignedCategory;
	}
	
	public PolicyPromotionMoney() {
	}

	public Boolean getPromotionMoneyAppend() {
		return promotionMoneyAppend;
	}

	public void setPromotionMoneyAppend(Boolean promotionMoneyAppend) {
		this.promotionMoneyAppend = promotionMoneyAppend;
	}

	public Boolean getPromotionMoneyCardOnly() {
		return promotionMoneyCardOnly;
	}

	public void setPromotionMoneyCardOnly(Boolean promotionMoneyCardOnly) {
		this.promotionMoneyCardOnly = promotionMoneyCardOnly;
	}

	public String getPromotionMoneyCardType() {
		return promotionMoneyCardType;
	}

	public void setPromotionMoneyCardType(String promotionMoneyCardType) {
		this.promotionMoneyCardType = promotionMoneyCardType;
	}

	public String getPromotionMoneyNo() {
		return this.promotionMoneyNo;
	}

	public void setPromotionMoneyNo(String promotionMoneyNo) {
		this.promotionMoneyNo = promotionMoneyNo;
	}
	
	public Date getPromotionMoneyDateFrom() {
		return this.promotionMoneyDateFrom;
	}

	public void setPromotionMoneyDateFrom(Date promotionMoneyDateFrom) {
		this.promotionMoneyDateFrom = promotionMoneyDateFrom;
	}

	public Date getPromotionMoneyDateTo() {
		return this.promotionMoneyDateTo;
	}

	public void setPromotionMoneyDateTo(Date promotionMoneyDateTo) {
		this.promotionMoneyDateTo = promotionMoneyDateTo;
	}

	public Date getPromotionMoneyTimeFrom() {
		return this.promotionMoneyTimeFrom;
	}

	public void setPromotionMoneyTimeFrom(Date promotionMoneyTimeFrom) {
		this.promotionMoneyTimeFrom = promotionMoneyTimeFrom;
	}

	public Date getPromotionMoneyTimeTo() {
		return this.promotionMoneyTimeTo;
	}

	public void setPromotionMoneyTimeTo(Date promotionMoneyTimeTo) {
		this.promotionMoneyTimeTo = promotionMoneyTimeTo;
	}

	public BigDecimal getPromotionMoneyBillMoney() {
		return this.promotionMoneyBillMoney;
	}

	public void setPromotionMoneyBillMoney(BigDecimal promotionMoneyBillMoney) {
		this.promotionMoneyBillMoney = promotionMoneyBillMoney;
	}

	public boolean isPromotionMoneyMonActived() {
		return this.promotionMoneyMonActived;
	}

	public void setPromotionMoneyMonActived(boolean promotionMoneyMonActived) {
		this.promotionMoneyMonActived = promotionMoneyMonActived;
	}

	public boolean isPromotionMoneyTuesActived() {
		return this.promotionMoneyTuesActived;
	}

	public void setPromotionMoneyTuesActived(boolean promotionMoneyTuesActived) {
		this.promotionMoneyTuesActived = promotionMoneyTuesActived;
	}

	public boolean isPromotionMoneyWedActived() {
		return this.promotionMoneyWedActived;
	}

	public void setPromotionMoneyWedActived(boolean promotionMoneyWedActived) {
		this.promotionMoneyWedActived = promotionMoneyWedActived;
	}

	public boolean isPromotionMoneyThursActived() {
		return this.promotionMoneyThursActived;
	}

	public void setPromotionMoneyThursActived(boolean promotionMoneyThursActived) {
		this.promotionMoneyThursActived = promotionMoneyThursActived;
	}

	public boolean isPromotionMoneyFridayActived() {
		return this.promotionMoneyFridayActived;
	}

	public void setPromotionMoneyFridayActived(
			boolean promotionMoneyFridayActived) {
		this.promotionMoneyFridayActived = promotionMoneyFridayActived;
	}

	public boolean isPromotionMoneySatActived() {
		return this.promotionMoneySatActived;
	}

	public void setPromotionMoneySatActived(boolean promotionMoneySatActived) {
		this.promotionMoneySatActived = promotionMoneySatActived;
	}

	public boolean isPromotionMoneySunActived() {
		return this.promotionMoneySunActived;
	}

	public void setPromotionMoneySunActived(boolean promotionMoneySunActived) {
		this.promotionMoneySunActived = promotionMoneySunActived;
	}

	public String getPromotionMoneyCreator() {
		return this.promotionMoneyCreator;
	}

	public void setPromotionMoneyCreator(String promotionMoneyCreator) {
		this.promotionMoneyCreator = promotionMoneyCreator;
	}

	public Date getPromotionMoneyCreateTime() {
		return this.promotionMoneyCreateTime;
	}

	public void setPromotionMoneyCreateTime(Date promotionMoneyCreateTime) {
		this.promotionMoneyCreateTime = promotionMoneyCreateTime;
	}

	public String getPromotionMoneyAuditor() {
		return this.promotionMoneyAuditor;
	}

	public void setPromotionMoneyAuditor(String promotionMoneyAuditor) {
		this.promotionMoneyAuditor = promotionMoneyAuditor;
	}

	public Date getPromotionMoneyAuditTime() {
		return this.promotionMoneyAuditTime;
	}

	public void setPromotionMoneyAuditTime(Date promotionMoneyAuditTime) {
		this.promotionMoneyAuditTime = promotionMoneyAuditTime;
	}

	public String getPromotionMoneyMemo() {
		return this.promotionMoneyMemo;
	}

	public void setPromotionMoneyMemo(String promotionMoneyMemo) {
		this.promotionMoneyMemo = promotionMoneyMemo;
	}

	public Date getPromotionMoneyCancelTime() {
		return this.promotionMoneyCancelTime;
	}

	public void setPromotionMoneyCancelTime(Date promotionMoneyCancelTime) {
		this.promotionMoneyCancelTime = promotionMoneyCancelTime;
	}

	public String getPromotionMoneyCancelOperator() {
		return this.promotionMoneyCancelOperator;
	}

	public void setPromotionMoneyCancelOperator(
			String promotionMoneyCancelOperator) {
		this.promotionMoneyCancelOperator = promotionMoneyCancelOperator;
	}

	public String getPromotionMoneyItems() {
		return this.promotionMoneyItems;
	}

	public void setPromotionMoneyItems(String promotionMoneyItems) {
		this.promotionMoneyItems = promotionMoneyItems;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getPromotionItemCount() {
		return this.promotionItemCount;
	}

	public void setPromotionItemCount(Integer promotionItemCount) {
		this.promotionItemCount = promotionItemCount;
	}

	public String getSystemBookCode() {
		return systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getPromotionMoneyAppliedBranch() {
		return promotionMoneyAppliedBranch;
	}

	public void setPromotionMoneyAppliedBranch(String promotionMoneyAppliedBranch) {
		this.promotionMoneyAppliedBranch = promotionMoneyAppliedBranch;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public List<PolicyPromotionMoneyDetail> getPolicyPromotionMoneyDetails() {
		return policyPromotionMoneyDetails;
	}

	public void setPolicyPromotionMoneyDetails(
			List<PolicyPromotionMoneyDetail> policyPromotionMoneyDetails) {
		this.policyPromotionMoneyDetails = policyPromotionMoneyDetails;
	}

	
}
