package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;


/**
 * PolicyPromotionDetailId generated by hbm2java
 */
@Embeddable
public class PolicyPromotionDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 758096824427379951L;
	private String policyPromotionNo;
	private Integer policyPromotionDetailNum;

	public PolicyPromotionDetailId() {
	}

	public PolicyPromotionDetailId(String policyPromotionNo,
			Integer policyPromotionDetailNum) {
		this.policyPromotionNo = policyPromotionNo;
		this.policyPromotionDetailNum = policyPromotionDetailNum;
	}

	public String getPolicyPromotionNo() {
		return this.policyPromotionNo;
	}

	public void setPolicyPromotionNo(String policyPromotionNo) {
		this.policyPromotionNo = policyPromotionNo;
	}

	public Integer getPolicyPromotionDetailNum() {
		return this.policyPromotionDetailNum;
	}

	public void setPolicyPromotionDetailNum(Integer policyPromotionDetailNum) {
		this.policyPromotionDetailNum = policyPromotionDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PolicyPromotionDetailId))
			return false;
		PolicyPromotionDetailId castOther = (PolicyPromotionDetailId) other;

		return ((this.getPolicyPromotionNo() == castOther
				.getPolicyPromotionNo()) || (this.getPolicyPromotionNo() != null
				&& castOther.getPolicyPromotionNo() != null && this
				.getPolicyPromotionNo()
				.equals(castOther.getPolicyPromotionNo())))
				&& ((this.getPolicyPromotionDetailNum() == castOther
						.getPolicyPromotionDetailNum()) || (this
						.getPolicyPromotionDetailNum() != null
						&& castOther.getPolicyPromotionDetailNum() != null && this
						.getPolicyPromotionDetailNum().equals(
								castOther.getPolicyPromotionDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPolicyPromotionNo() == null ? 0 : this
						.getPolicyPromotionNo().hashCode());
		result = 37
				* result
				+ (getPolicyPromotionDetailNum() == null ? 0 : this
						.getPolicyPromotionDetailNum().hashCode());
		return result;
	}

}
