package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;


/**
 * PolicyPresentDetailId generated by hbm2java
 */
@Embeddable
public class PolicyPresentDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1925038310902325012L;
	private String policyPresentNo;
	private Integer policyPresentDetailNum;

	public PolicyPresentDetailId() {
	}

	public PolicyPresentDetailId(String policyPresentNo,
			Integer policyPresentDetailNum) {
		this.policyPresentNo = policyPresentNo;
		this.policyPresentDetailNum = policyPresentDetailNum;
	}

	public String getPolicyPresentNo() {
		return this.policyPresentNo;
	}

	public void setPolicyPresentNo(String policyPresentNo) {
		this.policyPresentNo = policyPresentNo;
	}

	public Integer getPolicyPresentDetailNum() {
		return this.policyPresentDetailNum;
	}

	public void setPolicyPresentDetailNum(Integer policyPresentDetailNum) {
		this.policyPresentDetailNum = policyPresentDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PolicyPresentDetailId))
			return false;
		PolicyPresentDetailId castOther = (PolicyPresentDetailId) other;

		return ((this.getPolicyPresentNo() == castOther.getPolicyPresentNo()) || (this
				.getPolicyPresentNo() != null
				&& castOther.getPolicyPresentNo() != null && this
				.getPolicyPresentNo().equals(castOther.getPolicyPresentNo())))
				&& ((this.getPolicyPresentDetailNum() == castOther
						.getPolicyPresentDetailNum()) || (this
						.getPolicyPresentDetailNum() != null
						&& castOther.getPolicyPresentDetailNum() != null && this
						.getPolicyPresentDetailNum().equals(
								castOther.getPolicyPresentDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPolicyPresentNo() == null ? 0 : this.getPolicyPresentNo()
						.hashCode());
		result = 37
				* result
				+ (getPolicyPresentDetailNum() == null ? 0 : this
						.getPolicyPresentDetailNum().hashCode());
		return result;
	}

}
