package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Transient;
import java.math.BigDecimal;

/**
 * PolicyPresentDetail generated by hbm2java
 */
@Entity
public class PolicyPresentDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5481952490972232374L;
	@EmbeddedId
	private PolicyPresentDetailId id;
	private Integer itemNum;
	private BigDecimal policyPresentDetailPresentAmount;
	private String policyPresentDetailMemo;
	private Integer itemGradeNum;
	private BigDecimal policyPresentDetailPrice;

	//临时属性
	@Transient
	private PosItem posItem;
	

	public PolicyPresentDetail() {
	}
	
	public BigDecimal getPolicyPresentDetailPrice() {
		return policyPresentDetailPrice;
	}
	
	public void setPolicyPresentDetailPrice(BigDecimal policyPresentDetailPrice) {
		this.policyPresentDetailPrice = policyPresentDetailPrice;
	}
	
	public Integer getItemGradeNum() {
		return itemGradeNum;
	}

	public void setItemGradeNum(Integer itemGradeNum) {
		this.itemGradeNum = itemGradeNum;
	}

	public PosItem getPosItem() {
		return posItem;
	}

	public void setPosItem(PosItem posItem) {
		this.posItem = posItem;
	}

	public PolicyPresentDetailId getId() {
		return this.id;
	}

	public void setId(PolicyPresentDetailId id) {
		this.id = id;
	}

	public BigDecimal getPolicyPresentDetailPresentAmount() {
		return this.policyPresentDetailPresentAmount;
	}

	public void setPolicyPresentDetailPresentAmount(
			BigDecimal policyPresentDetailPresentAmount) {
		this.policyPresentDetailPresentAmount = policyPresentDetailPresentAmount;
	}

	public String getPolicyPresentDetailMemo() {
		return this.policyPresentDetailMemo;
	}

	public void setPolicyPresentDetailMemo(String policyPresentDetailMemo) {
		this.policyPresentDetailMemo = policyPresentDetailMemo;
	}

	public Integer getItemNum() {
		return itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

}
