package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Transient;
import java.math.BigDecimal;

/**
 * PolicyPromotionMoneyDetail generated by hbm2java
 */
@Entity
public class PolicyPromotionMoneyDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8990182756057640008L;
	@EmbeddedId
	private PolicyPromotionMoneyDetailId id;
	private Integer itemNum;
	private BigDecimal promotionMoneyDetailSpecialPrice;
	private BigDecimal promotionMoneyDetailAmountLimit;
	private String promotionMoneyDetailMemo;
	private Integer itemGradeNum;
	
	
	//临时属性
	@Transient
	private PosItem posItem;

	public PolicyPromotionMoneyDetail() {
	}

	public Integer getItemGradeNum() {
		return itemGradeNum;
	}

	public void setItemGradeNum(Integer itemGradeNum) {
		this.itemGradeNum = itemGradeNum;
	}

	public PolicyPromotionMoneyDetailId getId() {
		return this.id;
	}

	public void setId(PolicyPromotionMoneyDetailId id) {
		this.id = id;
	}

	public BigDecimal getPromotionMoneyDetailSpecialPrice() {
		return this.promotionMoneyDetailSpecialPrice;
	}

	public void setPromotionMoneyDetailSpecialPrice(
			BigDecimal promotionMoneyDetailSpecialPrice) {
		this.promotionMoneyDetailSpecialPrice = promotionMoneyDetailSpecialPrice;
	}

	public BigDecimal getPromotionMoneyDetailAmountLimit() {
		return this.promotionMoneyDetailAmountLimit;
	}

	public void setPromotionMoneyDetailAmountLimit(
			BigDecimal promotionMoneyDetailAmountLimit) {
		this.promotionMoneyDetailAmountLimit = promotionMoneyDetailAmountLimit;
	}

	public String getPromotionMoneyDetailMemo() {
		return this.promotionMoneyDetailMemo;
	}

	public void setPromotionMoneyDetailMemo(String promotionMoneyDetailMemo) {
		this.promotionMoneyDetailMemo = promotionMoneyDetailMemo;
	}

	public Integer getItemNum() {
		return itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public PosItem getPosItem() {
		return posItem;
	}

	public void setPosItem(PosItem posItem) {
		this.posItem = posItem;
	}

}
