package com.nhsoft.module.report.model;


import com.nhsoft.module.report.query.State;
import com.nhsoft.module.report.util.AppUtil;
import com.nhsoft.report.utils.DateUtil;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PolicyPresent generated by hbm2java
 */
@Entity
public class PolicyPresent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4906164400225477148L;
	@Id
	private String policyPresentNo;
	private Integer itemNum;
	private String systemBookCode;
	private Date policyPresentDateFrom;
	private Date policyPresentDateTo;
	private Date policyPresentTimeFrom;
	private Date policyPresentTimeTo;
	private String policyPresentAppliedBranch;
	private boolean policyPresentMonActived;
	private boolean policyPresentTuesActived;
	private boolean policyPresentWedActived;
	private boolean policyPresentThursActived;
	private boolean policyPresentFridayActived;
	private boolean policyPresentSatActived;
	private boolean policyPresentSunActived;
	private String policyPresentCreator;
	private Date policyPresentCreateTime;
	private String policyPresentAuditor;
	private Date policyPresentAuditTime;
	@Embedded
	@AttributeOverrides( {
		 			@AttributeOverride(name="stateCode", column = @Column(name="policyPresentStateCode")), 
		@AttributeOverride(name="stateName", column = @Column(name="policyPresentStateName")) } )
	private State state;
	private String policyPresentMemo;
	private BigDecimal policyPresentSaleAmount;
	private Date policyPresentCancelTime;
	private String policyPresentCancelOperator;
	private Integer branchNum;
	private Integer policyPresentItemCount;
	private Boolean policyPresentCardOnly;
	private String policyPresentCardType;
	private Integer itemGradeNum;

	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "policyPresentNo", updatable=false, insertable=false)
	private List<PolicyPresentDetail> policyPresentDetails = new ArrayList<PolicyPresentDetail>(0);

	public PolicyPresent() {
	}

	public Integer getItemGradeNum() {
		return itemGradeNum;
	}

	public void setItemGradeNum(Integer itemGradeNum) {
		this.itemGradeNum = itemGradeNum;
	}

	public Boolean getPolicyPresentCardOnly() {
		return policyPresentCardOnly;
	}

	public void setPolicyPresentCardOnly(Boolean policyPresentCardOnly) {
		this.policyPresentCardOnly = policyPresentCardOnly;
	}

	public String getPolicyPresentCardType() {
		return policyPresentCardType;
	}

	public void setPolicyPresentCardType(String policyPresentCardType) {
		this.policyPresentCardType = policyPresentCardType;
	}

	public String getPolicyPresentNo() {
		return this.policyPresentNo;
	}

	public void setPolicyPresentNo(String policyPresentNo) {
		this.policyPresentNo = policyPresentNo;
	}
	
	public Date getPolicyPresentDateFrom() {
		return this.policyPresentDateFrom;
	}

	public void setPolicyPresentDateFrom(Date policyPresentDateFrom) {
		this.policyPresentDateFrom = policyPresentDateFrom;
	}

	public Date getPolicyPresentDateTo() {
		return this.policyPresentDateTo;
	}

	public void setPolicyPresentDateTo(Date policyPresentDateTo) {
		this.policyPresentDateTo = policyPresentDateTo;
	}

	public Date getPolicyPresentTimeFrom() {
		return this.policyPresentTimeFrom;
	}

	public void setPolicyPresentTimeFrom(Date policyPresentTimeFrom) {
		this.policyPresentTimeFrom = policyPresentTimeFrom;
	}

	public Date getPolicyPresentTimeTo() {
		return this.policyPresentTimeTo;
	}

	public void setPolicyPresentTimeTo(Date policyPresentTimeTo) {
		this.policyPresentTimeTo = policyPresentTimeTo;
	}

	public String getPolicyPresentAppliedBranch() {
		return policyPresentAppliedBranch;
	}

	public void setPolicyPresentAppliedBranch(String policyPresentAppliedBranch) {
		this.policyPresentAppliedBranch = policyPresentAppliedBranch;
	}

	public boolean isPolicyPresentMonActived() {
		return this.policyPresentMonActived;
	}

	public void setPolicyPresentMonActived(boolean policyPresentMonActived) {
		this.policyPresentMonActived = policyPresentMonActived;
	}

	public boolean isPolicyPresentTuesActived() {
		return this.policyPresentTuesActived;
	}

	public void setPolicyPresentTuesActived(boolean policyPresentTuesActived) {
		this.policyPresentTuesActived = policyPresentTuesActived;
	}

	public boolean isPolicyPresentWedActived() {
		return this.policyPresentWedActived;
	}

	public void setPolicyPresentWedActived(boolean policyPresentWedActived) {
		this.policyPresentWedActived = policyPresentWedActived;
	}

	public boolean isPolicyPresentThursActived() {
		return this.policyPresentThursActived;
	}

	public void setPolicyPresentThursActived(boolean policyPresentThursActived) {
		this.policyPresentThursActived = policyPresentThursActived;
	}

	public boolean isPolicyPresentFridayActived() {
		return this.policyPresentFridayActived;
	}

	public void setPolicyPresentFridayActived(boolean policyPresentFridayActived) {
		this.policyPresentFridayActived = policyPresentFridayActived;
	}

	public boolean isPolicyPresentSatActived() {
		return this.policyPresentSatActived;
	}

	public void setPolicyPresentSatActived(boolean policyPresentSatActived) {
		this.policyPresentSatActived = policyPresentSatActived;
	}

	public boolean isPolicyPresentSunActived() {
		return this.policyPresentSunActived;
	}

	public void setPolicyPresentSunActived(boolean policyPresentSunActived) {
		this.policyPresentSunActived = policyPresentSunActived;
	}

	public String getPolicyPresentCreator() {
		return this.policyPresentCreator;
	}

	public void setPolicyPresentCreator(String policyPresentCreator) {
		this.policyPresentCreator = policyPresentCreator;
	}

	public Date getPolicyPresentCreateTime() {
		return this.policyPresentCreateTime;
	}

	public void setPolicyPresentCreateTime(Date policyPresentCreateTime) {
		this.policyPresentCreateTime = policyPresentCreateTime;
	}

	public String getPolicyPresentAuditor() {
		return this.policyPresentAuditor;
	}

	public void setPolicyPresentAuditor(String policyPresentAuditor) {
		this.policyPresentAuditor = policyPresentAuditor;
	}

	public Date getPolicyPresentAuditTime() {
		return this.policyPresentAuditTime;
	}

	public void setPolicyPresentAuditTime(Date policyPresentAuditTime) {
		this.policyPresentAuditTime = policyPresentAuditTime;
	}


	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getPolicyPresentMemo() {
		return this.policyPresentMemo;
	}

	public void setPolicyPresentMemo(String policyPresentMemo) {
		this.policyPresentMemo = policyPresentMemo;
	}

	public BigDecimal getPolicyPresentSaleAmount() {
		return this.policyPresentSaleAmount;
	}

	public void setPolicyPresentSaleAmount(BigDecimal policyPresentSaleAmount) {
		this.policyPresentSaleAmount = policyPresentSaleAmount;
	}

	public Date getPolicyPresentCancelTime() {
		return this.policyPresentCancelTime;
	}

	public void setPolicyPresentCancelTime(Date policyPresentCancelTime) {
		this.policyPresentCancelTime = policyPresentCancelTime;
	}

	public String getPolicyPresentCancelOperator() {
		return this.policyPresentCancelOperator;
	}

	public void setPolicyPresentCancelOperator(
			String policyPresentCancelOperator) {
		this.policyPresentCancelOperator = policyPresentCancelOperator;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getPolicyPresentItemCount() {
		return this.policyPresentItemCount;
	}

	public void setPolicyPresentItemCount(Integer policyPresentItemCount) {
		this.policyPresentItemCount = policyPresentItemCount;
	}

	public String getSystemBookCode() {
		return systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public List<PolicyPresentDetail> getPolicyPresentDetails() {
		return policyPresentDetails;
	}

	public void setPolicyPresentDetails(
			List<PolicyPresentDetail> policyPresentDetails) {
		this.policyPresentDetails = policyPresentDetails;
	}

	public Integer getItemNum() {
		return itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String createNoticeText(List<PosItem> posItems){
		StringBuffer sb = new StringBuffer();
		sb.append("促销政策—赠送促销");
		
		PosItem posItem = PosItem.get(itemNum, posItems);
		if(posItem != null){
			sb.append("(").append(String.format("促销商品[%s], 购买数量%s", posItem.getItemCode() + "|" + posItem.getItemName(), 
					policyPresentSaleAmount.setScale(2, BigDecimal.ROUND_HALF_UP).toString())).append(")");
		}
		
		sb.append(String.format("  单据号[%s]即将到期", policyPresentNo)).append(AppUtil.getSeperate());
		sb.append(String.format("促销日期:%s 至 %s 促销时间:%s 至 %s", DateUtil.getDateStr(policyPresentDateFrom), DateUtil.getDateStr(policyPresentDateTo)
				, DateUtil.getHHmmStr(policyPresentTimeFrom), DateUtil.getHHmmStr(policyPresentTimeTo))).append(AppUtil.getSeperate());
		sb.append(AppUtil.getSeperate());
		int maxItemNameLength = 0;
		for(int i = 0;i < policyPresentDetails.size();i++){
			PolicyPresentDetail policyPresentDetail = policyPresentDetails.get(i);
			Integer itemNum = policyPresentDetail.getItemNum();
			posItem = PosItem.get(itemNum, posItems);
			if(posItem == null){
				continue;
			}
			policyPresentDetail.setPosItem(posItem);
			String itemName = posItem.getItemCode() + "|" + posItem.getItemName();
			int length = AppUtil.getStringWidth(itemName);
			if(length > maxItemNameLength){
				maxItemNameLength = length;
			}
		}
		sb.append("赠送商品").append(AppUtil.getString(maxItemNameLength + 5)).append("赠送数量");
		sb.append(AppUtil.getSeperate());
		for(int i = 0;i < policyPresentDetails.size();i++){
			PolicyPresentDetail policyPresentDetail = policyPresentDetails.get(i);
			if(policyPresentDetail.getPosItem() == null){
				continue;
			}
			String item = policyPresentDetail.getPosItem().getItemCode() + "|" + policyPresentDetail.getPosItem().getItemName();
			sb.append(item);
			sb.append(AppUtil.getString(8 + maxItemNameLength + 5 - AppUtil.getStringWidth(item)));
			
			item = policyPresentDetail.getPolicyPresentDetailPresentAmount().setScale(2, BigDecimal.ROUND_HALF_UP).toString();
			sb.append(item);
			sb.append(AppUtil.getSeperate());
		}
		return sb.toString();
	}
}
