package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;

/**
 * PosItemAreaId generated by hbm2java
 */
@Embeddable
public class PosItemAreaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2875951758522050471L;
	private Integer itemNum;
	private Integer posItemAreaNum;

	public PosItemAreaId() {
	}

	public PosItemAreaId(Integer itemNum, Integer posItemAreaNum) {
		this.itemNum = itemNum;
		this.posItemAreaNum = posItemAreaNum;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public Integer getPosItemAreaNum() {
		return this.posItemAreaNum;
	}

	public void setPosItemAreaNum(Integer posItemAreaNum) {
		this.posItemAreaNum = posItemAreaNum;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemNum == null) ? 0 : itemNum.hashCode());
		result = prime * result + ((posItemAreaNum == null) ? 0 : posItemAreaNum.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PosItemAreaId other = (PosItemAreaId) obj;
		if (itemNum == null) {
			if (other.itemNum != null)
				return false;
		} else if (!itemNum.equals(other.itemNum))
			return false;
		if (posItemAreaNum == null) {
			if (other.posItemAreaNum != null)
				return false;
		} else if (!posItemAreaNum.equals(other.posItemAreaNum))
			return false;
		return true;
	}


}
