package com.nhsoft.module.report.model;



import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PosItemGrade generated by hbm2java
 */
public class PosItemGrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2107521376416827926L;
	private Integer itemGradeNum;
	private Integer itemNum;
	private String systemBookCode;
	private String itemGradeCode;
	private String itemGradeBarcode;
	private String itemGradeName;
	private Date itemGradeEditTime;
	private Integer itemGradeType;
	private Boolean itemGradeDiscounted;
	private BigDecimal itemGradeRegularPrice;
	private BigDecimal itemGradeLevel2Price;
	private BigDecimal itemGradeLevel3Price;
	private BigDecimal itemGradeLevel4Price;
	private String itemGradePinyin;

	public PosItemGrade() {
	}

	public String getItemGradePinyin() {
		return itemGradePinyin;
	}

	public void setItemGradePinyin(String itemGradePinyin) {
		this.itemGradePinyin = itemGradePinyin;
	}

	public BigDecimal getItemGradeRegularPrice() {
		return itemGradeRegularPrice;
	}

	public void setItemGradeRegularPrice(BigDecimal itemGradeRegularPrice) {
		this.itemGradeRegularPrice = itemGradeRegularPrice;
	}

	public BigDecimal getItemGradeLevel2Price() {
		return itemGradeLevel2Price;
	}

	public void setItemGradeLevel2Price(BigDecimal itemGradeLevel2Price) {
		this.itemGradeLevel2Price = itemGradeLevel2Price;
	}

	public BigDecimal getItemGradeLevel3Price() {
		return itemGradeLevel3Price;
	}

	public void setItemGradeLevel3Price(BigDecimal itemGradeLevel3Price) {
		this.itemGradeLevel3Price = itemGradeLevel3Price;
	}

	public BigDecimal getItemGradeLevel4Price() {
		return itemGradeLevel4Price;
	}

	public void setItemGradeLevel4Price(BigDecimal itemGradeLevel4Price) {
		this.itemGradeLevel4Price = itemGradeLevel4Price;
	}

	public Integer getItemGradeNum() {
		return this.itemGradeNum;
	}

	public void setItemGradeNum(Integer itemGradeNum) {
		this.itemGradeNum = itemGradeNum;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getItemGradeCode() {
		return this.itemGradeCode;
	}

	public void setItemGradeCode(String itemGradeCode) {
		this.itemGradeCode = itemGradeCode;
	}

	public String getItemGradeBarcode() {
		return this.itemGradeBarcode;
	}

	public void setItemGradeBarcode(String itemGradeBarcode) {
		this.itemGradeBarcode = itemGradeBarcode;
	}

	public String getItemGradeName() {
		return this.itemGradeName;
	}

	public void setItemGradeName(String itemGradeName) {
		this.itemGradeName = itemGradeName;
	}

	public Date getItemGradeEditTime() {
		return this.itemGradeEditTime;
	}

	public void setItemGradeEditTime(Date itemGradeEditTime) {
		this.itemGradeEditTime = itemGradeEditTime;
	}

	public Integer getItemGradeType() {
		return this.itemGradeType;
	}

	public void setItemGradeType(Integer itemGradeType) {
		this.itemGradeType = itemGradeType;
	}

	public Boolean getItemGradeDiscounted() {
		return itemGradeDiscounted;
	}

	public void setItemGradeDiscounted(Boolean itemGradeDiscounted) {
		this.itemGradeDiscounted = itemGradeDiscounted;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemGradeNum == null) ? 0 : itemGradeNum.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PosItemGrade other = (PosItemGrade) obj;
		if (itemGradeNum == null) {
			if (other.itemGradeNum != null)
				return false;
		} else if (!itemGradeNum.equals(other.itemGradeNum))
			return false;
		return true;
	}

	public static List<PosItemGrade> find(List<PosItemGrade> posItemGrades, Integer itemNum) {
		List<PosItemGrade> list = new ArrayList<PosItemGrade>();
		for(int i = 0;i < posItemGrades.size();i++){
			PosItemGrade posItemGrade = posItemGrades.get(i);
			if(posItemGrade.getItemNum().equals(itemNum)){
				list.add(posItemGrade);
			}
		}
		return list;
	}

	public static PosItemGrade get(List<PosItemGrade> posItemGrades, Integer itemNum, Integer itemGradeType) {
		for(int i = 0;i < posItemGrades.size();i++){
			PosItemGrade posItemGrade = posItemGrades.get(i);
			if(posItemGrade.getItemNum().equals(itemNum) 
					&& posItemGrade.getItemGradeType().equals(itemGradeType)){
							
				return posItemGrade;
			}
		}
		return null;
	}
	
	public static PosItemGrade get(List<PosItemGrade> posItemGrades, Integer itemGradeNum) {
		for(int i = 0;i < posItemGrades.size();i++){
			PosItemGrade posItemGrade = posItemGrades.get(i);
			if(posItemGrade.getItemGradeNum().equals(itemGradeNum)) {
				return posItemGrade;
			}
		}
		return null;
	}

}
