package com.nhsoft.module.report.model;


import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PosItemFlag generated by hbm2java
 */
@Entity
public class PosItemFlag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1221165673978232412L;
	@Id
	private int itemFlagNum;
	private String systemBookCode;
	private String itemFlagName;
	private String itemFlagType;
	private Date itemFlagStartTime;
	private Date itemFlagEndTime;

	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "itemFlagNum", updatable=false, insertable=false)
	private List<ItemFlagDetail> itemFlagDetails = new ArrayList<ItemFlagDetail>(0);

	public PosItemFlag() {
	}

	public String getItemFlagType() {
		return itemFlagType;
	}

	public void setItemFlagType(String itemFlagType) {
		this.itemFlagType = itemFlagType;
	}

	public Date getItemFlagStartTime() {
		return itemFlagStartTime;
	}

	public void setItemFlagStartTime(Date itemFlagStartTime) {
		this.itemFlagStartTime = itemFlagStartTime;
	}

	public Date getItemFlagEndTime() {
		return itemFlagEndTime;
	}

	public void setItemFlagEndTime(Date itemFlagEndTime) {
		this.itemFlagEndTime = itemFlagEndTime;
	}

	public int getItemFlagNum() {
		return this.itemFlagNum;
	}

	public void setItemFlagNum(int itemFlagNum) {
		this.itemFlagNum = itemFlagNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getItemFlagName() {
		return this.itemFlagName;
	}

	public void setItemFlagName(String itemFlagName) {
		this.itemFlagName = itemFlagName;
	}

	public List<ItemFlagDetail> getItemFlagDetails() {
		return itemFlagDetails;
	}

	public void setItemFlagDetails(List<ItemFlagDetail> itemFlagDetails) {
		this.itemFlagDetails = itemFlagDetails;
	}

}
