package com.nhsoft.module.report.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Transient;
import java.util.ArrayList;
import java.util.List;


/**
 * PosItemDetail generated by hbm2java
 */
@Entity
public class PosItemDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4138219923010609575L;
	@Id
	private Integer itemNum;
	private String systemBookCode;
	private String itemDetailContext;
	
	//关联图片ID 供应商新品申请用到
	@Transient
	private List<String> systemImageIds = new ArrayList<String>();

	public PosItemDetail() {
	}

	public PosItemDetail(Integer itemNum, String systemBookCode) {
		this.itemNum = itemNum;
		this.systemBookCode = systemBookCode;
	}

	public PosItemDetail(Integer itemNum, String systemBookCode,
			String itemDetailContext) {
		this.itemNum = itemNum;
		this.systemBookCode = systemBookCode;
		this.itemDetailContext = itemDetailContext;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getItemDetailContext() {
		return this.itemDetailContext;
	}

	public void setItemDetailContext(String itemDetailContext) {
		this.itemDetailContext = itemDetailContext;
	}

	public List<String> getSystemImageIds() {
		return systemImageIds;
	}

	public void setSystemImageIds(List<String> systemImageIds) {
		this.systemImageIds = systemImageIds;
	}

}
