package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;


/**
 * PosOrderDetailId generated by hbm2java
 */
@Embeddable
public class PosOrderDetailId implements java.io.Serializable {

	private static final long serialVersionUID = 3355956852426062662L;
	private String orderNo;
	private Integer orderDetailNum;

	public PosOrderDetailId() {
	}
	
	public PosOrderDetailId(String orderNo, Integer orderDetailNum) {
		this.orderNo = orderNo;
		this.orderDetailNum = orderDetailNum;
	}

	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Integer getOrderDetailNum() {
		return this.orderDetailNum;
	}

	public void setOrderDetailNum(Integer orderDetailNum) {
		this.orderDetailNum = orderDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PosOrderDetailId))
			return false;
		PosOrderDetailId castOther = (PosOrderDetailId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this
				.getOrderNo() != null && castOther.getOrderNo() != null && this
				.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getOrderDetailNum() == castOther.getOrderDetailNum()) || (this
						.getOrderDetailNum() != null
						&& castOther.getOrderDetailNum() != null && this
						.getOrderDetailNum().equals(
								castOther.getOrderDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37
				* result
				+ (getOrderDetailNum() == null ? 0 : this.getOrderDetailNum()
						.hashCode());
		return result;
	}

}
