package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.math.BigDecimal;

/**
 * PreSettlementDetail generated by hbm2java
 */
@Entity
public class PreSettlementDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2847558448812522570L;
	@EmbeddedId
	private PreSettlementDetailId id;
	@ManyToOne
	@JoinColumn(name="preSettlementNo", insertable=false, updatable=false)
	private PreSettlement preSettlement;
	private BigDecimal preSettlementDetailMoney;

	public PreSettlementDetail() {
	}

	public PreSettlementDetailId getId() {
		return this.id;
	}

	public void setId(PreSettlementDetailId id) {
		this.id = id;
	}

	public PreSettlement getPreSettlement() {
		return this.preSettlement;
	}

	public void setPreSettlement(PreSettlement preSettlement) {
		this.preSettlement = preSettlement;
	}

	public BigDecimal getPreSettlementDetailMoney() {
		return this.preSettlementDetailMoney;
	}

	public void setPreSettlementDetailMoney(BigDecimal preSettlementDetailMoney) {
		this.preSettlementDetailMoney = preSettlementDetailMoney;
	}

}
