package com.nhsoft.module.report.model;



/**
 * PreSettlementDetailId generated by hbm2java
 */
public class PreSettlementDetailId implements java.io.Serializable {

	private static final long serialVersionUID = 1794375051117392552L;
	private String preSettlementNo;
	private String settlementNo;

	public PreSettlementDetailId(String preSettlementNo, String settlementNo) {
		this.preSettlementNo = preSettlementNo;
		this.settlementNo = settlementNo;
	}
	
	public PreSettlementDetailId(){
		
	}

	public String getPreSettlementNo() {
		return this.preSettlementNo;
	}

	public void setPreSettlementNo(String preSettlementNo) {
		this.preSettlementNo = preSettlementNo;
	}

	public String getSettlementNo() {
		return this.settlementNo;
	}

	public void setSettlementNo(String settlementNo) {
		this.settlementNo = settlementNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((preSettlementNo == null) ? 0 : preSettlementNo.hashCode());
		result = prime * result + ((settlementNo == null) ? 0 : settlementNo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PreSettlementDetailId other = (PreSettlementDetailId) obj;
		if (preSettlementNo == null) {
			if (other.preSettlementNo != null)
				return false;
		} else if (!preSettlementNo.equals(other.preSettlementNo))
			return false;
		if (settlementNo == null) {
			if (other.settlementNo != null)
				return false;
		} else if (!settlementNo.equals(other.settlementNo))
			return false;
		return true;
	}


}
