package com.nhsoft.module.report.model;


import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * PurchaseOrderDetail generated by hbm2java
 */
@Entity
public class PurchaseOrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 503349864720206066L;
	@EmbeddedId
	private PurchaseOrderDetailId id;
	private Integer itemNum;
	private String purchaseOrderDetailItemCode;
	private String purchaseOrderDetailItemName;
	private BigDecimal purchaseOrderDetailOnhand;
	private BigDecimal purchaseOrderDetailOnorderAmount;
	private BigDecimal purchaseOrderDetailCost;
	private BigDecimal purchaseOrderDetailQty;
	private BigDecimal purchaseOrderDetailMoney;
	private BigDecimal purchaseOrderDetailRecievedAmount;
	private BigDecimal purchaseOrderDetailRecievedMoney;
	private BigDecimal purchaseOrderDetailCustOrderAmount;
	private Integer purchaseOrderDetailPostItemMatrixNum;
	private BigDecimal purchaseOrderDetailPresentQty;
	private String purchaseOrderDetailMemo;
	private BigDecimal purchaseOrderDetailRecievedPresentAmount;
	private String purchaseOrderDetailItemUnit;
	private String purchaseOrderDetailUseUnit;
	private BigDecimal purchaseOrderDetailUseQty;
	private BigDecimal purchaseOrderDetailUsePrice;
	private BigDecimal purchaseOrderDetailUseRate;
	private String purchaseOrderDetailAssistUnit;
	private BigDecimal purchaseOrderDetailAssistQty;
	private String purchaseOrderDetailItemSpec;
	private String purchaseOrderDetailPeriod;
	private BigDecimal purchaseOrderDetailLastPrice;
	private String purchaseOrderDetailPresentUnit;
	private BigDecimal purchaseOrderDetailPresentUseQty;
	private BigDecimal purchaseOrderDetailStdPrice;

	public PurchaseOrderDetail() {
	}

	public BigDecimal getPurchaseOrderDetailStdPrice() {
		return purchaseOrderDetailStdPrice;
	}

	public void setPurchaseOrderDetailStdPrice(BigDecimal purchaseOrderDetailStdPrice) {
		this.purchaseOrderDetailStdPrice = purchaseOrderDetailStdPrice;
	}

	public BigDecimal getPurchaseOrderDetailPresentUseQty() {
		return purchaseOrderDetailPresentUseQty;
	}

	public void setPurchaseOrderDetailPresentUseQty(BigDecimal purchaseOrderDetailPresentUseQty) {
		this.purchaseOrderDetailPresentUseQty = purchaseOrderDetailPresentUseQty;
	}

	public String getPurchaseOrderDetailPresentUnit() {
		return purchaseOrderDetailPresentUnit;
	}

	public void setPurchaseOrderDetailPresentUnit(String purchaseOrderDetailPresentUnit) {
		this.purchaseOrderDetailPresentUnit = purchaseOrderDetailPresentUnit;
	}

	public PurchaseOrderDetailId getId() {
		return this.id;
	}

	public void setId(PurchaseOrderDetailId id) {
		this.id = id;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getPurchaseOrderDetailItemCode() {
		return this.purchaseOrderDetailItemCode;
	}

	public void setPurchaseOrderDetailItemCode(
			String purchaseOrderDetailItemCode) {
		this.purchaseOrderDetailItemCode = purchaseOrderDetailItemCode;
	}

	public String getPurchaseOrderDetailItemName() {
		return this.purchaseOrderDetailItemName;
	}

	public void setPurchaseOrderDetailItemName(
			String purchaseOrderDetailItemName) {
		this.purchaseOrderDetailItemName = purchaseOrderDetailItemName;
	}

	public BigDecimal getPurchaseOrderDetailOnhand() {
		return this.purchaseOrderDetailOnhand;
	}

	public void setPurchaseOrderDetailOnhand(
			BigDecimal purchaseOrderDetailOnhand) {
		this.purchaseOrderDetailOnhand = purchaseOrderDetailOnhand;
	}

	public BigDecimal getPurchaseOrderDetailOnorderAmount() {
		return this.purchaseOrderDetailOnorderAmount;
	}

	public void setPurchaseOrderDetailOnorderAmount(
			BigDecimal purchaseOrderDetailOnorderAmount) {
		this.purchaseOrderDetailOnorderAmount = purchaseOrderDetailOnorderAmount;
	}

	public BigDecimal getPurchaseOrderDetailCost() {
		return this.purchaseOrderDetailCost;
	}

	public void setPurchaseOrderDetailCost(BigDecimal purchaseOrderDetailCost) {
		this.purchaseOrderDetailCost = purchaseOrderDetailCost;
	}

	public BigDecimal getPurchaseOrderDetailQty() {
		return this.purchaseOrderDetailQty;
	}

	public void setPurchaseOrderDetailQty(BigDecimal purchaseOrderDetailQty) {
		this.purchaseOrderDetailQty = purchaseOrderDetailQty;
	}

	public BigDecimal getPurchaseOrderDetailMoney() {
		return this.purchaseOrderDetailMoney;
	}

	public void setPurchaseOrderDetailMoney(BigDecimal purchaseOrderDetailMoney) {
		this.purchaseOrderDetailMoney = purchaseOrderDetailMoney;
	}

	public BigDecimal getPurchaseOrderDetailRecievedAmount() {
		return this.purchaseOrderDetailRecievedAmount;
	}

	public void setPurchaseOrderDetailRecievedAmount(
			BigDecimal purchaseOrderDetailRecievedAmount) {
		this.purchaseOrderDetailRecievedAmount = purchaseOrderDetailRecievedAmount;
	}

	public BigDecimal getPurchaseOrderDetailRecievedMoney() {
		return this.purchaseOrderDetailRecievedMoney;
	}

	public void setPurchaseOrderDetailRecievedMoney(
			BigDecimal purchaseOrderDetailRecievedMoney) {
		this.purchaseOrderDetailRecievedMoney = purchaseOrderDetailRecievedMoney;
	}

	public BigDecimal getPurchaseOrderDetailCustOrderAmount() {
		return this.purchaseOrderDetailCustOrderAmount;
	}

	public void setPurchaseOrderDetailCustOrderAmount(
			BigDecimal purchaseOrderDetailCustOrderAmount) {
		this.purchaseOrderDetailCustOrderAmount = purchaseOrderDetailCustOrderAmount;
	}

	public Integer getPurchaseOrderDetailPostItemMatrixNum() {
		return this.purchaseOrderDetailPostItemMatrixNum;
	}

	public void setPurchaseOrderDetailPostItemMatrixNum(
			Integer purchaseOrderDetailPostItemMatrixNum) {
		this.purchaseOrderDetailPostItemMatrixNum = purchaseOrderDetailPostItemMatrixNum;
	}

	public BigDecimal getPurchaseOrderDetailPresentQty() {
		return this.purchaseOrderDetailPresentQty;
	}

	public void setPurchaseOrderDetailPresentQty(
			BigDecimal purchaseOrderDetailPresentQty) {
		this.purchaseOrderDetailPresentQty = purchaseOrderDetailPresentQty;
	}

	public String getPurchaseOrderDetailMemo() {
		return this.purchaseOrderDetailMemo;
	}

	public void setPurchaseOrderDetailMemo(String purchaseOrderDetailMemo) {
		this.purchaseOrderDetailMemo = purchaseOrderDetailMemo;
	}

	public BigDecimal getPurchaseOrderDetailRecievedPresentAmount() {
		return this.purchaseOrderDetailRecievedPresentAmount;
	}

	public void setPurchaseOrderDetailRecievedPresentAmount(
			BigDecimal purchaseOrderDetailRecievedPresentAmount) {
		this.purchaseOrderDetailRecievedPresentAmount = purchaseOrderDetailRecievedPresentAmount;
	}

	public String getPurchaseOrderDetailItemUnit() {
		return this.purchaseOrderDetailItemUnit;
	}

	public void setPurchaseOrderDetailItemUnit(
			String purchaseOrderDetailItemUnit) {
		this.purchaseOrderDetailItemUnit = purchaseOrderDetailItemUnit;
	}

	public String getPurchaseOrderDetailUseUnit() {
		return this.purchaseOrderDetailUseUnit;
	}

	public void setPurchaseOrderDetailUseUnit(String purchaseOrderDetailUseUnit) {
		this.purchaseOrderDetailUseUnit = purchaseOrderDetailUseUnit;
	}

	public BigDecimal getPurchaseOrderDetailUseQty() {
		return this.purchaseOrderDetailUseQty;
	}

	public void setPurchaseOrderDetailUseQty(
			BigDecimal purchaseOrderDetailUseQty) {
		this.purchaseOrderDetailUseQty = purchaseOrderDetailUseQty;
	}

	public BigDecimal getPurchaseOrderDetailUsePrice() {
		return this.purchaseOrderDetailUsePrice;
	}

	public void setPurchaseOrderDetailUsePrice(
			BigDecimal purchaseOrderDetailUsePrice) {
		this.purchaseOrderDetailUsePrice = purchaseOrderDetailUsePrice;
	}

	public BigDecimal getPurchaseOrderDetailUseRate() {
		return this.purchaseOrderDetailUseRate;
	}

	public void setPurchaseOrderDetailUseRate(
			BigDecimal purchaseOrderDetailUseRate) {
		this.purchaseOrderDetailUseRate = purchaseOrderDetailUseRate;
	}

	public String getPurchaseOrderDetailAssistUnit() {
		return this.purchaseOrderDetailAssistUnit;
	}

	public void setPurchaseOrderDetailAssistUnit(
			String purchaseOrderDetailAssistUnit) {
		this.purchaseOrderDetailAssistUnit = purchaseOrderDetailAssistUnit;
	}

	public BigDecimal getPurchaseOrderDetailAssistQty() {
		return this.purchaseOrderDetailAssistQty;
	}

	public void setPurchaseOrderDetailAssistQty(
			BigDecimal purchaseOrderDetailAssistQty) {
		this.purchaseOrderDetailAssistQty = purchaseOrderDetailAssistQty;
	}

	public String getPurchaseOrderDetailItemSpec() {
		return this.purchaseOrderDetailItemSpec;
	}

	public void setPurchaseOrderDetailItemSpec(
			String purchaseOrderDetailItemSpec) {
		this.purchaseOrderDetailItemSpec = purchaseOrderDetailItemSpec;
	}

	public String getPurchaseOrderDetailPeriod() {
		return this.purchaseOrderDetailPeriod;
	}

	public void setPurchaseOrderDetailPeriod(String purchaseOrderDetailPeriod) {
		this.purchaseOrderDetailPeriod = purchaseOrderDetailPeriod;
	}

	public BigDecimal getPurchaseOrderDetailLastPrice() {
		return purchaseOrderDetailLastPrice;
	}

	public void setPurchaseOrderDetailLastPrice(
			BigDecimal purchaseOrderDetailLastPrice) {
		this.purchaseOrderDetailLastPrice = purchaseOrderDetailLastPrice;
	}

	public static List<PurchaseOrderDetail> findDetails(List<PurchaseOrderDetail> purchaseOrderDetails,
			String purchaseOrderFid) {
		List<PurchaseOrderDetail> list= new ArrayList<PurchaseOrderDetail>();
		for(int i = 0;i < purchaseOrderDetails.size();i++){
			PurchaseOrderDetail purchaseOrderDetail = purchaseOrderDetails.get(i);
			if(purchaseOrderDetail.getId().getPurchaseOrderFid().equals(purchaseOrderFid)){
				list.add(purchaseOrderDetail);
			}
		}
		return list;
	}
	

	public static PurchaseOrderDetail getDetail(
			List<PurchaseOrderDetail> purchaseOrderDetails, Integer itemNum, Integer itemMatrixNum) {
		for(int i = 0;i < purchaseOrderDetails.size();i++){
			PurchaseOrderDetail purchaseOrderDetail = purchaseOrderDetails.get(i);
			if(purchaseOrderDetail.getItemNum().equals(itemNum)
					&& purchaseOrderDetail.getPurchaseOrderDetailPostItemMatrixNum().equals(itemMatrixNum)){
				return purchaseOrderDetail;
			}
		}
		return null;
	}

}
