package com.nhsoft.module.report.model;



/**
 * PurchaseOrderDetailId generated by hbm2java
 */
public class PurchaseOrderDetailId implements java.io.Serializable {

	private static final long serialVersionUID = 3605899743675816205L;
	private String purchaseOrderFid;
	private Integer purchaseOrderDetailNum;

	public PurchaseOrderDetailId() {
	}

	public PurchaseOrderDetailId(String purchaseOrderFid,
			Integer purchaseOrderDetailNum) {
		this.purchaseOrderFid = purchaseOrderFid;
		this.purchaseOrderDetailNum = purchaseOrderDetailNum;
	}

	public String getPurchaseOrderFid() {
		return this.purchaseOrderFid;
	}

	public void setPurchaseOrderFid(String purchaseOrderFid) {
		this.purchaseOrderFid = purchaseOrderFid;
	}

	public Integer getPurchaseOrderDetailNum() {
		return this.purchaseOrderDetailNum;
	}

	public void setPurchaseOrderDetailNum(Integer purchaseOrderDetailNum) {
		this.purchaseOrderDetailNum = purchaseOrderDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseOrderDetailId))
			return false;
		PurchaseOrderDetailId castOther = (PurchaseOrderDetailId) other;

		return ((this.getPurchaseOrderFid() == castOther.getPurchaseOrderFid()) || (this
				.getPurchaseOrderFid() != null
				&& castOther.getPurchaseOrderFid() != null && this
				.getPurchaseOrderFid().equals(castOther.getPurchaseOrderFid())))
				&& ((this.getPurchaseOrderDetailNum() == castOther
						.getPurchaseOrderDetailNum()) || (this
						.getPurchaseOrderDetailNum() != null
						&& castOther.getPurchaseOrderDetailNum() != null && this
						.getPurchaseOrderDetailNum().equals(
								castOther.getPurchaseOrderDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPurchaseOrderFid() == null ? 0 : this
						.getPurchaseOrderFid().hashCode());
		result = 37
				* result
				+ (getPurchaseOrderDetailNum() == null ? 0 : this
						.getPurchaseOrderDetailNum().hashCode());
		return result;
	}

}
