package com.nhsoft.module.report.model;


import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.math.BigDecimal;

/**
 * SettlementDetail generated by hbm2java
 */
@Entity
public class SettlementDetail implements java.io.Serializable {

	private static final long serialVersionUID = -1669905429431623018L;
	@EmbeddedId
	private SettlementDetailId id;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="returnOrderFid")
	private ReturnOrder returnOrder;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="receiveOrderFid")
	private ReceiveOrder receiveOrder;
	private BigDecimal settlementDetailMoney;
	private BigDecimal settlementDetailDiscount;
	private String settlementDetailMemo;
	private String systemBookCode;
	private String accountBankName;
	@ManyToOne
	@NotFound(action= NotFoundAction.IGNORE)
	@JoinColumn(name="otherInoutBillNo")
	private OtherInout otherInout;

	public SettlementDetail() {
	}

	public SettlementDetailId getId() {
		return this.id;
	}

	public void setId(SettlementDetailId id) {
		this.id = id;
	}
	
	public ReturnOrder getReturnOrder() {
		return returnOrder;
	}

	public void setReturnOrder(ReturnOrder returnOrder) {
		this.returnOrder = returnOrder;
	}

	public ReceiveOrder getReceiveOrder() {
		return receiveOrder;
	}

	public void setReceiveOrder(ReceiveOrder receiveOrder) {
		this.receiveOrder = receiveOrder;
	}

	public BigDecimal getSettlementDetailMoney() {
		return this.settlementDetailMoney;
	}

	public void setSettlementDetailMoney(BigDecimal settlementDetailMoney) {
		this.settlementDetailMoney = settlementDetailMoney;
	}

	public BigDecimal getSettlementDetailDiscount() {
		return this.settlementDetailDiscount;
	}

	public void setSettlementDetailDiscount(BigDecimal settlementDetailDiscount) {
		this.settlementDetailDiscount = settlementDetailDiscount;
	}

	public String getSettlementDetailMemo() {
		return this.settlementDetailMemo;
	}

	public void setSettlementDetailMemo(String settlementDetailMemo) {
		this.settlementDetailMemo = settlementDetailMemo;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getAccountBankName() {
		return this.accountBankName;
	}

	public void setAccountBankName(String accountBankName) {
		this.accountBankName = accountBankName;
	}

	public OtherInout getOtherInout() {
		return otherInout;
	}

	public void setOtherInout(OtherInout otherInout) {
		this.otherInout = otherInout;
	}

}
