package com.nhsoft.module.report.model;



import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * ShiftTable generated by hbm2java
 */

@Entity
public class ShiftTable implements java.io.Serializable {

	/**
	 * 
	 */
	@Embeddable
	public static class ShiftTableId implements java.io.Serializable {
		
		/**
		 *
		 */
		private static final long serialVersionUID = 3283199860369666345L;
		private String systemBookCode;
		private Integer branchNum;
		private Integer shiftTableNum;
		private String shiftTableBizday;
		
		public ShiftTableId() {
		}
		
		public ShiftTableId(String systemBookCode, Integer branchNum,
		                    Integer shiftTableNum, String shiftTableBizday) {
			this.systemBookCode = systemBookCode;
			this.branchNum = branchNum;
			this.shiftTableNum = shiftTableNum;
			this.shiftTableBizday = shiftTableBizday;
		}
		
		public String getSystemBookCode() {
			return this.systemBookCode;
		}
		
		public void setSystemBookCode(String systemBookCode) {
			this.systemBookCode = systemBookCode;
		}
		
		public Integer getBranchNum() {
			return this.branchNum;
		}
		
		public void setBranchNum(Integer branchNum) {
			this.branchNum = branchNum;
		}
		
		public Integer getShiftTableNum() {
			return this.shiftTableNum;
		}
		
		public void setShiftTableNum(Integer shiftTableNum) {
			this.shiftTableNum = shiftTableNum;
		}
		
		public String getShiftTableBizday() {
			return this.shiftTableBizday;
		}
		
		public void setShiftTableBizday(String shiftTableBizday) {
			this.shiftTableBizday = shiftTableBizday;
		}
		
		
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((branchNum == null) ? 0 : branchNum.hashCode());
			result = prime * result + ((shiftTableBizday == null) ? 0 : shiftTableBizday.hashCode());
			result = prime * result + ((shiftTableNum == null) ? 0 : shiftTableNum.hashCode());
			result = prime * result + ((systemBookCode == null) ? 0 : systemBookCode.hashCode());
			return result;
		}
		
		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			ShiftTableId other = (ShiftTableId) obj;
			if (branchNum == null) {
				if (other.branchNum != null)
					return false;
			} else if (!branchNum.equals(other.branchNum))
				return false;
			if (shiftTableBizday == null) {
				if (other.shiftTableBizday != null)
					return false;
			} else if (!shiftTableBizday.equals(other.shiftTableBizday))
				return false;
			if (shiftTableNum == null) {
				if (other.shiftTableNum != null)
					return false;
			} else if (!shiftTableNum.equals(other.shiftTableNum))
				return false;
			if (systemBookCode == null) {
				if (other.systemBookCode != null)
					return false;
			} else if (!systemBookCode.equals(other.systemBookCode))
				return false;
			return true;
		}
		
		public static ShiftTableId getByClosedCashId(String closedCashId) {
			String[] array = closedCashId.split("-");
			ShiftTableId id = new ShiftTableId(array[0], Integer.parseInt(array[1]), Integer.parseInt(array[3]), array[2]);
			return id;
		}
		
		public String getClosedCashId() {
			return systemBookCode + "-" + branchNum + "-" + shiftTableBizday + "-" + shiftTableNum;
		}
		
	}
	
	private static final long serialVersionUID = 1225341176889558728L;
	@EmbeddedId
	private ShiftTableId id;
	private Date shiftTableBizDate;
	private Date shiftTableStart;
	private Date shiftTableEnd;
	private Integer shiftTableUserNum;
	private String shiftTableUserCode;
	private String shiftTableUserName;
	private boolean shiftTableClosed;
	private boolean shiftTableSynchronized;
	private boolean shiftTableNeedCarry;
	private boolean shiftTableCarried;
	private String shiftTableTerminalId;
	private Boolean shiftTableDpcSynchronized;
	private BigDecimal shiftTableActualMoney;
	private BigDecimal shiftTableActualBankMoney;
	private Integer shiftTableStatus;
	private String shiftTableMemo;
	
	public Integer getShiftTableStatus() {
		return shiftTableStatus;
	}

	public void setShiftTableStatus(Integer shiftTableStatus) {
		this.shiftTableStatus = shiftTableStatus;
	}

	public String getShiftTableMemo() {
		return shiftTableMemo;
	}

	public void setShiftTableMemo(String shiftTableMemo) {
		this.shiftTableMemo = shiftTableMemo;
	}

	public BigDecimal getShiftTableActualBankMoney() {
		return shiftTableActualBankMoney;
	}

	public void setShiftTableActualBankMoney(BigDecimal shiftTableActualBankMoney) {
		this.shiftTableActualBankMoney = shiftTableActualBankMoney;
	}

	public Boolean getShiftTableDpcSynchronized() {
		return shiftTableDpcSynchronized;
	}

	public void setShiftTableDpcSynchronized(Boolean shiftTableDpcSynchronized) {
		this.shiftTableDpcSynchronized = shiftTableDpcSynchronized;
	}

	//临时属性
	private String branchName;

	public ShiftTable() {
	}

	public ShiftTableId getId() {
		return this.id;
	}

	public void setId(ShiftTableId id) {
		this.id = id;
	}

	public Date getShiftTableBizDate() {
		return this.shiftTableBizDate;
	}

	public void setShiftTableBizDate(Date shiftTableBizDate) {
		this.shiftTableBizDate = shiftTableBizDate;
	}

	public Date getShiftTableStart() {
		return this.shiftTableStart;
	}

	public void setShiftTableStart(Date shiftTableStart) {
		this.shiftTableStart = shiftTableStart;
	}

	public Date getShiftTableEnd() {
		return this.shiftTableEnd;
	}

	public void setShiftTableEnd(Date shiftTableEnd) {
		this.shiftTableEnd = shiftTableEnd;
	}

	public Integer getShiftTableUserNum() {
		return this.shiftTableUserNum;
	}

	public void setShiftTableUserNum(Integer shiftTableUserNum) {
		this.shiftTableUserNum = shiftTableUserNum;
	}

	public String getShiftTableUserCode() {
		return this.shiftTableUserCode;
	}

	public void setShiftTableUserCode(String shiftTableUserCode) {
		this.shiftTableUserCode = shiftTableUserCode;
	}

	public String getShiftTableUserName() {
		return this.shiftTableUserName;
	}

	public void setShiftTableUserName(String shiftTableUserName) {
		this.shiftTableUserName = shiftTableUserName;
	}

	public boolean isShiftTableClosed() {
		return this.shiftTableClosed;
	}

	public void setShiftTableClosed(boolean shiftTableClosed) {
		this.shiftTableClosed = shiftTableClosed;
	}

	public boolean isShiftTableSynchronized() {
		return this.shiftTableSynchronized;
	}

	public void setShiftTableSynchronized(boolean shiftTableSynchronized) {
		this.shiftTableSynchronized = shiftTableSynchronized;
	}

	public boolean isShiftTableNeedCarry() {
		return this.shiftTableNeedCarry;
	}

	public void setShiftTableNeedCarry(boolean shiftTableNeedCarry) {
		this.shiftTableNeedCarry = shiftTableNeedCarry;
	}

	public boolean isShiftTableCarried() {
		return this.shiftTableCarried;
	}

	public void setShiftTableCarried(boolean shiftTableCarried) {
		this.shiftTableCarried = shiftTableCarried;
	}

	public String getShiftTableTerminalId() {
		return this.shiftTableTerminalId;
	}

	public void setShiftTableTerminalId(String shiftTableTerminalId) {
		this.shiftTableTerminalId = shiftTableTerminalId;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public BigDecimal getShiftTableActualMoney() {
		return shiftTableActualMoney;
	}

	public void setShiftTableActualMoney(BigDecimal shiftTableActualMoney) {
		this.shiftTableActualMoney = shiftTableActualMoney;
	}

	public static ShiftTable getShiftTable(List<ShiftTable> shiftTables, Integer branchNum, String shiftTableBizday,
			Integer shiftTableNum) {
		for(int i = 0;i < shiftTables.size();i++){
			ShiftTable shiftTable = shiftTables.get(i);
			if(shiftTable.getId().getBranchNum().equals(branchNum) 
					&& shiftTable.getId().getShiftTableBizday().equals(shiftTableBizday)
					&& shiftTable.getId().getShiftTableNum().equals(shiftTableNum)){
				return shiftTable;
			}
		}
		return null;
	}

}
