package com.nhsoft.module.report.model;

import javax.persistence.Embeddable;


/**
 * ShiftTableId generated by hbm2java
 */
@Embeddable
public class ShiftTableId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3283199860369666345L;
	private String systemBookCode;
	private Integer branchNum;
	private Integer shiftTableNum;
	private String shiftTableBizday;

	public ShiftTableId() {
	}

	public ShiftTableId(String systemBookCode, Integer branchNum,
			Integer shiftTableNum, String shiftTableBizday) {
		this.systemBookCode = systemBookCode;
		this.branchNum = branchNum;
		this.shiftTableNum = shiftTableNum;
		this.shiftTableBizday = shiftTableBizday;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getShiftTableNum() {
		return this.shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((branchNum == null) ? 0 : branchNum.hashCode());
		result = prime * result + ((shiftTableBizday == null) ? 0 : shiftTableBizday.hashCode());
		result = prime * result + ((shiftTableNum == null) ? 0 : shiftTableNum.hashCode());
		result = prime * result + ((systemBookCode == null) ? 0 : systemBookCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ShiftTableId other = (ShiftTableId) obj;
		if (branchNum == null) {
			if (other.branchNum != null)
				return false;
		} else if (!branchNum.equals(other.branchNum))
			return false;
		if (shiftTableBizday == null) {
			if (other.shiftTableBizday != null)
				return false;
		} else if (!shiftTableBizday.equals(other.shiftTableBizday))
			return false;
		if (shiftTableNum == null) {
			if (other.shiftTableNum != null)
				return false;
		} else if (!shiftTableNum.equals(other.shiftTableNum))
			return false;
		if (systemBookCode == null) {
			if (other.systemBookCode != null)
				return false;
		} else if (!systemBookCode.equals(other.systemBookCode))
			return false;
		return true;
	}

	public static ShiftTableId getByClosedCashId(String closedCashId) {
		String[] array = closedCashId.split("-");
		ShiftTableId id = new ShiftTableId(array[0], Integer.parseInt(array[1]), Integer.parseInt(array[3]), array[2]);
		return id;
	}

	public String getClosedCashId() {
		return systemBookCode + "-" + branchNum + "-" + shiftTableBizday + "-" + shiftTableNum;
	}

}
