package com.nhsoft.module.report.model;

import com.nhsoft.module.report.query.State;
import org.apache.commons.lang3.StringUtils;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * TaskRequest generated by hbm2java
 */
public class TaskRequest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2249491013253698564L;
	private String taskRequestFid;
	private String systemBookCode;
	private Integer branchNum;
	private Integer itemNum;
	private String taskRequestBizday;
	private Date taskRequestTime;
	private String taskRequestItemCode;
	private String taskRequestItemSpec;
	private String taskRequestItemUnit;
	private BigDecimal taskRequestItemQty;
	private String taskRequestItemStockUnit;
	private BigDecimal taskRequestItemStockQty;
	private String taskRequestItemName;
	private BigDecimal taskRequestItemUseRate;
	private String taskRequestItemCostMode;
	private String taskRequestItemCategoryCode;
	private Boolean taskRequestItemIgnore = false;
	private Integer storehouseNum;
	private String taskRequestDefaultUserName;
	private Integer taskRequestUserNum;
	private String taskRequestUserName;
	private BigDecimal taskRequestItemReceiveQty;//采购收货数量
	private BigDecimal taskRequestItemOutQty; //出仓数量
	private BigDecimal taskRequestItemLastRate;	 //上次采购转换率
	private BigDecimal taskRequestItemPurchaseQty;//实际采购数量
	private String taskRequestItemDepartment;//商品部门
	private BigDecimal taskRequestPickQty;//实际采购数量
	private String taskRequestItemBaseUnit; //基本单位数量
	private BigDecimal taskRequestTarePrice;//配送任务中上次录入的筐单价
	private BigDecimal taskRequestPickBasicQty;
	private State state;
	private List<TaskRequestDetail> taskRequestDetails = new ArrayList<TaskRequestDetail>();
	
	//临时属性
	private BigDecimal orderTaskBalanceQty; //剩余订量(本次订量)
	private Integer taskRequestBranchCount; //要货门店数
	private boolean hasMaterial = false;//是否有原料
	private PosItem posItem;
	private boolean useAssistUnit = false;
	
	public TaskRequest() {
		
		setTaskRequestItemPurchaseQty(BigDecimal.ZERO);
		setTaskRequestPickQty(BigDecimal.ZERO);
	}
	
	public boolean isUseAssistUnit() {
		return useAssistUnit;
	}
	
	public void setUseAssistUnit(boolean useAssistUnit) {
		this.useAssistUnit = useAssistUnit;
	}
	
	public PosItem getPosItem() {
		return posItem;
	}

	public void setPosItem(PosItem posItem) {
		this.posItem = posItem;
	}

	public boolean isHasMaterial() {
		return hasMaterial;
	}

	public void setHasMaterial(boolean hasMaterial) {
		this.hasMaterial = hasMaterial;
	}

	public BigDecimal getTaskRequestPickBasicQty() {
		return taskRequestPickBasicQty;
	}

	public void setTaskRequestPickBasicQty(BigDecimal taskRequestPickBasicQty) {
		this.taskRequestPickBasicQty = taskRequestPickBasicQty;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public BigDecimal getTaskRequestTarePrice() {
		return taskRequestTarePrice;
	}

	public void setTaskRequestTarePrice(BigDecimal taskRequestTarePrice) {
		this.taskRequestTarePrice = taskRequestTarePrice;
	}

	public String getTaskRequestItemBaseUnit() {
		return taskRequestItemBaseUnit;
	}

	public void setTaskRequestItemBaseUnit(String taskRequestItemBaseUnit) {
		this.taskRequestItemBaseUnit = taskRequestItemBaseUnit;
	}

	public BigDecimal getTaskRequestPickQty() {
		return taskRequestPickQty;
	}

	public void setTaskRequestPickQty(BigDecimal taskRequestPickQty) {
		this.taskRequestPickQty = taskRequestPickQty;
	}

	public String getTaskRequestItemDepartment() {
		return taskRequestItemDepartment;
	}

	public void setTaskRequestItemDepartment(String taskRequestItemDepartment) {
		this.taskRequestItemDepartment = taskRequestItemDepartment;
	}

	public BigDecimal getTaskRequestItemReceiveQty() {
		return taskRequestItemReceiveQty;
	}

	public void setTaskRequestItemReceiveQty(BigDecimal taskRequestItemReceiveQty) {
		this.taskRequestItemReceiveQty = taskRequestItemReceiveQty;
	}

	
	public String getTaskRequestItemCategoryCode() {
		return taskRequestItemCategoryCode;
	}

	public void setTaskRequestItemCategoryCode(String taskRequestItemCategoryCode) {
		this.taskRequestItemCategoryCode = taskRequestItemCategoryCode;
	}

	public Boolean getTaskRequestItemIgnore() {
		return taskRequestItemIgnore;
	}

	public void setTaskRequestItemIgnore(Boolean taskRequestItemIgnore) {
		this.taskRequestItemIgnore = taskRequestItemIgnore;
	}


	public String getTaskRequestItemCostMode() {
		return taskRequestItemCostMode;
	}

	public void setTaskRequestItemCostMode(String taskRequestItemCostMode) {
		this.taskRequestItemCostMode = taskRequestItemCostMode;
	}

	public BigDecimal getOrderTaskBalanceQty() {
		return orderTaskBalanceQty;
	}

	public void setOrderTaskBalanceQty(BigDecimal orderTaskBalanceQty) {
		this.orderTaskBalanceQty = orderTaskBalanceQty;
	}

	public TaskRequest(String taskRequestFid) {
		this.taskRequestFid = taskRequestFid;
	}

	public String getTaskRequestFid() {
		return this.taskRequestFid;
	}

	public void setTaskRequestFid(String taskRequestFid) {
		this.taskRequestFid = taskRequestFid;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getTaskRequestBizday() {
		return this.taskRequestBizday;
	}

	public void setTaskRequestBizday(String taskRequestBizday) {
		this.taskRequestBizday = taskRequestBizday;
	}

	public Date getTaskRequestTime() {
		return this.taskRequestTime;
	}

	public void setTaskRequestTime(Date taskRequestTime) {
		this.taskRequestTime = taskRequestTime;
	}

	public String getTaskRequestItemCode() {
		return this.taskRequestItemCode;
	}

	public void setTaskRequestItemCode(String taskRequestItemCode) {
		this.taskRequestItemCode = taskRequestItemCode;
	}

	public String getTaskRequestItemSpec() {
		return this.taskRequestItemSpec;
	}

	public void setTaskRequestItemSpec(String taskRequestItemSpec) {
		this.taskRequestItemSpec = taskRequestItemSpec;
	}

	public String getTaskRequestItemUnit() {
		return this.taskRequestItemUnit;
	}

	public void setTaskRequestItemUnit(String taskRequestItemUnit) {
		this.taskRequestItemUnit = taskRequestItemUnit;
	}

	public BigDecimal getTaskRequestItemQty() {
		return this.taskRequestItemQty;
	}

	public void setTaskRequestItemQty(BigDecimal taskRequestItemQty) {
		this.taskRequestItemQty = taskRequestItemQty;
	}

	public String getTaskRequestItemStockUnit() {
		return this.taskRequestItemStockUnit;
	}

	public void setTaskRequestItemStockUnit(String taskRequestItemStockUnit) {
		this.taskRequestItemStockUnit = taskRequestItemStockUnit;
	}

	public BigDecimal getTaskRequestItemStockQty() {
		return this.taskRequestItemStockQty;
	}

	public void setTaskRequestItemStockQty(BigDecimal taskRequestItemStockQty) {
		this.taskRequestItemStockQty = taskRequestItemStockQty;
	}

	public List<TaskRequestDetail> getTaskRequestDetails() {
		return taskRequestDetails;
	}

	public void setTaskRequestDetails(List<TaskRequestDetail> taskRequestDetails) {
		this.taskRequestDetails = taskRequestDetails;
	}
	
	public String getTaskRequestItemName() {
		return taskRequestItemName;
	}

	public void setTaskRequestItemName(String taskRequestItemName) {
		this.taskRequestItemName = taskRequestItemName;
	}

	public BigDecimal getTaskRequestItemUseRate() {
		return taskRequestItemUseRate;
	}

	public void setTaskRequestItemUseRate(BigDecimal taskRequestItemUseRate) {
		this.taskRequestItemUseRate = taskRequestItemUseRate;
	}

	public Integer getStorehouseNum() {
		return storehouseNum;
	}

	public void setStorehouseNum(Integer storehouseNum) {
		this.storehouseNum = storehouseNum;
	}

	public String getTaskRequestDefaultUserName() {
		return taskRequestDefaultUserName;
	}

	public void setTaskRequestDefaultUserName(String taskRequestDefaultUserName) {
		this.taskRequestDefaultUserName = taskRequestDefaultUserName;
	}

	public Integer getTaskRequestUserNum() {
		return taskRequestUserNum;
	}

	public void setTaskRequestUserNum(Integer taskRequestUserNum) {
		this.taskRequestUserNum = taskRequestUserNum;
	}

	public String getTaskRequestUserName() {
		return taskRequestUserName;
	}

	public void setTaskRequestUserName(String taskRequestUserName) {
		this.taskRequestUserName = taskRequestUserName;
	}

	public BigDecimal getTaskRequestItemOutQty() {
		return taskRequestItemOutQty;
	}

	public void setTaskRequestItemOutQty(BigDecimal taskRequestItemOutQty) {
		this.taskRequestItemOutQty = taskRequestItemOutQty;
	}

	public BigDecimal getTaskRequestItemLastRate() {
		return taskRequestItemLastRate;
	}

	public void setTaskRequestItemLastRate(BigDecimal taskRequestItemLastRate) {
		this.taskRequestItemLastRate = taskRequestItemLastRate;
	}

	public BigDecimal getTaskRequestItemPurchaseQty() {
		return taskRequestItemPurchaseQty;
	}

	public void setTaskRequestItemPurchaseQty(BigDecimal taskRequestItemPurchaseQty) {
		this.taskRequestItemPurchaseQty = taskRequestItemPurchaseQty;
	}

	public Integer getTaskRequestBranchCount() {
		return taskRequestBranchCount;
	}

	public void setTaskRequestBranchCount(Integer taskRequestBranchCount) {
		this.taskRequestBranchCount = taskRequestBranchCount;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskRequestFid == null) ? 0 : taskRequestFid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaskRequest other = (TaskRequest) obj;
		if (taskRequestFid == null) {
			if (other.taskRequestFid != null)
				return false;
		} else if (!taskRequestFid.equals(other.taskRequestFid))
			return false;
		return true;
	}

	public static TaskRequest getTaskRequest(List<TaskRequest> taskRequests, Integer itemNum){
		for(int i = 0;i < taskRequests.size();i++){
			TaskRequest taskRequest = taskRequests.get(i);
			if(taskRequest.getItemNum().equals(itemNum)){
				return taskRequest;
			}
		}
		return null;
	}
	
	public static TaskRequest getTaskRequest(List<TaskRequest> taskRequests, String taskRequestFid){
		for(int i = 0;i < taskRequests.size();i++){
			TaskRequest taskRequest = taskRequests.get(i);
			if(taskRequest.getTaskRequestFid().equals(taskRequestFid)){
				return taskRequest;
			}
		}
		return null;
	}
	
	public String getDetailsMemo(Integer toBranchNum){
		StringBuffer sb = new StringBuffer();
		boolean hasMemo = false;
		for(int i = 0;i < taskRequestDetails.size();i++){
			TaskRequestDetail detail = taskRequestDetails.get(i);
			if(!detail.getTaskRequestDetailBranchNum().equals(toBranchNum)){
				continue;
			}
			
			if(StringUtils.isNotEmpty(detail.getTaskRequestDetailMemo())){
				if(hasMemo){
					sb.append(";");
				}			
				sb.append(detail.getTaskRequestDetailMemo());
				hasMemo = true;
			}
		}
		return sb.toString();
	}


}
