package com.nhsoft.module.report.model;



import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * TransferLine generated by hbm2java
 */
@Entity
public class TransferLine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4044172387854090634L;
	@Id
	private int transferLineNum;
	private String systemBookCode;
	private Integer branchNum;
	private String transferLineCode;
	private String transferLineName;
	private BigDecimal transferLineMoney;
	private String transferLineExpress;

	@OneToMany(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "transferLineNum", updatable=false, insertable=false)
	private List<TransferLineDetail> transferLineDetails = new ArrayList<TransferLineDetail>();
	
	//lazy读取 服务端处理时使用
	@ManyToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinTable(name="TransferLineDetail", joinColumns={@JoinColumn(name="transferLineNum")}, inverseJoinColumns={@JoinColumn(name="systemBookCode", referencedColumnName="systemBookCode"), @JoinColumn(name="branchNum", referencedColumnName="branchNum")})
	private List<Branch> branchs = new ArrayList<Branch>();

	public TransferLine() {
	}

	public String getTransferLineExpress() {
		return transferLineExpress;
	}

	public void setTransferLineExpress(String transferLineExpress) {
		this.transferLineExpress = transferLineExpress;
	}

	public int getTransferLineNum() {
		return this.transferLineNum;
	}

	public void setTransferLineNum(int transferLineNum) {
		this.transferLineNum = transferLineNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getTransferLineCode() {
		return this.transferLineCode;
	}

	public void setTransferLineCode(String transferLineCode) {
		this.transferLineCode = transferLineCode;
	}

	public String getTransferLineName() {
		return this.transferLineName;
	}

	public void setTransferLineName(String transferLineName) {
		this.transferLineName = transferLineName;
	}

	public List<Branch> getBranchs() {
		return branchs;
	}

	public void setBranchs(List<Branch> branchs) {
		this.branchs = branchs;
	}

	public List<TransferLineDetail> getTransferLineDetails() {
		return transferLineDetails;
	}

	public void setTransferLineDetails(List<TransferLineDetail> transferLineDetails) {
		this.transferLineDetails = transferLineDetails;
	}

	public Integer getBranchNum() {
		return branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public BigDecimal getTransferLineMoney() {
		return transferLineMoney;
	}

	public void setTransferLineMoney(BigDecimal transferLineMoney) {
		this.transferLineMoney = transferLineMoney;
	}
	

}
