package com.nhsoft.module.report.model;

import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * WeixinItemDetail generated by hbm2java
 */
@Entity
public class WeixinItemDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4585616063022508645L;
	@Id
	private int weixinItemNum;
	private String weixinItemDetailContext;

	public WeixinItemDetail() {
	}

	public WeixinItemDetail(int weixinItemNum) {
		this.weixinItemNum = weixinItemNum;
	}

	public int getWeixinItemNum() {
		return this.weixinItemNum;
	}

	public void setWeixinItemNum(int weixinItemNum) {
		this.weixinItemNum = weixinItemNum;
	}

	public String getWeixinItemDetailContext() {
		return weixinItemDetailContext;
	}

	public void setWeixinItemDetailContext(String weixinItemDetailContext) {
		this.weixinItemDetailContext = weixinItemDetailContext;
	}
	
}
