package com.nhsoft.module.report.model;



/**
 * WholesaleBookDetailId generated by hbm2java
 */
public class WholesaleBookDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1950122975904677416L;
	private String wholesaleBookFid;
	private Integer bookDetailNum;

	public WholesaleBookDetailId() {
	}

	public WholesaleBookDetailId(String wholesaleBookFid, Integer bookDetailNum) {
		this.wholesaleBookFid = wholesaleBookFid;
		this.bookDetailNum = bookDetailNum;
	}

	public String getWholesaleBookFid() {
		return this.wholesaleBookFid;
	}

	public void setWholesaleBookFid(String wholesaleBookFid) {
		this.wholesaleBookFid = wholesaleBookFid;
	}

	public Integer getBookDetailNum() {
		return this.bookDetailNum;
	}

	public void setBookDetailNum(Integer bookDetailNum) {
		this.bookDetailNum = bookDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WholesaleBookDetailId))
			return false;
		WholesaleBookDetailId castOther = (WholesaleBookDetailId) other;

		return ((this.getWholesaleBookFid() == castOther.getWholesaleBookFid()) || (this
				.getWholesaleBookFid() != null
				&& castOther.getWholesaleBookFid() != null && this
				.getWholesaleBookFid().equals(castOther.getWholesaleBookFid())))
				&& ((this.getBookDetailNum() == castOther.getBookDetailNum()) || (this
						.getBookDetailNum() != null
						&& castOther.getBookDetailNum() != null && this
						.getBookDetailNum()
						.equals(castOther.getBookDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getWholesaleBookFid() == null ? 0 : this
						.getWholesaleBookFid().hashCode());
		result = 37
				* result
				+ (getBookDetailNum() == null ? 0 : this.getBookDetailNum()
						.hashCode());
		return result;
	}

}
