package com.nhsoft.module.report.model;


import com.nhsoft.module.report.query.State;
import com.nhsoft.module.report.util.AppConstants;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * WholesaleBook generated by hbm2java
 */
@Entity
public class WholesaleBook implements java.io.Serializable {

	private static final long serialVersionUID = -4886039872153136993L;
	@Id
	private String wholesaleBookFid;
	private String clientFid;
	private Integer storehouseNum;
	private String systemBookCode;
	private Integer branchNum;
	private Date wholesaleBookDate;
	private Date wholesaleBookDeadline;
	private String wholesaleBookSeller;
	@Embedded
	@AttributeOverrides( {
		 			@AttributeOverride(name="stateCode", column = @Column(name="wholesaleBookStateCode")), 
		@AttributeOverride(name="stateName", column = @Column(name="wholesaleBookStateName")) } )
	private State state;
	private String wholesaleBookCreator;
	private Date wholesaleBookCreateTime;
	private String wholesaleBookAuditor;
	private Date wholesaleBookAuditTime;
	private Boolean wholesaleBookTransferFlag;
	private String wholesaleBookUuid;
	private String wholesaleBookMemo;
	private String wholesaleBookCancelOperator;
	private Date wholesaleBookCancelTime;
	private BigDecimal wholesaleBookTotalMoney;
	private BigDecimal wholesaleBookPreMoney;
	private Integer regionNum;
	private String wholesaleBookPayType;
	private Integer accountBankNum;
	private BigDecimal wholesaleBookPayDiscount;
	private BigDecimal wholesaleBookPayMoney;
	private String wholesaleBookInnerNo;
	private Boolean wholesaleBookRepealFlag;
	private String wholesaleBookBillNo;
	private Date wholesaleBookSaleDate;
	private Date wholesaleBookPickDate;
	private Date wholesaleBookSendDate;
	private Date wholesaleBookReceiveDate;
	private String wholesaleBookRefBillNo;
	private Date wholesaleBookLastEditTime;
	private String wholesaleBookSaleState;
	private Boolean wholesaleBookAntiFlag;
	private String wholesaleBookAuditBizday;

	@OneToMany
	@Fetch(FetchMode.SUBSELECT)
	@JoinColumn(name = "wholesaleBookFid", updatable=false, insertable=false)
	private List<WholesaleBookDetail> wholesaleBookDetails = new ArrayList<WholesaleBookDetail>(0);
	
	@Transient
	private AppUser appUser;
	@Transient
	private String copyFid;
	
	
	public String getCopyFid() {
		return copyFid;
	}

	public void setCopyFid(String copyFid) {
		this.copyFid = copyFid;
	}
	
    public AppUser getAppUser() {
		return appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}
	
	public String getWholesaleBookAuditBizday() {
		return wholesaleBookAuditBizday;
	}

	public void setWholesaleBookAuditBizday(String wholesaleBookAuditBizday) {
		this.wholesaleBookAuditBizday = wholesaleBookAuditBizday;
	}

	public WholesaleBook() {
	}

	public Boolean getWholesaleBookAntiFlag() {
		return wholesaleBookAntiFlag;
	}

	public void setWholesaleBookAntiFlag(Boolean wholesaleBookAntiFlag) {
		this.wholesaleBookAntiFlag = wholesaleBookAntiFlag;
	}

	public String getWholesaleBookSaleState() {
		return wholesaleBookSaleState;
	}

	public void setWholesaleBookSaleState(String wholesaleBookSaleState) {
		this.wholesaleBookSaleState = wholesaleBookSaleState;
	}

	public Date getWholesaleBookLastEditTime() {
		return wholesaleBookLastEditTime;
	}

	public void setWholesaleBookLastEditTime(Date wholesaleBookLastEditTime) {
		this.wholesaleBookLastEditTime = wholesaleBookLastEditTime;
	}

	public String getWholesaleBookRefBillNo() {
		return wholesaleBookRefBillNo;
	}

	public void setWholesaleBookRefBillNo(String wholesaleBookRefBillNo) {
		this.wholesaleBookRefBillNo = wholesaleBookRefBillNo;
	}

	public Date getWholesaleBookSaleDate() {
		return wholesaleBookSaleDate;
	}

	public void setWholesaleBookSaleDate(Date wholesaleBookSaleDate) {
		this.wholesaleBookSaleDate = wholesaleBookSaleDate;
	}

	public Date getWholesaleBookPickDate() {
		return wholesaleBookPickDate;
	}

	public void setWholesaleBookPickDate(Date wholesaleBookPickDate) {
		this.wholesaleBookPickDate = wholesaleBookPickDate;
	}

	public Date getWholesaleBookSendDate() {
		return wholesaleBookSendDate;
	}

	public void setWholesaleBookSendDate(Date wholesaleBookSendDate) {
		this.wholesaleBookSendDate = wholesaleBookSendDate;
	}

	public Date getWholesaleBookReceiveDate() {
		return wholesaleBookReceiveDate;
	}

	public void setWholesaleBookReceiveDate(Date wholesaleBookReceiveDate) {
		this.wholesaleBookReceiveDate = wholesaleBookReceiveDate;
	}

	public Integer getRegionNum() {
		return regionNum;
	}

	public void setRegionNum(Integer regionNum) {
		this.regionNum = regionNum;
	}

	public Boolean getWholesaleBookRepealFlag() {
		return wholesaleBookRepealFlag;
	}

	public void setWholesaleBookRepealFlag(Boolean wholesaleBookRepealFlag) {
		this.wholesaleBookRepealFlag = wholesaleBookRepealFlag;
	}

	public String getWholesaleBookBillNo() {
		return wholesaleBookBillNo;
	}

	public void setWholesaleBookBillNo(String wholesaleBookBillNo) {
		this.wholesaleBookBillNo = wholesaleBookBillNo;
	}

	public BigDecimal getWholesaleBookPreMoney() {
		return wholesaleBookPreMoney;
	}

	public void setWholesaleBookPreMoney(BigDecimal wholesaleBookPreMoney) {
		this.wholesaleBookPreMoney = wholesaleBookPreMoney;
	}

	public String getWholesaleBookFid() {
		return this.wholesaleBookFid;
	}

	public void setWholesaleBookFid(String wholesaleBookFid) {
		this.wholesaleBookFid = wholesaleBookFid;
	}

	public Integer getStorehouseNum() {
		return this.storehouseNum;
	}

	public void setStorehouseNum(Integer storehouseNum) {
		this.storehouseNum = storehouseNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Date getWholesaleBookDate() {
		return this.wholesaleBookDate;
	}

	public void setWholesaleBookDate(Date wholesaleBookDate) {
		this.wholesaleBookDate = wholesaleBookDate;
	}

	public Date getWholesaleBookDeadline() {
		return this.wholesaleBookDeadline;
	}

	public void setWholesaleBookDeadline(Date wholesaleBookDeadline) {
		this.wholesaleBookDeadline = wholesaleBookDeadline;
	}

	public String getWholesaleBookSeller() {
		return this.wholesaleBookSeller;
	}

	public void setWholesaleBookSeller(String wholesaleBookSeller) {
		this.wholesaleBookSeller = wholesaleBookSeller;
	}

	public String getClientFid() {
		return clientFid;
	}

	public void setClientFid(String clientFid) {
		this.clientFid = clientFid;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public List<WholesaleBookDetail> getWholesaleBookDetails() {
		return wholesaleBookDetails;
	}

	public void setWholesaleBookDetails(
			List<WholesaleBookDetail> wholesaleBookDetails) {
		this.wholesaleBookDetails = wholesaleBookDetails;
	}

	public String getWholesaleBookCreator() {
		return this.wholesaleBookCreator;
	}

	public void setWholesaleBookCreator(String wholesaleBookCreator) {
		this.wholesaleBookCreator = wholesaleBookCreator;
	}

	public Date getWholesaleBookCreateTime() {
		return this.wholesaleBookCreateTime;
	}

	public void setWholesaleBookCreateTime(Date wholesaleBookCreateTime) {
		this.wholesaleBookCreateTime = wholesaleBookCreateTime;
	}

	public String getWholesaleBookAuditor() {
		return this.wholesaleBookAuditor;
	}

	public void setWholesaleBookAuditor(String wholesaleBookAuditor) {
		this.wholesaleBookAuditor = wholesaleBookAuditor;
	}

	public Date getWholesaleBookAuditTime() {
		return this.wholesaleBookAuditTime;
	}

	public void setWholesaleBookAuditTime(Date wholesaleBookAuditTime) {
		this.wholesaleBookAuditTime = wholesaleBookAuditTime;

	}

	public Boolean getWholesaleBookTransferFlag() {
		return this.wholesaleBookTransferFlag;
	}

	public void setWholesaleBookTransferFlag(Boolean wholesaleBookTransferFlag) {
		this.wholesaleBookTransferFlag = wholesaleBookTransferFlag;
	}

	public String getWholesaleBookUuid() {
		return this.wholesaleBookUuid;
	}

	public void setWholesaleBookUuid(String wholesaleBookUuid) {
		this.wholesaleBookUuid = wholesaleBookUuid;
	}

	public String getWholesaleBookMemo() {
		return this.wholesaleBookMemo;
	}

	public void setWholesaleBookMemo(String wholesaleBookMemo) {
		this.wholesaleBookMemo = wholesaleBookMemo;
	}

	public String getWholesaleBookCancelOperator() {
		return this.wholesaleBookCancelOperator;
	}

	public void setWholesaleBookCancelOperator(
			String wholesaleBookCancelOperator) {
		this.wholesaleBookCancelOperator = wholesaleBookCancelOperator;
	}

	public Date getWholesaleBookCancelTime() {
		return this.wholesaleBookCancelTime;
	}

	public void setWholesaleBookCancelTime(Date wholesaleBookCancelTime) {
		this.wholesaleBookCancelTime = wholesaleBookCancelTime;
	}

	public BigDecimal getWholesaleBookTotalMoney() {
		return this.wholesaleBookTotalMoney;
	}

	public void setWholesaleBookTotalMoney(BigDecimal wholesaleBookTotalMoney) {
		this.wholesaleBookTotalMoney = wholesaleBookTotalMoney;
	}

	public String getWholesaleBookPayType() {
		return wholesaleBookPayType;
	}

	public void setWholesaleBookPayType(String wholesaleBookPayType) {
		this.wholesaleBookPayType = wholesaleBookPayType;
	}

	public Integer getAccountBankNum() {
		return accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public BigDecimal getWholesaleBookPayDiscount() {
		return wholesaleBookPayDiscount;
	}

	public void setWholesaleBookPayDiscount(BigDecimal wholesaleBookPayDiscount) {
		this.wholesaleBookPayDiscount = wholesaleBookPayDiscount;
	}

	public BigDecimal getWholesaleBookPayMoney() {
		return wholesaleBookPayMoney;
	}

	public void setWholesaleBookPayMoney(BigDecimal wholesaleBookPayMoney) {
		this.wholesaleBookPayMoney = wholesaleBookPayMoney;
	}

	public String getWholesaleBookInnerNo() {
		return wholesaleBookInnerNo;
	}

	public void setWholesaleBookInnerNo(String wholesaleBookInnerNo) {
		this.wholesaleBookInnerNo = wholesaleBookInnerNo;
	}

	public void removeZeroDetail(){
		for(int i = wholesaleBookDetails.size() - 1;i >= 0;i--){
			WholesaleBookDetail detail = wholesaleBookDetails.get(i);
			if(detail.getBookDetailPresentUseQty() == null){
				detail.setBookDetailPresentUseQty(BigDecimal.ZERO);
			}
			if(detail.getBookDetailUseQty().compareTo(BigDecimal.ZERO) == 0 
					&& detail.getBookDetailPresentUseQty().compareTo(BigDecimal.ZERO) == 0){
				wholesaleBookDetails.remove(i);
			}
		}
	}
	
	public void recal() {
		wholesaleBookTotalMoney = BigDecimal.ZERO;
		for (int i = wholesaleBookDetails.size() - 1; i >= 0; i--) {
			WholesaleBookDetail detail = wholesaleBookDetails.get(i);
			if(detail.getBookDetailStockoutTag() != null && detail.getBookDetailStockoutTag()){
				continue;
			}			
	
			detail.setBookDetailMoney(detail.getBookDetailUseQty().multiply(detail.getBookDetailUsePrice()).setScale(2, BigDecimal.ROUND_HALF_UP));
			detail.setBookDetailQty(detail.getBookDetailUseQty().multiply(detail.getBookDetailUseRate()));
			if(detail.getBookDetailQty().compareTo(BigDecimal.ZERO) > 0){
				detail.setBookDetailPrice(detail.getBookDetailMoney().divide(detail.getBookDetailQty(), 4, BigDecimal.ROUND_HALF_UP));
			}
			wholesaleBookTotalMoney = wholesaleBookTotalMoney.add(detail.getBookDetailMoney());
		}
		wholesaleBookTotalMoney = wholesaleBookTotalMoney.setScale(2, BigDecimal.ROUND_HALF_UP);
	}
	
	public String getSaleState(){
		String state = AppConstants.WHOLESALE_BOOK_SALE_STATE_FINISH;
		for(int i = 0;i < wholesaleBookDetails.size();i++){
			WholesaleBookDetail detail = wholesaleBookDetails.get(i);
			if (detail.getBookDetailSaleQty() == null) {
				detail.setBookDetailSaleQty(BigDecimal.ZERO);
			}
			if(detail.getBookDetailSaleQty().subtract(detail.getBookDetailQty()).abs().compareTo(BigDecimal.valueOf(0.01)) > 0){
				state = AppConstants.WHOLESALE_BOOK_SALE_STATE_PART;
				break;
			}
		}
		return state;
	}
}
