package com.nhsoft.module.report.model;



import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * WholesaleReturnDetail generated by hbm2java
 */
public class WholesaleReturnDetail implements java.io.Serializable {

	private static final long serialVersionUID = 435239498435901195L;
	private WholesaleReturnDetailId id;
	private Integer itemNum;
	private String returnDetailItemCode;
	private String returnDetailItemName;
	private String returnDetailItemSpec;
	private String returnDetailItemUnit;
	private String returnDetailItemAssistUnit;
	private BigDecimal returnDetailQty;
	private BigDecimal returnDetailAssistQty;
	private BigDecimal returnDetailPresentQty;
	private BigDecimal returnDetailAssistPresentQty;
	private BigDecimal returnDetailPrice;
	private BigDecimal returnDetailMoney;
	private BigDecimal returnDetailCost;
	private Integer returnDetailItemMatrixNum;
	private BigDecimal returnDetailCommission;
	private Date returnDetailProductingDate;
	private String returnDetailLotNumber;
	private String returnDetailMemo;
	private BigDecimal returnDetailInventoryQty;
	private BigDecimal returnDetailAssistInventoryQty;
	private String returnDetailUseUnit;
	private BigDecimal returnDetailUseQty;
	private BigDecimal returnDetailUsePrice;
	private BigDecimal returnDetailUseRate;
	private String returnDetailPeriod;
	private String returnDetailPresentUnit;
	private BigDecimal returnDetailPresentUseQty;
	private Integer supplierNum;
	private BigDecimal returnDetailSalePrice;

	
    public WholesaleReturnDetail() {
    }

    public BigDecimal getReturnDetailSalePrice() {
		return returnDetailSalePrice;
	}

	public void setReturnDetailSalePrice(BigDecimal returnDetailSalePrice) {
		this.returnDetailSalePrice = returnDetailSalePrice;
	}

	public Integer getSupplierNum() {
		return supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public WholesaleReturnDetailId getId() {
		return this.id;
	}

	public void setId(WholesaleReturnDetailId id) {
		this.id = id;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getReturnDetailItemCode() {
		return this.returnDetailItemCode;
	}

	public void setReturnDetailItemCode(String returnDetailItemCode) {
		this.returnDetailItemCode = returnDetailItemCode;
	}

	public String getReturnDetailItemName() {
		return this.returnDetailItemName;
	}

	public void setReturnDetailItemName(String returnDetailItemName) {
		this.returnDetailItemName = returnDetailItemName;
	}

	public String getReturnDetailItemSpec() {
		return this.returnDetailItemSpec;
	}

	public void setReturnDetailItemSpec(String returnDetailItemSpec) {
		this.returnDetailItemSpec = returnDetailItemSpec;
	}

	public String getReturnDetailItemUnit() {
		return this.returnDetailItemUnit;
	}

	public void setReturnDetailItemUnit(String returnDetailItemUnit) {
		this.returnDetailItemUnit = returnDetailItemUnit;
	}

	public String getReturnDetailItemAssistUnit() {
		return this.returnDetailItemAssistUnit;
	}

	public void setReturnDetailItemAssistUnit(String returnDetailItemAssistUnit) {
		this.returnDetailItemAssistUnit = returnDetailItemAssistUnit;
	}

	public BigDecimal getReturnDetailQty() {
		return this.returnDetailQty;
	}

	public void setReturnDetailQty(BigDecimal returnDetailQty) {
		this.returnDetailQty = returnDetailQty;
	}

	public BigDecimal getReturnDetailAssistQty() {
		return this.returnDetailAssistQty;
	}

	public void setReturnDetailAssistQty(BigDecimal returnDetailAssistQty) {
		this.returnDetailAssistQty = returnDetailAssistQty;
	}

	public BigDecimal getReturnDetailPresentQty() {
		return this.returnDetailPresentQty;
	}

	public void setReturnDetailPresentQty(BigDecimal returnDetailPresentQty) {
		this.returnDetailPresentQty = returnDetailPresentQty;
	}

	public BigDecimal getReturnDetailAssistPresentQty() {
		return this.returnDetailAssistPresentQty;
	}

	public void setReturnDetailAssistPresentQty(
			BigDecimal returnDetailAssistPresentQty) {
		this.returnDetailAssistPresentQty = returnDetailAssistPresentQty;
	}

	public BigDecimal getReturnDetailPrice() {
		return this.returnDetailPrice;
	}

	public void setReturnDetailPrice(BigDecimal returnDetailPrice) {
		this.returnDetailPrice = returnDetailPrice;
	}

	public BigDecimal getReturnDetailMoney() {
		return this.returnDetailMoney;
	}

	public void setReturnDetailMoney(BigDecimal returnDetailMoney) {
		this.returnDetailMoney = returnDetailMoney;
	}

	public BigDecimal getReturnDetailCost() {
		return this.returnDetailCost;
	}

	public void setReturnDetailCost(BigDecimal returnDetailCost) {
		this.returnDetailCost = returnDetailCost;
	}

	public Integer getReturnDetailItemMatrixNum() {
		return this.returnDetailItemMatrixNum;
	}

	public void setReturnDetailItemMatrixNum(Integer returnDetailItemMatrixNum) {
		this.returnDetailItemMatrixNum = returnDetailItemMatrixNum;
	}

	public BigDecimal getReturnDetailCommission() {
		return this.returnDetailCommission;
	}

	public void setReturnDetailCommission(BigDecimal returnDetailCommission) {
		this.returnDetailCommission = returnDetailCommission;
	}

	public Date getReturnDetailProductingDate() {
		return this.returnDetailProductingDate;
	}

	public void setReturnDetailProductingDate(Date returnDetailProductingDate) {
		this.returnDetailProductingDate = returnDetailProductingDate;
	}

	public String getReturnDetailLotNumber() {
		return this.returnDetailLotNumber;
	}

	public void setReturnDetailLotNumber(String returnDetailLotNumber) {
		this.returnDetailLotNumber = returnDetailLotNumber;
	}

	public String getReturnDetailMemo() {
		return this.returnDetailMemo;
	}

	public void setReturnDetailMemo(String returnDetailMemo) {
		this.returnDetailMemo = returnDetailMemo;
	}

	public BigDecimal getReturnDetailInventoryQty() {
		return this.returnDetailInventoryQty;
	}

	public void setReturnDetailInventoryQty(BigDecimal returnDetailInventoryQty) {
		this.returnDetailInventoryQty = returnDetailInventoryQty;
	}

	public BigDecimal getReturnDetailAssistInventoryQty() {
		return this.returnDetailAssistInventoryQty;
	}

	public void setReturnDetailAssistInventoryQty(
			BigDecimal returnDetailAssistInventoryQty) {
		this.returnDetailAssistInventoryQty = returnDetailAssistInventoryQty;
	}

	public String getReturnDetailUseUnit() {
		return this.returnDetailUseUnit;
	}

	public void setReturnDetailUseUnit(String returnDetailUseUnit) {
		this.returnDetailUseUnit = returnDetailUseUnit;
	}

	public BigDecimal getReturnDetailUseQty() {
		return this.returnDetailUseQty;
	}

	public void setReturnDetailUseQty(BigDecimal returnDetailUseQty) {
		this.returnDetailUseQty = returnDetailUseQty;
	}

	public BigDecimal getReturnDetailUsePrice() {
		return this.returnDetailUsePrice;
	}

	public void setReturnDetailUsePrice(BigDecimal returnDetailUsePrice) {
		this.returnDetailUsePrice = returnDetailUsePrice;
	}

	public BigDecimal getReturnDetailUseRate() {
		return this.returnDetailUseRate;
	}

	public void setReturnDetailUseRate(BigDecimal returnDetailUseRate) {
		this.returnDetailUseRate = returnDetailUseRate;
	}

	public String getReturnDetailPeriod() {
		return this.returnDetailPeriod;
	}

	public void setReturnDetailPeriod(String returnDetailPeriod) {
		this.returnDetailPeriod = returnDetailPeriod;
	}

	public String getReturnDetailPresentUnit() {
		return returnDetailPresentUnit;
	}

	public void setReturnDetailPresentUnit(String returnDetailPresentUnit) {
		this.returnDetailPresentUnit = returnDetailPresentUnit;
	}

	public BigDecimal getReturnDetailPresentUseQty() {
		return returnDetailPresentUseQty;
	}

	public void setReturnDetailPresentUseQty(BigDecimal returnDetailPresentUseQty) {
		this.returnDetailPresentUseQty = returnDetailPresentUseQty;
	}

	public static List<WholesaleReturnDetail> find(List<WholesaleReturnDetail> wholesaleReturnDetails,
			String wholesaleReturnFid) {
		List<WholesaleReturnDetail> list = new ArrayList<WholesaleReturnDetail>();
		for(int i = 0;i < wholesaleReturnDetails.size();i++){
			WholesaleReturnDetail wholesaleReturnDetail = wholesaleReturnDetails.get(i);
			if(wholesaleReturnDetail.getId().getWholesaleReturnFid().equals(wholesaleReturnFid)){
				list.add(wholesaleReturnDetail);
			}
		}
		return list;
	}

}
