package com.nhsoft.module.report.dto;

import com.nhsoft.module.report.query.State;
import org.apache.commons.lang.StringUtils;
import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 * CardUser generated by hbm2java
 */
public class CardUserDTO implements java.io.Serializable {

	private static final Logger logger = LoggerFactory.getLogger(CardUserDTO.class);
	private static final long serialVersionUID = 6142204157193150794L;
	private Integer cardUserNum;
	private String systemBookCode;
	private String cardUserCustName;
	private Date cardUserBirth;
	private String cardUserCustSex;
	private String cardUserIdCardType;
	private String cardUserIdCardNum;
	private String cardUserPhone;
	private String cardUserAddress;
	private String cardUserEmail;
	private Date cardUserDate;
	private Date cardUserDeadline;
	private String cardUserPassword;
	private Integer cardUserCardType;
	private String cardUserStorage;
	private String cardUserMemo;
	private String cardUserTips;
	private String cardUserFirm;
	private String cardUserPhysicalNum;
	private String cardUserPrintedNum;
	private State state;
	private Integer cardUserEnrollShop;
	private Date cardUserInitTime;
	private Integer cardUserDepositCount;
	private Integer cardUserConsumeCount;
	private Integer cardUserInvoiceCount;
	private Integer cardUserBalanceCount;
	private BigDecimal cardUserTotalCash;
	private BigDecimal cardUserTotalInvoice;
	private String cardUserRefNum;
	private String cardUserRefType;
	private Boolean cardUserLocked;
	private String cardUserOperator;
	private Boolean cardUserFlag;
	private Date cardUserLastEditTime;
	private String cardUserUuid;
	private String cardUserRevoker;
	private Date cardUserRevokeTime;
	private Integer cardUserRevokeShop;
	private CardBalanceDTO cardBalance;
	private Boolean cardUserExceptionFlag;
	private String cardUserExceptionMemo;
	private String cardUserOpenId;
	private Boolean cardUserChangeEnabled;
	private Boolean cardUserBindWeixin;
	private BigDecimal cardUserPoint;
	private Boolean cardUserUpload;
	private String cardUserAlipayNo;


	// 临时属性
	private String cardUserEnrollShopName;
	private BigDecimal cardUserPointBalance;
	private BigDecimal cardUserTempPoint;
	private String revokeShiftBizday;
	private Integer revokeShiftNum;
	private boolean fromApi = false;
	private BigDecimal revokeBalance;
	private BigDecimal pointBalance;
	private String memberCode;
	private String memberId;
	private Boolean onlineCard = false;//是否在线发卡
	private List<String> logs = new ArrayList<String>();
	
	public CardUserDTO() {
	}
	
	public String getCardUserAlipayNo() {
		return cardUserAlipayNo;
	}
	
	public void setCardUserAlipayNo(String cardUserAlipayNo) {
		this.cardUserAlipayNo = cardUserAlipayNo;
	}
	
	public Boolean getOnlineCard() {
		return onlineCard;
	}


	public void setOnlineCard(Boolean onlineCard) {
		this.onlineCard = onlineCard;
	}


	public Boolean getCardUserUpload() {
		return cardUserUpload;
	}


	public void setCardUserUpload(Boolean cardUserUpload) {
		this.cardUserUpload = cardUserUpload;
	}


	public BigDecimal getCardUserPoint() {
		return cardUserPoint;
	}


	public void setCardUserPoint(BigDecimal cardUserPoint) {
		this.cardUserPoint = cardUserPoint;
	}


	public String getMemberCode() {
		return memberCode;
	}

	public Boolean getCardUserBindWeixin() {
		return cardUserBindWeixin;
	}


	public void setCardUserBindWeixin(Boolean cardUserBindWeixin) {
		this.cardUserBindWeixin = cardUserBindWeixin;
	}


	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}


	public String getMemberId() {
		return memberId;
	}


	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}


	public BigDecimal getPointBalance() {
		return pointBalance;
	}


	public void setPointBalance(BigDecimal pointBalance) {
		this.pointBalance = pointBalance;
	}


	public BigDecimal getRevokeBalance() {
		return revokeBalance;
	}


	public void setRevokeBalance(BigDecimal revokeBalance) {
		this.revokeBalance = revokeBalance;
	}


	public String getRevokeShiftBizday() {
		return revokeShiftBizday;
	}

	public void setRevokeShiftBizday(String revokeShiftBizday) {
		this.revokeShiftBizday = revokeShiftBizday;
	}

	public Integer getRevokeShiftNum() {
		return revokeShiftNum;
	}

	public void setRevokeShiftNum(Integer revokeShiftNum) {
		this.revokeShiftNum = revokeShiftNum;
	}

	public boolean isFromApi() {
		return fromApi;
	}

	public void setFromApi(boolean fromApi) {
		this.fromApi = fromApi;
	}

	public Integer getCardUserNum() {
		return this.cardUserNum;
	}

	public void setCardUserNum(Integer cardUserNum) {
		this.cardUserNum = cardUserNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getCardUserCustName() {
		return this.cardUserCustName;
	}

	public void setCardUserCustName(String cardUserCustName) {
		this.cardUserCustName = cardUserCustName;
	}

	public Date getCardUserBirth() {
		return this.cardUserBirth;
	}

	public void setCardUserBirth(Date cardUserBirth) {
		this.cardUserBirth = cardUserBirth;
	}

	public String getCardUserCustSex() {
		return this.cardUserCustSex;
	}

	public void setCardUserCustSex(String cardUserCustSex) {
		this.cardUserCustSex = cardUserCustSex;
	}

	public String getCardUserIdCardType() {
		return this.cardUserIdCardType;
	}

	public void setCardUserIdCardType(String cardUserIdCardType) {
		this.cardUserIdCardType = cardUserIdCardType;
	}

	public String getCardUserIdCardNum() {
		return this.cardUserIdCardNum;
	}

	public void setCardUserIdCardNum(String cardUserIdCardNum) {
		this.cardUserIdCardNum = cardUserIdCardNum;
	}

	public String getCardUserPhone() {
		return this.cardUserPhone;
	}

	public void setCardUserPhone(String cardUserPhone) {
		this.cardUserPhone = cardUserPhone;
	}

	public String getCardUserAddress() {
		return this.cardUserAddress;
	}

	public void setCardUserAddress(String cardUserAddress) {
		this.cardUserAddress = cardUserAddress;
	}

	public String getCardUserEmail() {
		return this.cardUserEmail;
	}

	public void setCardUserEmail(String cardUserEmail) {
		this.cardUserEmail = cardUserEmail;
	}

	public Date getCardUserDate() {
		return this.cardUserDate;
	}

	public void setCardUserDate(Date cardUserDate) {
		this.cardUserDate = cardUserDate;
	}

	public Date getCardUserDeadline() {
		return this.cardUserDeadline;
	}

	public void setCardUserDeadline(Date cardUserDeadline) {
		this.cardUserDeadline = cardUserDeadline;
	}

	public String getCardUserPassword() {
		return this.cardUserPassword;
	}

	public void setCardUserPassword(String cardUserPassword) {
		this.cardUserPassword = cardUserPassword;
	}

	public Integer getCardUserCardType() {
		return this.cardUserCardType;
	}

	public void setCardUserCardType(Integer cardUserCardType) {
		this.cardUserCardType = cardUserCardType;
	}

	public String getCardUserStorage() {
		return this.cardUserStorage;
	}

	public void setCardUserStorage(String cardUserStorage) {
		this.cardUserStorage = cardUserStorage;
	}

	public String getCardUserMemo() {
		return this.cardUserMemo;
	}

	public void setCardUserMemo(String cardUserMemo) {
		this.cardUserMemo = cardUserMemo;
	}

	public String getCardUserTips() {
		return this.cardUserTips;
	}

	public void setCardUserTips(String cardUserTips) {
		this.cardUserTips = cardUserTips;
	}

	public String getCardUserFirm() {
		return this.cardUserFirm;
	}

	public void setCardUserFirm(String cardUserFirm) {
		this.cardUserFirm = cardUserFirm;
	}

	public String getCardUserPhysicalNum() {
		return this.cardUserPhysicalNum;
	}

	public void setCardUserPhysicalNum(String cardUserPhysicalNum) {
		this.cardUserPhysicalNum = cardUserPhysicalNum;
	}

	public String getCardUserPrintedNum() {
		return this.cardUserPrintedNum;
	}

	public void setCardUserPrintedNum(String cardUserPrintedNum) {
		this.cardUserPrintedNum = cardUserPrintedNum;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public Integer getCardUserEnrollShop() {
		return this.cardUserEnrollShop;
	}

	public void setCardUserEnrollShop(Integer cardUserEnrollShop) {
		if(cardUserEnrollShop == null){
			cardUserEnrollShop = 0;
		}
		this.cardUserEnrollShop = cardUserEnrollShop;
	}

	public Date getCardUserInitTime() {
		return this.cardUserInitTime;
	}

	public void setCardUserInitTime(Date cardUserInitTime) {
		this.cardUserInitTime = cardUserInitTime;
	}

	public Integer getCardUserDepositCount() {
		return this.cardUserDepositCount;
	}

	public void setCardUserDepositCount(Integer cardUserDepositCount) {
		this.cardUserDepositCount = cardUserDepositCount;
	}

	public Integer getCardUserConsumeCount() {
		return this.cardUserConsumeCount;
	}

	public void setCardUserConsumeCount(Integer cardUserConsumeCount) {
		this.cardUserConsumeCount = cardUserConsumeCount;
	}

	public Integer getCardUserInvoiceCount() {
		return this.cardUserInvoiceCount;
	}

	public void setCardUserInvoiceCount(Integer cardUserInvoiceCount) {
		this.cardUserInvoiceCount = cardUserInvoiceCount;
	}

	public Integer getCardUserBalanceCount() {
		return this.cardUserBalanceCount;
	}

	public void setCardUserBalanceCount(Integer cardUserBalanceCount) {
		this.cardUserBalanceCount = cardUserBalanceCount;
	}

	public BigDecimal getCardUserTotalCash() {
		return this.cardUserTotalCash;
	}

	public void setCardUserTotalCash(BigDecimal cardUserTotalCash) {
		this.cardUserTotalCash = cardUserTotalCash;
	}

	public BigDecimal getCardUserTotalInvoice() {
		return this.cardUserTotalInvoice;
	}

	public void setCardUserTotalInvoice(BigDecimal cardUserTotalInvoice) {
		this.cardUserTotalInvoice = cardUserTotalInvoice;
	}

	public String getCardUserRefNum() {
		return this.cardUserRefNum;
	}

	public void setCardUserRefNum(String cardUserRefNum) {
		this.cardUserRefNum = cardUserRefNum;
	}

	public String getCardUserRefType() {
		return this.cardUserRefType;
	}

	public void setCardUserRefType(String cardUserRefType) {
		this.cardUserRefType = cardUserRefType;
	}

	public Boolean getCardUserLocked() {
		return this.cardUserLocked;
	}

	public void setCardUserLocked(Boolean cardUserLocked) {
		this.cardUserLocked = cardUserLocked;
	}

	public String getCardUserOperator() {
		return this.cardUserOperator;
	}

	public void setCardUserOperator(String cardUserOperator) {
		this.cardUserOperator = cardUserOperator;
	}

	public Boolean getCardUserFlag() {
		return this.cardUserFlag;
	}

	public void setCardUserFlag(Boolean cardUserFlag) {
		this.cardUserFlag = cardUserFlag;
	}

	public Date getCardUserLastEditTime() {
		return this.cardUserLastEditTime;
	}

	public void setCardUserLastEditTime(Date cardUserLastEditTime) {
		this.cardUserLastEditTime = cardUserLastEditTime;
	}

	public String getCardUserUuid() {
		return this.cardUserUuid;
	}

	public void setCardUserUuid(String cardUserUuid) {
		this.cardUserUuid = cardUserUuid;
	}

	public String getCardUserRevoker() {
		return this.cardUserRevoker;
	}

	public void setCardUserRevoker(String cardUserRevoker) {
		this.cardUserRevoker = cardUserRevoker;
	}

	public Date getCardUserRevokeTime() {
		return this.cardUserRevokeTime;
	}

	public void setCardUserRevokeTime(Date cardUserRevokeTime) {
		this.cardUserRevokeTime = cardUserRevokeTime;
	}

	public Integer getCardUserRevokeShop() {
		return this.cardUserRevokeShop;
	}

	public void setCardUserRevokeShop(Integer cardUserRevokeShop) {
		this.cardUserRevokeShop = cardUserRevokeShop;
	}

	public CardBalanceDTO getCardBalance() {
		return cardBalance;
	}

	public void setCardBalance(CardBalanceDTO cardBalance) {
		this.cardBalance = cardBalance;
	}

	public Boolean getCardUserExceptionFlag() {
		return cardUserExceptionFlag;
	}

	public void setCardUserExceptionFlag(Boolean cardUserExceptionFlag) {
		this.cardUserExceptionFlag = cardUserExceptionFlag;
	}

	public String getCardUserExceptionMemo() {
		return cardUserExceptionMemo;
	}

	public void setCardUserExceptionMemo(String cardUserExceptionMemo) {
		this.cardUserExceptionMemo = cardUserExceptionMemo;
	}

	public String getCardUserEnrollShopName() {
		return cardUserEnrollShopName;
	}

	public void setCardUserEnrollShopName(String cardUserEnrollShopName) {
		this.cardUserEnrollShopName = cardUserEnrollShopName;
	}

	public BigDecimal getCardUserPointBalance() {
		return cardUserPointBalance;
	}

	public void setCardUserPointBalance(BigDecimal cardUserPointBalance) {
		this.cardUserPointBalance = cardUserPointBalance;
	}

	public String getCardUserOpenId() {
		return cardUserOpenId;
	}

	public void setCardUserOpenId(String cardUserOpenId) {
		this.cardUserOpenId = cardUserOpenId;
	}

	public BigDecimal getCardUserTempPoint() {
		return cardUserTempPoint;
	}

	public void setCardUserTempPoint(BigDecimal cardUserTempPoint) {
		this.cardUserTempPoint = cardUserTempPoint;
	}

	public Boolean getCardUserChangeEnabled() {
		return cardUserChangeEnabled;
	}


	public void setCardUserChangeEnabled(Boolean cardUserChangeEnabled) {
		this.cardUserChangeEnabled = cardUserChangeEnabled;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cardUserNum == null) ? 0 : cardUserNum.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CardUserDTO other = (CardUserDTO) obj;
		if (cardUserNum == null) {
			if (other.cardUserNum != null)
				return false;
		} else if (!cardUserNum.equals(other.cardUserNum))
			return false;
		return true;
	}
	
	public String getMemberCacheKey(){
		return "AMA-POS-CARDUSER-" + systemBookCode + "-" + cardUserNum;
	}
	
	public static String getMemberCacheKey(String systemBookCode, Integer cardUserNum){
		return "AMA-POS-CARDUSER-" + systemBookCode + "-" + cardUserNum;
	}
	
	public List<String> getLogs() {
		return logs;
	}


	public void setLogs(List<String> logs) {
		this.logs = logs;
	}


	public static CardUserDTO getCardUser(List<CardUserDTO> cardUsers, Integer cardUserNum) {
		for(CardUserDTO cardUser : cardUsers) {
			if(cardUser.getCardUserNum().equals(cardUserNum)) {
				return cardUser;
			}
		}
		return null;
	}


}
