package com.nhsoft.module.report.dto;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.Date;

/**
 * CardDeposit generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class CardDepositDTO implements java.io.Serializable {

	private static final Logger logger = LoggerFactory.getLogger(CardDepositDTO.class);
	private static final long serialVersionUID = 2765947710410271382L;
	private String depositFid;
	private String systemBookCode;
	private Integer branchNum;
	private Integer shiftTableNum;
	private String shiftTableBizday;
	private Integer depositCustNum;
	private Integer depositCardType;
	private String depositPrintedNum;
	private Integer depositCategory;
	private String depositType;
	private BigDecimal depositBalance;
	private BigDecimal depositCash;
	private BigDecimal depositMoney;
	private BigDecimal depositPoint;
	private BigDecimal depositInvoice;
	private Date depositDate;
	private String depositOperator;
	private Integer depositCount;
	private Integer depositPaymentType;
	private String depositPaymentTypeName;
	private String depositBankName;
	private String depositBillref;
	private String depositMemo;
	private Date depositStartDate;
	private Date depositDeadline;
	private String depositPhysicalNum;
	private String depositCustName;
	private String depositBranchName;
	private Integer depositBalanceDetailNum;
	private Integer accountBankNum;
	private String depositMachine;
	private Boolean depositSettlementFlag;
	private Boolean depositRepealed;
	private Boolean depositNoticeFlag;
	private String depositOpenId;
	private String clientFid;
	private String depositAntiFid;
	private String depositSeller;
	private Date depositSynchDate;
	private String depositSource;


	private CardUserDTO cardUser;
	
	//临时属性
	private String depositCrypt;
	private Boolean fromPos = false;
	private String reSendFid;
	
    public String getReSendFid() {
		return reSendFid;
	}

	public void setReSendFid(String reSendFid) {
		this.reSendFid = reSendFid;
	}

	public Date getDepositSynchDate() {
		return depositSynchDate;
	}

	public void setDepositSynchDate(Date depositSynchDate) {
		this.depositSynchDate = depositSynchDate;
	}

	public Boolean getFromPos() {
		return fromPos;
	}

	public void setFromPos(Boolean fromPos) {
		this.fromPos = fromPos;
	}

	public String getDepositCrypt() {
		return depositCrypt;
	}

	public void setDepositCrypt(String depositCrypt) {
		this.depositCrypt = depositCrypt;
	}

	public CardUserDTO getCardUser() {
		return cardUser;
	}

	public void setCardUser(CardUserDTO cardUser) {
		this.cardUser = cardUser;
	}

	public CardDepositDTO() {
    	setDepositSettlementFlag(false);
	}

    public String getDepositSeller() {
		return depositSeller;
	}

	public void setDepositSeller(String depositSeller) {
		this.depositSeller = depositSeller;
	}

	public String getDepositAntiFid() {
		return depositAntiFid;
	}

	public void setDepositAntiFid(String depositAntiFid) {
		this.depositAntiFid = depositAntiFid;
	}

	public String getClientFid() {
        return clientFid;
    }

    public void setClientFid(String clientFid) {
        this.clientFid = clientFid;
    }
    
	public Boolean getDepositRepealed() {
		return depositRepealed;
	}

	public void setDepositRepealed(Boolean depositRepealed) {
		this.depositRepealed = depositRepealed;
	}

	public String getDepositFid() {
		return this.depositFid;
	}

	public void setDepositFid(String depositFid) {
		this.depositFid = depositFid;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getShiftTableNum() {
		return this.shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public Integer getDepositCustNum() {
		return this.depositCustNum;
	}

	public void setDepositCustNum(Integer depositCustNum) {
		this.depositCustNum = depositCustNum;
	}

	public Integer getDepositCardType() {
		return this.depositCardType;
	}

	public void setDepositCardType(Integer depositCardType) {
		this.depositCardType = depositCardType;
	}

	public String getDepositPrintedNum() {
		return this.depositPrintedNum;
	}

	public void setDepositPrintedNum(String depositPrintedNum) {
		this.depositPrintedNum = depositPrintedNum;
	}

	public Integer getDepositCategory() {
		return this.depositCategory;
	}

	public void setDepositCategory(Integer depositCategory) {
		this.depositCategory = depositCategory;
	}

	public String getDepositType() {
		return this.depositType;
	}

	public void setDepositType(String depositType) {
		this.depositType = depositType;
	}

	public BigDecimal getDepositBalance() {
		return this.depositBalance;
	}

	public void setDepositBalance(BigDecimal depositBalance) {
		this.depositBalance = depositBalance;
	}

	public BigDecimal getDepositCash() {
		return this.depositCash;
	}

	public void setDepositCash(BigDecimal depositCash) {
		this.depositCash = depositCash;
	}

	public BigDecimal getDepositMoney() {
		return this.depositMoney;
	}

	public void setDepositMoney(BigDecimal depositMoney) {
		this.depositMoney = depositMoney;
	}

	public BigDecimal getDepositPoint() {
		return this.depositPoint;
	}

	public void setDepositPoint(BigDecimal depositPoint) {
		this.depositPoint = depositPoint;
	}

	public BigDecimal getDepositInvoice() {
		return this.depositInvoice;
	}

	public void setDepositInvoice(BigDecimal depositInvoice) {
		this.depositInvoice = depositInvoice;
	}

	public Date getDepositDate() {
		return this.depositDate;
	}

	public void setDepositDate(Date depositDate) {
		this.depositDate = depositDate;
	}

	public String getDepositOperator() {
		return this.depositOperator;
	}

	public void setDepositOperator(String depositOperator) {
		this.depositOperator = depositOperator;
	}

	public Integer getDepositCount() {
		return this.depositCount;
	}

	public void setDepositCount(Integer depositCount) {
		this.depositCount = depositCount;
	}

	public Integer getDepositPaymentType() {
		return this.depositPaymentType;
	}

	public void setDepositPaymentType(Integer depositPaymentType) {
		this.depositPaymentType = depositPaymentType;
	}

	public String getDepositPaymentTypeName() {
		return this.depositPaymentTypeName;
	}

	public void setDepositPaymentTypeName(String depositPaymentTypeName) {
		this.depositPaymentTypeName = depositPaymentTypeName;
	}

	public String getDepositBankName() {
		return this.depositBankName;
	}

	public void setDepositBankName(String depositBankName) {
		this.depositBankName = depositBankName;
	}

	public String getDepositBillref() {
		return this.depositBillref;
	}

	public void setDepositBillref(String depositBillref) {
		this.depositBillref = depositBillref;
	}

	public String getDepositMemo() {
		return this.depositMemo;
	}

	public void setDepositMemo(String depositMemo) {
		this.depositMemo = depositMemo;
	}

	public Date getDepositStartDate() {
		return this.depositStartDate;
	}

	public void setDepositStartDate(Date depositStartDate) {
		this.depositStartDate = depositStartDate;
	}

	public Date getDepositDeadline() {
		return this.depositDeadline;
	}

	public void setDepositDeadline(Date depositDeadline) {
		this.depositDeadline = depositDeadline;
	}

	public String getDepositPhysicalNum() {
		return this.depositPhysicalNum;
	}

	public void setDepositPhysicalNum(String depositPhysicalNum) {
		this.depositPhysicalNum = depositPhysicalNum;
	}

	public String getDepositCustName() {
		return this.depositCustName;
	}

	public void setDepositCustName(String depositCustName) {
		this.depositCustName = depositCustName;
	}

	public String getDepositBranchName() {
		return this.depositBranchName;
	}

	public void setDepositBranchName(String depositBranchName) {
		this.depositBranchName = depositBranchName;
	}

	public Integer getDepositBalanceDetailNum() {
		return this.depositBalanceDetailNum;
	}

	public void setDepositBalanceDetailNum(Integer depositBalanceDetailNum) {
		this.depositBalanceDetailNum = depositBalanceDetailNum;
	}

	public Integer getAccountBankNum() {
		return this.accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public String getDepositMachine() {
		return this.depositMachine;
	}

	public void setDepositMachine(String depositMachine) {
		this.depositMachine = depositMachine;
	}

	public Boolean getDepositSettlementFlag() {
		return this.depositSettlementFlag;
	}

	public void setDepositSettlementFlag(Boolean depositSettlementFlag) {
		this.depositSettlementFlag = depositSettlementFlag;
	}

	public Boolean getDepositNoticeFlag() {
		return depositNoticeFlag;
	}

	public void setDepositNoticeFlag(Boolean depositNoticeFlag) {
		this.depositNoticeFlag = depositNoticeFlag;
	}

	public String getDepositOpenId() {
		return depositOpenId;
	}

	public void setDepositOpenId(String depositOpenId) {
		this.depositOpenId = depositOpenId;
	}
	
}
