package com.nhsoft.module.report.dto;



import java.math.BigDecimal;
import java.util.Date;

/**
 * ConsumePoint generated by hbm2java
 */
public class ConsumePointDTO implements java.io.Serializable {

	private static final long serialVersionUID = 2185797937551649402L;
	private String consumePointFid;
	private String systemBookCode;
	private Integer branchNum;
	private Integer shiftTableNum;
	private String shiftTableBizday;
	private Integer consumePointCustNum;
	private String consumePointPrintedNum;
	private String consumePointPhysicalNum;
	private Date consumePointDate;
	private BigDecimal consumePointBalance;
	private BigDecimal consumePointPoint;
	private String consumePointOperator;
	private String consumePointMemo;
	private String consumePointBranchName;
	private String consumePointCustName;
	private Integer consumePointCardType;
	private String consumePointRefBillNo;
	private Integer consumePointItemNum;
	private Integer consumePointStorehouseNum;
	private BigDecimal consumePointAmount;
	private String consumePointItemName;
	private Boolean consumePointSettlementFlag;
	private BigDecimal consumePointCost;

	//临时属性
	private String reSendFid;

	public ConsumePointDTO() {
	}

	public BigDecimal getConsumePointCost() {
		return consumePointCost;
	}

	public void setConsumePointCost(BigDecimal consumePointCost) {
		this.consumePointCost = consumePointCost;
	}

	public Boolean getConsumePointSettlementFlag() {
		return consumePointSettlementFlag;
	}

	public void setConsumePointSettlementFlag(Boolean consumePointSettlementFlag) {
		this.consumePointSettlementFlag = consumePointSettlementFlag;
	}

	public String getReSendFid() {
		return reSendFid;
	}

	public void setReSendFid(String reSendFid) {
		this.reSendFid = reSendFid;
	}

	public String getConsumePointItemName() {
		return consumePointItemName;
	}

	public void setConsumePointItemName(String consumePointItemName) {
		this.consumePointItemName = consumePointItemName;
	}

	public String getConsumePointFid() {
		return this.consumePointFid;
	}

	public void setConsumePointFid(String consumePointFid) {
		this.consumePointFid = consumePointFid;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getShiftTableNum() {
		return this.shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public Integer getConsumePointCustNum() {
		return this.consumePointCustNum;
	}

	public void setConsumePointCustNum(Integer consumePointCustNum) {
		this.consumePointCustNum = consumePointCustNum;
	}

	public String getConsumePointPrintedNum() {
		return this.consumePointPrintedNum;
	}

	public void setConsumePointPrintedNum(String consumePointPrintedNum) {
		this.consumePointPrintedNum = consumePointPrintedNum;
	}

	public String getConsumePointPhysicalNum() {
		return this.consumePointPhysicalNum;
	}

	public void setConsumePointPhysicalNum(String consumePointPhysicalNum) {
		this.consumePointPhysicalNum = consumePointPhysicalNum;
	}

	public Date getConsumePointDate() {
		return this.consumePointDate;
	}

	public void setConsumePointDate(Date consumePointDate) {
		this.consumePointDate = consumePointDate;
	}

	public BigDecimal getConsumePointBalance() {
		return this.consumePointBalance;
	}

	public void setConsumePointBalance(BigDecimal consumePointBalance) {
		this.consumePointBalance = consumePointBalance;
	}

	public BigDecimal getConsumePointPoint() {
		return this.consumePointPoint;
	}

	public void setConsumePointPoint(BigDecimal consumePointPoint) {
		this.consumePointPoint = consumePointPoint;
	}

	public String getConsumePointOperator() {
		return this.consumePointOperator;
	}

	public void setConsumePointOperator(String consumePointOperator) {
		this.consumePointOperator = consumePointOperator;
	}

	public String getConsumePointMemo() {
		return this.consumePointMemo;
	}

	public void setConsumePointMemo(String consumePointMemo) {
		this.consumePointMemo = consumePointMemo;
	}

	public String getConsumePointBranchName() {
		return this.consumePointBranchName;
	}

	public void setConsumePointBranchName(String consumePointBranchName) {
		this.consumePointBranchName = consumePointBranchName;
	}

	public String getConsumePointCustName() {
		return this.consumePointCustName;
	}

	public void setConsumePointCustName(String consumePointCustName) {
		this.consumePointCustName = consumePointCustName;
	}

	public Integer getConsumePointCardType() {
		return this.consumePointCardType;
	}

	public void setConsumePointCardType(Integer consumePointCardType) {
		this.consumePointCardType = consumePointCardType;
	}

	public String getConsumePointRefBillNo() {
		return this.consumePointRefBillNo;
	}

	public void setConsumePointRefBillNo(String consumePointRefBillNo) {
		this.consumePointRefBillNo = consumePointRefBillNo;
	}

	public Integer getConsumePointItemNum() {
		return this.consumePointItemNum;
	}

	public void setConsumePointItemNum(Integer consumePointItemNum) {
		this.consumePointItemNum = consumePointItemNum;
	}

	public Integer getConsumePointStorehouseNum() {
		return this.consumePointStorehouseNum;
	}

	public void setConsumePointStorehouseNum(Integer consumePointStorehouseNum) {
		this.consumePointStorehouseNum = consumePointStorehouseNum;
	}

	public BigDecimal getConsumePointAmount() {
		return this.consumePointAmount;
	}

	public void setConsumePointAmount(BigDecimal consumePointAmount) {
		this.consumePointAmount = consumePointAmount;
	}

}
