package com.nhsoft.module.report.dto;

// Generated 2016-6-20 16:34:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ShiftTablePayment generated by hbm2java
 */
public class ShiftTablePaymentDTO implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8652179490091352563L;

	

	private String systemBookCode;
	private int branchNum;
	private int shiftTableNum;
	private String shiftTableBizday;
	private int shiftTablePaymentNum;
	private String shiftTablePaymentType;
	private BigDecimal shiftTablePaymentMoney;
	private Boolean shiftTablePaymentSyncFlag;

	public ShiftTablePaymentDTO() {
	}

	public String getSystemBookCode() {
		return systemBookCode;
	}

	public int getBranchNum() {
		return branchNum;
	}

	public int getShiftTableNum() {
		return shiftTableNum;
	}

	public String getShiftTableBizday() {
		return shiftTableBizday;
	}

	public int getShiftTablePaymentNum() {
		return shiftTablePaymentNum;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public void setBranchNum(int branchNum) {
		this.branchNum = branchNum;
	}

	public void setShiftTableNum(int shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public void setShiftTablePaymentNum(int shiftTablePaymentNum) {
		this.shiftTablePaymentNum = shiftTablePaymentNum;
	}

	public String getShiftTablePaymentType() {
		return this.shiftTablePaymentType;
	}

	public void setShiftTablePaymentType(String shiftTablePaymentType) {
		this.shiftTablePaymentType = shiftTablePaymentType;
	}

	public BigDecimal getShiftTablePaymentMoney() {
		return this.shiftTablePaymentMoney;
	}

	public void setShiftTablePaymentMoney(BigDecimal shiftTablePaymentMoney) {
		this.shiftTablePaymentMoney = shiftTablePaymentMoney;
	}

	public Boolean getShiftTablePaymentSyncFlag() {
		return this.shiftTablePaymentSyncFlag;
	}

	public void setShiftTablePaymentSyncFlag(Boolean shiftTablePaymentSyncFlag) {
		this.shiftTablePaymentSyncFlag = shiftTablePaymentSyncFlag;
	}

}
