package com.nhsoft.module.report.dto;

// Generated 2017-3-20 15:17:23 by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;

/**
 * SynchCheckData generated by hbm2java
 */
public class SynchCheckDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8886565979426996021L;
	private String systemBookCode;
	private int branchNum;
	private String shiftTableBizday;
	private Integer shiftTableNum;
	private String terminalId;
	private String synchType;
	private Date synchDate;
	private String synchMemo;

	public SynchCheckDTO() {
	}
	
	public SynchCheckDTO(String systemBookCode, Integer branchNum, String shiftTableBizday,  
			Integer shiftTableNum, String terminalId, String synchType) {
		this.systemBookCode = systemBookCode;
		this.branchNum = branchNum;
		this.shiftTableBizday = shiftTableBizday;
		this.shiftTableNum = shiftTableNum;
		this.terminalId = terminalId;
		this.synchType = synchType;
		this.synchDate = Calendar.getInstance().getTime();
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public int getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(int branchNum) {
		this.branchNum = branchNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}

	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}

	public Integer getShiftTableNum() {
		return this.shiftTableNum;
	}

	public void setShiftTableNum(Integer shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	public String getSynchType() {
		return this.synchType;
	}

	public void setSynchType(String synchType) {
		this.synchType = synchType;
	}

	public Date getSynchDate() {
		return this.synchDate;
	}

	public void setSynchDate(Date synchDate) {
		this.synchDate = synchDate;
	}

	public String getSynchMemo() {
		return this.synchMemo;
	}

	public void setSynchMemo(String synchMemo) {
		this.synchMemo = synchMemo;
	}

}
