package com.nhsoft.report.model;



import java.math.BigDecimal;
import java.util.Date;

/**
 * MarketActionDetail generated by hbm2java
 */
public class MarketActionDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3761608322141877471L;
	private MarketActionDetailId id;
	private Integer marketActionDetailAmount;
	private Date marketActionDetailDate;
	private String marketActionDetailTypeCode;
	private String marketActionDetailTypeName;
	private String marketActionDetailBranch;
	private BigDecimal marketActionDetailValue;
	private Integer marketActionDetailDay;//有效天数
	private Boolean marketActionDetailSelfBranch;
	private Date marketActionDetailEffectiveDate;//生效日期
	private Boolean marketActionDetailAutoValue;
	private Integer marketActionDetailValueMin;
	private Integer marketActionDetailValueMax;
	private BigDecimal marketActionDetailGrade;//阶梯起赠金额
	private BigDecimal marketActionDetailMaxAmount;
	
	//临时属性
	private BigDecimal marketActionDetailSendAmount;//券已发放数量
	private BigDecimal marketActionDetailSendOpenIdAmount;//该openId券已发放数量
	
	public MarketActionDetail() {
	}

	public BigDecimal getMarketActionDetailSendOpenIdAmount() {
		return marketActionDetailSendOpenIdAmount;
	}

	public void setMarketActionDetailSendOpenIdAmount(BigDecimal marketActionDetailSendOpenIdAmount) {
		this.marketActionDetailSendOpenIdAmount = marketActionDetailSendOpenIdAmount;
	}

	public BigDecimal getMarketActionDetailSendAmount() {
		return marketActionDetailSendAmount;
	}

	public void setMarketActionDetailSendAmount(BigDecimal marketActionDetailSendAmount) {
		this.marketActionDetailSendAmount = marketActionDetailSendAmount;
	}

	public BigDecimal getMarketActionDetailMaxAmount() {
		return marketActionDetailMaxAmount;
	}

	public void setMarketActionDetailMaxAmount(BigDecimal marketActionDetailMaxAmount) {
		this.marketActionDetailMaxAmount = marketActionDetailMaxAmount;
	}

	public MarketActionDetailId getId() {
		return id;
	}

	public void setId(MarketActionDetailId id) {
		this.id = id;
	}

	public Integer getMarketActionDetailAmount() {
		return this.marketActionDetailAmount;
	}

	public void setMarketActionDetailAmount(Integer marketActionDetailAmount) {
		this.marketActionDetailAmount = marketActionDetailAmount;
	}

	public Date getMarketActionDetailDate() {
		return this.marketActionDetailDate;
	}

	public void setMarketActionDetailDate(Date marketActionDetailDate) {
		this.marketActionDetailDate = marketActionDetailDate;
	}

	public String getMarketActionDetailTypeCode() {
		return this.marketActionDetailTypeCode;
	}

	public void setMarketActionDetailTypeCode(String marketActionDetailTypeCode) {
		this.marketActionDetailTypeCode = marketActionDetailTypeCode;
	}

	public String getMarketActionDetailTypeName() {
		return this.marketActionDetailTypeName;
	}

	public void setMarketActionDetailTypeName(String marketActionDetailTypeName) {
		this.marketActionDetailTypeName = marketActionDetailTypeName;
	}

	public String getMarketActionDetailBranch() {
		return this.marketActionDetailBranch;
	}

	public void setMarketActionDetailBranch(String marketActionDetailBranch) {
		this.marketActionDetailBranch = marketActionDetailBranch;
	}

	public BigDecimal getMarketActionDetailValue() {
		return marketActionDetailValue;
	}

	public void setMarketActionDetailValue(BigDecimal marketActionDetailValue) {
		this.marketActionDetailValue = marketActionDetailValue;
	}

	public Integer getMarketActionDetailDay() {
		return marketActionDetailDay;
	}

	public void setMarketActionDetailDay(Integer marketActionDetailDay) {
		this.marketActionDetailDay = marketActionDetailDay;
	}

	public Boolean getMarketActionDetailSelfBranch() {
		return marketActionDetailSelfBranch;
	}

	public void setMarketActionDetailSelfBranch(Boolean marketActionDetailSelfBranch) {
		this.marketActionDetailSelfBranch = marketActionDetailSelfBranch;
	}

	public Date getMarketActionDetailEffectiveDate() {
		return marketActionDetailEffectiveDate;
	}

	public void setMarketActionDetailEffectiveDate(Date marketActionDetailEffectiveDate) {
		this.marketActionDetailEffectiveDate = marketActionDetailEffectiveDate;
	}

	public Boolean getMarketActionDetailAutoValue() {
		return marketActionDetailAutoValue;
	}

	public void setMarketActionDetailAutoValue(Boolean marketActionDetailAutoValue) {
		this.marketActionDetailAutoValue = marketActionDetailAutoValue;
	}

	public Integer getMarketActionDetailValueMin() {
		return marketActionDetailValueMin;
	}

	public void setMarketActionDetailValueMin(Integer marketActionDetailValueMin) {
		this.marketActionDetailValueMin = marketActionDetailValueMin;
	}

	public Integer getMarketActionDetailValueMax() {
		return marketActionDetailValueMax;
	}

	public void setMarketActionDetailValueMax(Integer marketActionDetailValueMax) {
		this.marketActionDetailValueMax = marketActionDetailValueMax;
	}

	public BigDecimal getMarketActionDetailGrade() {
		return marketActionDetailGrade;
	}

	public void setMarketActionDetailGrade(BigDecimal marketActionDetailGrade) {
		this.marketActionDetailGrade = marketActionDetailGrade;
	}

}
