package com.nhsoft.report.model;



import com.nhsoft.report.dto.OrderTraceSearch;
import com.nhsoft.report.shared.State;
import com.nhsoft.report.util.AppConstants;
import org.apache.commons.lang3.StringUtils;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * OnlineOrder generated by hbm2java
 */
public class OnlineOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5419742120898702275L;
	private String onlineOrderFid;
	private Integer storehouseNum;
	private String systemBookCode;
	private Integer branchNum;
	private String onlineOrderNo;
	private String onlineOrderClientNick;
	private String onlineOrderClientName;
	private String onlineOrderPhone;
	private String onlineOrderCity;
	private String onlineOrderAddress;
	private String onlineOrderZip;
	private String onlineOrderMemo;
	private State state;
	private BigDecimal onlineOrderTotalMoney;
	private Integer onlineOrderTotalCount;
	private BigDecimal onlineOrderPostFee;
	private String onlineOrderSource;
	private String onlineOrderPaymentType;
	private String onlineOrderPaymentNo;
	private BigDecimal onlineOrderPaymentMoney;
	private String onlineOrderDeliver;
	private String onlineOrderDeliverNo;
	private Integer onlineOrderPrintCount;
	private String onlineOrderState;
	private String onlineOrderDistrict;
	private String onlineOrderPickupAddress;
	private Boolean onlineOrderSystemSynch;
	private String onlineOrderBuyerMessage;
	private Date onlineOrderLastEditTime;
	private String onlineOrderOpenId;
	private Integer onlineOrderCardNum;
	private String onlineOrderPrintedNum;
	private String onlineOrderCardName;
	private BigDecimal onlineOrderPoint;
	private BigDecimal onlineOrderCouponTotalMoney;
	private BigDecimal onlineOrderCouponPaymentMoney;
	private Integer onlineOrderCardType;
	private String onlineTeamFid; //关联团购单号
	private Integer onlineOrderType;
	private String onlineOrderClientUrl;//头像
	private Boolean onlineOrderHeadFlag; 
	private Date onlineOrderDeadline;
	private String onlineOrderLabel;
	private BigDecimal onlineOrderOtherDiscount;//平台优惠金额
	private BigDecimal onlineOrderSelfDiscount;//商家优惠金额
	private String onlineOrderAllowBranchNums;//允许提货门店
	private String onlineOrderViewNo; //第三方平台C端界面显示的订单号
	private BigDecimal onlineOrderRealIncome;//商户实收金额
	
	private List<OnlineOrderDetail> onlineOrderDetails = new ArrayList<OnlineOrderDetail>(0);
	private List<OnlineOrderFlow> onlineOrderFlows = new ArrayList<OnlineOrderFlow>(0);

	// 临时属性
	private Date onlineOrderPaymentDate;
	private Date onlineOrderSendDate;
	private Date onlineOrderReceiveDate;
	private Date onlineOrderCancelDate;
	private OrderTraceSearch orderTraceSearch;
	private AppUser appUser;
	private Integer cardUserNum; //是否会员卡支付标记
	private OnlineTeam onlineTeam;//是否团购标记
	private Boolean sendMessage = true; //是否留言提醒
	private Boolean isNewGroup = false; //是否新版拼团
	private Integer fetchShopId;//自提门店编号 仅有赞订单使用
	private WeixinPosItem weixinPosItem;
	private Boolean ignoreError = false;
	private Boolean updateDetail = false;
	private Boolean newOrder = true;//是否新订单
	private String youzanFetchCode;

	
	public OnlineOrder() {
	}
	
	public BigDecimal getOnlineOrderRealIncome() {
		return onlineOrderRealIncome;
	}
	
	public void setOnlineOrderRealIncome(BigDecimal onlineOrderRealIncome) {
		this.onlineOrderRealIncome = onlineOrderRealIncome;
	}
	
	public String getYouzanFetchCode() {
		return youzanFetchCode;
	}
	
	public void setYouzanFetchCode(String youzanFetchCode) {
		this.youzanFetchCode = youzanFetchCode;
	}
	
	public String getOnlineOrderViewNo() {
		return onlineOrderViewNo;
	}
	
	public void setOnlineOrderViewNo(String onlineOrderViewNo) {
		this.onlineOrderViewNo = onlineOrderViewNo;
	}
	
	public String getOnlineOrderAllowBranchNums() {
		return onlineOrderAllowBranchNums;
	}
	
	public void setOnlineOrderAllowBranchNums(String onlineOrderAllowBranchNums) {
		this.onlineOrderAllowBranchNums = onlineOrderAllowBranchNums;
	}
	
	public BigDecimal getOnlineOrderOtherDiscount() {
		return onlineOrderOtherDiscount;
	}

	public void setOnlineOrderOtherDiscount(BigDecimal onlineOrderOtherDiscount) {
		this.onlineOrderOtherDiscount = onlineOrderOtherDiscount;
	}

	public BigDecimal getOnlineOrderSelfDiscount() {
		return onlineOrderSelfDiscount;
	}

	public void setOnlineOrderSelfDiscount(BigDecimal onlineOrderSelfDiscount) {
		this.onlineOrderSelfDiscount = onlineOrderSelfDiscount;
	}

	public Boolean getNewOrder() {
		return newOrder;
	}

	public void setNewOrder(Boolean newOrder) {
		this.newOrder = newOrder;
	}

	public Boolean getUpdateDetail() {
		return updateDetail;
	}

	public void setUpdateDetail(Boolean updateDetail) {
		this.updateDetail = updateDetail;
	}

	public Boolean getIgnoreError() {
		return ignoreError;
	}

	public void setIgnoreError(Boolean ignoreError) {
		this.ignoreError = ignoreError;
	}

	public String getOnlineOrderLabel() {
		return onlineOrderLabel;
	}

	public void setOnlineOrderLabel(String onlineOrderLabel) {
		this.onlineOrderLabel = onlineOrderLabel;
	}

	public Date getOnlineOrderSendDate() {
		return onlineOrderSendDate;
	}

	public void setOnlineOrderSendDate(Date onlineOrderSendDate) {
		this.onlineOrderSendDate = onlineOrderSendDate;
	}

	public Date getOnlineOrderReceiveDate() {
		return onlineOrderReceiveDate;
	}

	public void setOnlineOrderReceiveDate(Date onlineOrderReceiveDate) {
		this.onlineOrderReceiveDate = onlineOrderReceiveDate;
	}

	public Date getOnlineOrderCancelDate() {
		return onlineOrderCancelDate;
	}

	public void setOnlineOrderCancelDate(Date onlineOrderCancelDate) {
		this.onlineOrderCancelDate = onlineOrderCancelDate;
	}

	public WeixinPosItem getWeixinPosItem() {
		return weixinPosItem;
	}

	public void setWeixinPosItem(WeixinPosItem weixinPosItem) {
		this.weixinPosItem = weixinPosItem;
	}

	public Date getOnlineOrderDeadline() {
		return onlineOrderDeadline;
	}

	public void setOnlineOrderDeadline(Date onlineOrderDeadline) {
		this.onlineOrderDeadline = onlineOrderDeadline;
	}

	public Integer getFetchShopId() {
		return fetchShopId;
	}

	public void setFetchShopId(Integer fetchShopId) {
		this.fetchShopId = fetchShopId;
	}

	public Boolean getIsNewGroup() {
		return isNewGroup;
	}

	public void setIsNewGroup(Boolean isNewGroup) {
		this.isNewGroup = isNewGroup;
	}

	public Boolean getSendMessage() {
		return sendMessage;
	}

	public void setSendMessage(Boolean sendMessage) {
		this.sendMessage = sendMessage;
	}

	public Boolean getOnlineOrderHeadFlag() {
		return onlineOrderHeadFlag;
	}

	public void setOnlineOrderHeadFlag(Boolean onlineOrderHeadFlag) {
		this.onlineOrderHeadFlag = onlineOrderHeadFlag;
	}

	public Integer getOnlineOrderType() {
		return onlineOrderType;
	}

	public void setOnlineOrderType(Integer onlineOrderType) {
		this.onlineOrderType = onlineOrderType;
	}

	public String getOnlineOrderClientUrl() {
		return onlineOrderClientUrl;
	}

	public void setOnlineOrderClientUrl(String onlineOrderClientUrl) {
		this.onlineOrderClientUrl = onlineOrderClientUrl;
	}

	public OnlineTeam getOnlineTeam() {
		return onlineTeam;
	}

	public void setOnlineTeam(OnlineTeam onlineTeam) {
		this.onlineTeam = onlineTeam;
	}

	public String getOnlineTeamFid() {
		return onlineTeamFid;
	}

	public void setOnlineTeamFid(String onlineTeamFid) {
		this.onlineTeamFid = onlineTeamFid;
	}

	public Integer getOnlineOrderCardType() {
		return onlineOrderCardType;
	}

	public void setOnlineOrderCardType(Integer onlineOrderCardType) {
		this.onlineOrderCardType = onlineOrderCardType;
	}

	public Integer getOnlineOrderCardNum() {
		return onlineOrderCardNum;
	}

	public void setOnlineOrderCardNum(Integer onlineOrderCardNum) {
		this.onlineOrderCardNum = onlineOrderCardNum;
	}

	public String getOnlineOrderPrintedNum() {
		return onlineOrderPrintedNum;
	}

	public void setOnlineOrderPrintedNum(String onlineOrderPrintedNum) {
		this.onlineOrderPrintedNum = onlineOrderPrintedNum;
	}

	public String getOnlineOrderCardName() {
		return onlineOrderCardName;
	}

	public void setOnlineOrderCardName(String onlineOrderCardName) {
		this.onlineOrderCardName = onlineOrderCardName;
	}

	public BigDecimal getOnlineOrderPoint() {
		return onlineOrderPoint;
	}

	public void setOnlineOrderPoint(BigDecimal onlineOrderPoint) {
		this.onlineOrderPoint = onlineOrderPoint;
	}

	public BigDecimal getOnlineOrderCouponTotalMoney() {
		return onlineOrderCouponTotalMoney;
	}

	public void setOnlineOrderCouponTotalMoney(BigDecimal onlineOrderCouponTotalMoney) {
		this.onlineOrderCouponTotalMoney = onlineOrderCouponTotalMoney;
	}

	public BigDecimal getOnlineOrderCouponPaymentMoney() {
		return onlineOrderCouponPaymentMoney;
	}

	public void setOnlineOrderCouponPaymentMoney(BigDecimal onlineOrderCouponPaymentMoney) {
		this.onlineOrderCouponPaymentMoney = onlineOrderCouponPaymentMoney;
	}

	public Integer getCardUserNum() {
		return cardUserNum;
	}

	public void setCardUserNum(Integer cardUserNum) {
		this.cardUserNum = cardUserNum;
	}

	public String getOnlineOrderOpenId() {
		return onlineOrderOpenId;
	}

	public void setOnlineOrderOpenId(String onlineOrderOpenId) {
		this.onlineOrderOpenId = onlineOrderOpenId;
	}

	public String getOnlineOrderFid() {
		return this.onlineOrderFid;
	}

	public void setOnlineOrderFid(String onlineOrderFid) {
		this.onlineOrderFid = onlineOrderFid;
	}

	public Integer getStorehouseNum() {
		return this.storehouseNum;
	}

	public void setStorehouseNum(Integer storehouseNum) {
		this.storehouseNum = storehouseNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getOnlineOrderNo() {
		return this.onlineOrderNo;
	}

	public void setOnlineOrderNo(String onlineOrderNo) {
		this.onlineOrderNo = onlineOrderNo;
	}

	public String getOnlineOrderClientNick() {
		return this.onlineOrderClientNick;
	}

	public void setOnlineOrderClientNick(String onlineOrderClientNick) {
		this.onlineOrderClientNick = onlineOrderClientNick;
	}

	public String getOnlineOrderClientName() {
		return this.onlineOrderClientName;
	}

	public void setOnlineOrderClientName(String onlineOrderClientName) {
		this.onlineOrderClientName = onlineOrderClientName;
	}

	public String getOnlineOrderPhone() {
		return this.onlineOrderPhone;
	}

	public void setOnlineOrderPhone(String onlineOrderPhone) {
		this.onlineOrderPhone = onlineOrderPhone;
	}

	public String getOnlineOrderCity() {
		return this.onlineOrderCity;
	}

	public void setOnlineOrderCity(String onlineOrderCity) {
		this.onlineOrderCity = onlineOrderCity;
	}

	public String getOnlineOrderAddress() {
		return this.onlineOrderAddress;
	}

	public void setOnlineOrderAddress(String onlineOrderAddress) {
		this.onlineOrderAddress = onlineOrderAddress;
	}

	public String getOnlineOrderZip() {
		return this.onlineOrderZip;
	}

	public void setOnlineOrderZip(String onlineOrderZip) {
		this.onlineOrderZip = onlineOrderZip;
	}

	public String getOnlineOrderMemo() {
		return this.onlineOrderMemo;
	}

	public void setOnlineOrderMemo(String onlineOrderMemo) {
		this.onlineOrderMemo = onlineOrderMemo;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public BigDecimal getOnlineOrderTotalMoney() {
		return this.onlineOrderTotalMoney;
	}

	public void setOnlineOrderTotalMoney(BigDecimal onlineOrderTotalMoney) {
		this.onlineOrderTotalMoney = onlineOrderTotalMoney;
	}

	public Integer getOnlineOrderTotalCount() {
		return this.onlineOrderTotalCount;
	}

	public void setOnlineOrderTotalCount(Integer onlineOrderTotalCount) {
		this.onlineOrderTotalCount = onlineOrderTotalCount;
	}

	public BigDecimal getOnlineOrderPostFee() {
		return this.onlineOrderPostFee;
	}

	public void setOnlineOrderPostFee(BigDecimal onlineOrderPostFee) {
		this.onlineOrderPostFee = onlineOrderPostFee;
	}

	public String getOnlineOrderSource() {
		return this.onlineOrderSource;
	}

	public void setOnlineOrderSource(String onlineOrderSource) {
		this.onlineOrderSource = onlineOrderSource;
	}

	public String getOnlineOrderPaymentType() {
		return this.onlineOrderPaymentType;
	}

	public void setOnlineOrderPaymentType(String onlineOrderPaymentType) {
		this.onlineOrderPaymentType = onlineOrderPaymentType;
	}

	public String getOnlineOrderPaymentNo() {
		return this.onlineOrderPaymentNo;
	}

	public void setOnlineOrderPaymentNo(String onlineOrderPaymentNo) {
		this.onlineOrderPaymentNo = onlineOrderPaymentNo;
	}

	public BigDecimal getOnlineOrderPaymentMoney() {
		return this.onlineOrderPaymentMoney;
	}

	public void setOnlineOrderPaymentMoney(BigDecimal onlineOrderPaymentMoney) {
		this.onlineOrderPaymentMoney = onlineOrderPaymentMoney;
	}

	public String getOnlineOrderDeliver() {
		return this.onlineOrderDeliver;
	}

	public void setOnlineOrderDeliver(String onlineOrderDeliver) {
		this.onlineOrderDeliver = onlineOrderDeliver;
	}

	public String getOnlineOrderDeliverNo() {
		return this.onlineOrderDeliverNo;
	}

	public void setOnlineOrderDeliverNo(String onlineOrderDeliverNo) {
		this.onlineOrderDeliverNo = onlineOrderDeliverNo;
	}

	public Integer getOnlineOrderPrintCount() {
		return this.onlineOrderPrintCount;
	}

	public void setOnlineOrderPrintCount(Integer onlineOrderPrintCount) {
		this.onlineOrderPrintCount = onlineOrderPrintCount;
	}

	public List<OnlineOrderDetail> getOnlineOrderDetails() {
		return onlineOrderDetails;
	}

	public void setOnlineOrderDetails(List<OnlineOrderDetail> onlineOrderDetails) {
		this.onlineOrderDetails = onlineOrderDetails;
	}

	public List<OnlineOrderFlow> getOnlineOrderFlows() {
		return onlineOrderFlows;
	}

	public void setOnlineOrderFlows(List<OnlineOrderFlow> onlineOrderFlows) {
		this.onlineOrderFlows = onlineOrderFlows;
	}

	public Date getOnlineOrderPaymentDate() {
		return onlineOrderPaymentDate;
	}

	public void setOnlineOrderPaymentDate(Date onlineOrderPaymentDate) {
		this.onlineOrderPaymentDate = onlineOrderPaymentDate;
	}

	public OrderTraceSearch getOrderTraceSearch() {
		return orderTraceSearch;
	}

	public void setOrderTraceSearch(OrderTraceSearch orderTraceSearch) {
		this.orderTraceSearch = orderTraceSearch;
	}

	public String getOnlineOrderState() {
		return onlineOrderState;
	}

	public void setOnlineOrderState(String onlineOrderState) {
		this.onlineOrderState = onlineOrderState;
	}

	public String getOnlineOrderDistrict() {
		return onlineOrderDistrict;
	}

	public void setOnlineOrderDistrict(String onlineOrderDistrict) {
		this.onlineOrderDistrict = onlineOrderDistrict;
	}

	public AppUser getAppUser() {
		return appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	public String getOnlineOrderPickupAddress() {
		return onlineOrderPickupAddress;
	}

	public void setOnlineOrderPickupAddress(String onlineOrderPickupAddress) {
		this.onlineOrderPickupAddress = onlineOrderPickupAddress;
	}

	public Boolean getOnlineOrderSystemSynch() {
		return onlineOrderSystemSynch;
	}

	public void setOnlineOrderSystemSynch(Boolean onlineOrderSystemSynch) {
		this.onlineOrderSystemSynch = onlineOrderSystemSynch;
	}

	public String getOnlineOrderBuyerMessage() {
		return onlineOrderBuyerMessage;
	}

	public void setOnlineOrderBuyerMessage(String onlineOrderBuyerMessage) {
		this.onlineOrderBuyerMessage = onlineOrderBuyerMessage;
	}

	public Date getOnlineOrderLastEditTime() {
		return onlineOrderLastEditTime;
	}

	public void setOnlineOrderLastEditTime(Date onlineOrderLastEditTime) {
		this.onlineOrderLastEditTime = onlineOrderLastEditTime;
	}

	public OnlineOrderFlow createOnlineOrderFlow(Date date, String flowItem) {
		Integer maxNum = 0;
		for (int i = 0; i < onlineOrderFlows.size(); i++) {
			OnlineOrderFlow onlineOrderFlow = onlineOrderFlows.get(i);
			if (onlineOrderFlow.getId().getOnlineOrderFlowNum() > maxNum) {
				maxNum = onlineOrderFlow.getId().getOnlineOrderFlowNum();
			}
		}

		OnlineOrderFlow onlineOrderFlow = new OnlineOrderFlow();
		OnlineOrderFlowId onlineOrderFlowId = new OnlineOrderFlowId(onlineOrderFid, maxNum + 1);
		onlineOrderFlow.setId(onlineOrderFlowId);
		onlineOrderFlow.setOnlineOrderFlowTime(date);
		onlineOrderFlow.setOnlineOrderFlowItem(flowItem);
		if (appUser == null) {
			onlineOrderFlow.setOnlineOrderFlowOperator("");
		} else {
			onlineOrderFlow.setOnlineOrderFlowOperator(appUser.getAppUserName());
		}
		onlineOrderFlows.add(onlineOrderFlow);
		return onlineOrderFlow;
	}

	public OnlineOrderFlow getOnlineOrderFlow(String flowItem) {
		for (int i = 0; i < onlineOrderFlows.size(); i++) {
			OnlineOrderFlow onlineOrderFlow = onlineOrderFlows.get(i);
			if (onlineOrderFlow.getOnlineOrderFlowItem().equals(flowItem)) {
				return onlineOrderFlow;
			}
		}
		return null;
	}
	
	public void recalMoney(){
		onlineOrderPaymentMoney = BigDecimal.ZERO;
		onlineOrderTotalMoney = BigDecimal.ZERO;
		BigDecimal discount = BigDecimal.ZERO;
		for (int i = 0; i < onlineOrderDetails.size(); i++) {
			OnlineOrderDetail onlineOrderDetail = onlineOrderDetails.get(i);
			
			if(onlineOrderDetail.getOnlineOrderDetailStateCode() == AppConstants.POS_ORDER_DETAIL_STATE_REMOVE){
				continue;
			}
			if(StringUtils.isNotEmpty(onlineOrderDetail.getOnlineOrderDetailTicketUuid())){
				continue;
			}
			if(onlineOrderDetail.getOnlineOrderDetailDiscountMoney() == null){
				onlineOrderDetail.setOnlineOrderDetailDiscountMoney(BigDecimal.ZERO);
			}
			if(onlineOrderDetail.getOnlineOrderDetailUsePrice() != null && onlineOrderDetail.getOnlineOrderDetailUseQty() != null){
				onlineOrderTotalMoney = onlineOrderTotalMoney.add(onlineOrderDetail.getOnlineOrderDetailUsePrice()
						.multiply(onlineOrderDetail.getOnlineOrderDetailUseQty()).setScale(2, BigDecimal.ROUND_HALF_UP));
			} else {
				onlineOrderTotalMoney = onlineOrderTotalMoney.add(onlineOrderDetail.getOnlineOrderDetailPrice()
						.multiply(onlineOrderDetail.getOnlineOrderDetailQty()).setScale(2, BigDecimal.ROUND_HALF_UP));

			}
			if(onlineOrderDetail.getOnlineOrderDetailDiscountMoney() == null){
				onlineOrderDetail.setOnlineOrderDetailDiscountMoney(BigDecimal.ZERO);
				
			}
			discount = discount.add(onlineOrderDetail.getOnlineOrderDetailDiscountMoney());
		}
		if(onlineOrderPostFee == null){
			onlineOrderPostFee = BigDecimal.ZERO;
		}
		if(onlineOrderCouponTotalMoney == null){
			onlineOrderCouponTotalMoney = BigDecimal.ZERO;
		}
		onlineOrderPaymentMoney = onlineOrderTotalMoney.subtract(discount).subtract(onlineOrderCouponTotalMoney == null?BigDecimal.ZERO:onlineOrderCouponTotalMoney);;
		onlineOrderPaymentMoney = onlineOrderPaymentMoney.add(onlineOrderPostFee);	
	}
	
	public BigDecimal calPaymentMoney(){
		BigDecimal paymentMoney = BigDecimal.ZERO;
		for (int i = 0; i < onlineOrderDetails.size(); i++) {
			OnlineOrderDetail onlineOrderDetail = onlineOrderDetails.get(i);
			
			if(onlineOrderDetail.getOnlineOrderDetailStateCode() == AppConstants.POS_ORDER_DETAIL_STATE_REMOVE){
				continue;
			}
			if(StringUtils.isNotEmpty(onlineOrderDetail.getOnlineOrderDetailTicketUuid())){
				continue;
			}
			
			if(onlineOrderDetail.getOnlineOrderDetailUsePrice() != null && onlineOrderDetail.getOnlineOrderDetailUseQty() != null){
				paymentMoney = paymentMoney.add(onlineOrderDetail.getOnlineOrderDetailUsePrice()
						.multiply(onlineOrderDetail.getOnlineOrderDetailUseQty()).setScale(2, BigDecimal.ROUND_HALF_UP));
			} else {
				paymentMoney = paymentMoney.add(onlineOrderDetail.getOnlineOrderDetailPrice()
						.multiply(onlineOrderDetail.getOnlineOrderDetailQty()).setScale(2, BigDecimal.ROUND_HALF_UP));

			}
			if(onlineOrderDetail.getOnlineOrderDetailDiscountMoney() == null){
				onlineOrderDetail.setOnlineOrderDetailDiscountMoney(BigDecimal.ZERO);
				
			}
			paymentMoney = paymentMoney.subtract(onlineOrderDetail.getOnlineOrderDetailDiscountMoney());
		}
		if(onlineOrderPostFee == null){
			onlineOrderPostFee = BigDecimal.ZERO;
		}
		if(onlineOrderCouponTotalMoney == null){
			onlineOrderCouponTotalMoney = BigDecimal.ZERO;
		}
		paymentMoney = paymentMoney.add(onlineOrderPostFee);	
		paymentMoney = paymentMoney.subtract(onlineOrderCouponTotalMoney);
		return paymentMoney.setScale(2, BigDecimal.ROUND_HALF_UP);
	}

	public static OnlineOrder get(List<OnlineOrder> onlineOrders, String onlineOrderFid) {
		OnlineOrder onlineOrder;
		for(int i = 0;i < onlineOrders.size();i++){
			onlineOrder = onlineOrders.get(i);
			if(onlineOrder.getOnlineOrderFid().equals(onlineOrderFid)){
				return onlineOrder;
			}
		}
		return null;
	}

}
