package com.nhsoft.report.model;

import com.nhsoft.report.shared.State;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * OrderTask generated by hbm2java
 */
public class OrderTask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -306300421746126854L;
	private String orderTaskFid;
	private String taskRequestFid;
	private String systemBookCode;
	private Integer branchNum;
	private Integer itemNum;
	private String orderTaskType;
	private String orderTaskBizday;
	private Date orderTaskCreateTime;
	private String orderTaskCreator;
	private String orderTaskItemCode;
	private String orderTaskItemName;
	private String orderTaskItemSpec;
	private String orderTaskItemUnit;
	private BigDecimal orderTaskRequestQty;
	private BigDecimal orderTaskPurchaseQty;
	private BigDecimal orderTaskUseQty;
	private State state;
	private String orderTaskMemo;
	private String orderTaskDefaultUserName;
	private Integer orderTaskUserNum;
	private String orderTaskUserName;
	private BigDecimal orderTaskStock;
	private Boolean orderTaskSelfTag;
	private Integer supplierNum;
	private BigDecimal orderTaskUseRate;
	private Date orderTaskAuditTime;
	private String orderTaskAuditor;
	private Date orderTaskFinishTime;
	private Integer storehouseNum;
	private BigDecimal orderTaskItemLastRate; //上次采购转换率
	private String orderTaskItemBaseUnit; //基本单位
	private String orderTaskItemDepartment;//商品部门
	private Integer itemMatrixNum;
	private String orderTaskItemCostMode;
	private BigDecimal orderTaskReceiveQty; //收货数量  茂雄这个属性用作原料对应成品的已加工量
	private BigDecimal orderTaskPresentUseQty;
	private List<OrderTaskDetail> orderTaskDetails = new ArrayList<OrderTaskDetail>();
	
	private Boolean checkInRequest = true; //验证是否在要货汇总里
	private boolean generateTaskTransfer = false; //是否生成配送任务
	private boolean auditTaskTransfer = false; //是否直接审核配送任务
	private Boolean checkInOrderTask = false; //验证是否在已生成审核的任务
	
	//临时属性
	private PosItem posItem;
	private BigDecimal price;//明细成本价

	public OrderTask() {
	}
	
	public BigDecimal getOrderTaskPresentUseQty() {
		return orderTaskPresentUseQty;
	}
	
	public void setOrderTaskPresentUseQty(BigDecimal orderTaskPresentUseQty) {
		this.orderTaskPresentUseQty = orderTaskPresentUseQty;
	}
	
	public PosItem getPosItem() {
		return posItem;
	}
	
	public void setPosItem(PosItem posItem) {
		this.posItem = posItem;
	}
	
	public BigDecimal getPrice() {
		return price;
	}
	
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	public boolean isGenerateTaskTransfer() {
		return generateTaskTransfer;
	}

	public void setGenerateTaskTransfer(boolean generateTaskTransfer) {
		this.generateTaskTransfer = generateTaskTransfer;
	}

	public Boolean getCheckInOrderTask() {
		return checkInOrderTask;
	}

	public void setCheckInOrderTask(Boolean checkInOrderTask) {
		this.checkInOrderTask = checkInOrderTask;
	}

	public BigDecimal getOrderTaskReceiveQty() {
		return orderTaskReceiveQty;
	}

	public void setOrderTaskReceiveQty(BigDecimal orderTaskReceiveQty) {
		this.orderTaskReceiveQty = orderTaskReceiveQty;
	}

	public String getOrderTaskItemCostMode() {
		return orderTaskItemCostMode;
	}

	public void setOrderTaskItemCostMode(String orderTaskItemCostMode) {
		this.orderTaskItemCostMode = orderTaskItemCostMode;
	}

	public boolean isAuditTaskTransfer() {
		return auditTaskTransfer;
	}

	public void setAuditTaskTransfer(boolean auditTaskTransfer) {
		this.auditTaskTransfer = auditTaskTransfer;
	}

	public String getOrderTaskItemDepartment() {
		return orderTaskItemDepartment;
	}

	public void setOrderTaskItemDepartment(String orderTaskItemDepartment) {
		this.orderTaskItemDepartment = orderTaskItemDepartment;
	}

	public String getOrderTaskItemBaseUnit() {
		return orderTaskItemBaseUnit;
	}


	public void setOrderTaskItemBaseUnit(String orderTaskItemBaseUnit) {
		this.orderTaskItemBaseUnit = orderTaskItemBaseUnit;
	}


	public BigDecimal getOrderTaskUseRate() {
		return orderTaskUseRate;
	}


	public void setOrderTaskUseRate(BigDecimal orderTaskUseRate) {
		this.orderTaskUseRate = orderTaskUseRate;
	}


	public Date getOrderTaskAuditTime() {
		return orderTaskAuditTime;
	}


	public void setOrderTaskAuditTime(Date orderTaskAuditTime) {
		this.orderTaskAuditTime = orderTaskAuditTime;
	}


	public String getOrderTaskAuditor() {
		return orderTaskAuditor;
	}


	public void setOrderTaskAuditor(String orderTaskAuditor) {
		this.orderTaskAuditor = orderTaskAuditor;
	}


	public Integer getSupplierNum() {
		return supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public String getOrderTaskBizday() {
		return orderTaskBizday;
	}

	public void setOrderTaskBizday(String orderTaskBizday) {
		this.orderTaskBizday = orderTaskBizday;
	}

	public OrderTask(String orderTaskFid) {
		this.orderTaskFid = orderTaskFid;
	}

	public String getOrderTaskFid() {
		return this.orderTaskFid;
	}

	public void setOrderTaskFid(String orderTaskFid) {
		this.orderTaskFid = orderTaskFid;
	}

	public String getTaskRequestFid() {
		return this.taskRequestFid;
	}

	public void setTaskRequestFid(String taskRequestFid) {
		this.taskRequestFid = taskRequestFid;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getOrderTaskType() {
		return this.orderTaskType;
	}

	public void setOrderTaskType(String orderTaskType) {
		this.orderTaskType = orderTaskType;
	}

	public Date getOrderTaskCreateTime() {
		return this.orderTaskCreateTime;
	}

	public void setOrderTaskCreateTime(Date orderTaskCreateTime) {
		this.orderTaskCreateTime = orderTaskCreateTime;
	}

	public String getOrderTaskCreator() {
		return this.orderTaskCreator;
	}

	public void setOrderTaskCreator(String orderTaskCreator) {
		this.orderTaskCreator = orderTaskCreator;
	}

	public String getOrderTaskItemCode() {
		return this.orderTaskItemCode;
	}

	public void setOrderTaskItemCode(String orderTaskItemCode) {
		this.orderTaskItemCode = orderTaskItemCode;
	}

	public String getOrderTaskItemName() {
		return this.orderTaskItemName;
	}

	public void setOrderTaskItemName(String orderTaskItemName) {
		this.orderTaskItemName = orderTaskItemName;
	}

	public String getOrderTaskItemSpec() {
		return this.orderTaskItemSpec;
	}

	public void setOrderTaskItemSpec(String orderTaskItemSpec) {
		this.orderTaskItemSpec = orderTaskItemSpec;
	}

	public String getOrderTaskItemUnit() {
		return this.orderTaskItemUnit;
	}

	public void setOrderTaskItemUnit(String orderTaskItemUnit) {
		this.orderTaskItemUnit = orderTaskItemUnit;
	}

	public BigDecimal getOrderTaskRequestQty() {
		return this.orderTaskRequestQty;
	}

	public void setOrderTaskRequestQty(BigDecimal orderTaskRequestQty) {
		this.orderTaskRequestQty = orderTaskRequestQty;
	}

	public BigDecimal getOrderTaskPurchaseQty() {
		return this.orderTaskPurchaseQty;
	}

	public void setOrderTaskPurchaseQty(BigDecimal orderTaskPurchaseQty) {
		this.orderTaskPurchaseQty = orderTaskPurchaseQty;
	}

	public BigDecimal getOrderTaskUseQty() {
		return this.orderTaskUseQty;
	}

	public void setOrderTaskUseQty(BigDecimal orderTaskUseQty) {
		this.orderTaskUseQty = orderTaskUseQty;
	}


	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getOrderTaskMemo() {
		return this.orderTaskMemo;
	}

	public void setOrderTaskMemo(String orderTaskMemo) {
		this.orderTaskMemo = orderTaskMemo;
	}

	public Integer getOrderTaskUserNum() {
		return this.orderTaskUserNum;
	}

	public void setOrderTaskUserNum(Integer orderTaskUserNum) {
		this.orderTaskUserNum = orderTaskUserNum;
	}

	public String getOrderTaskUserName() {
		return this.orderTaskUserName;
	}

	public void setOrderTaskUserName(String orderTaskUserName) {
		this.orderTaskUserName = orderTaskUserName;
	}

	public BigDecimal getOrderTaskStock() {
		return this.orderTaskStock;
	}

	public void setOrderTaskStock(BigDecimal orderTaskStock) {
		this.orderTaskStock = orderTaskStock;
	}

	public Boolean getOrderTaskSelfTag() {
		return this.orderTaskSelfTag;
	}

	public void setOrderTaskSelfTag(Boolean orderTaskSelfTag) {
		this.orderTaskSelfTag = orderTaskSelfTag;
	}

	public List<OrderTaskDetail> getOrderTaskDetails() {
		return orderTaskDetails;
	}

	public void setOrderTaskDetails(List<OrderTaskDetail> orderTaskDetails) {
		this.orderTaskDetails = orderTaskDetails;
	}

	public String getOrderTaskDefaultUserName() {
		return orderTaskDefaultUserName;
	}

	public void setOrderTaskDefaultUserName(String orderTaskDefaultUserName) {
		this.orderTaskDefaultUserName = orderTaskDefaultUserName;
	}


	public Date getOrderTaskFinishTime() {
		return orderTaskFinishTime;
	}


	public void setOrderTaskFinishTime(Date orderTaskFinishTime) {
		this.orderTaskFinishTime = orderTaskFinishTime;
	}
	public Integer getStorehouseNum() {
		return storehouseNum;
	}


	public void setStorehouseNum(Integer storehouseNum) {
		this.storehouseNum = storehouseNum;
	}

	public Boolean getCheckInRequest() {
		return checkInRequest;
	}


	public void setCheckInRequest(Boolean checkInRequest) {
		this.checkInRequest = checkInRequest;
	}


	public BigDecimal getOrderTaskItemLastRate() {
		return orderTaskItemLastRate;
	}


	public void setOrderTaskItemLastRate(BigDecimal orderTaskItemLastRate) {
		this.orderTaskItemLastRate = orderTaskItemLastRate;
	}

	public Integer getItemMatrixNum() {
		return itemMatrixNum;
	}

	public void setItemMatrixNum(Integer itemMatrixNum) {
		this.itemMatrixNum = itemMatrixNum;
	}

	public static List<OrderTask> findOrderTasks(List<OrderTask> orderTasks, Integer itemNum, String orderTaskType) {
		List<OrderTask> list = new ArrayList<OrderTask>();
		for(int i = 0;i < orderTasks.size();i++){
			OrderTask orderTask = orderTasks.get(i);
			if(orderTask.getItemNum().equals(itemNum) && orderTask.getOrderTaskType().equals(orderTaskType)){
				list.add(orderTask);
				
			}
		}
		return list;
	}
	
	public static List<OrderTask> findOrderTasks(List<OrderTask> orderTasks, Integer itemNum, String orderTaskType, Integer itemMatrixNum) {
		List<OrderTask> list = new ArrayList<OrderTask>();
		for(int i = 0;i < orderTasks.size();i++){
			OrderTask orderTask = orderTasks.get(i);
			if(orderTask.getItemMatrixNum() == null){
				orderTask.setItemMatrixNum(0);
			}
			if(orderTask.getItemNum().equals(itemNum) 
					&& orderTask.getOrderTaskType().equals(orderTaskType)
					&& orderTask.getItemMatrixNum().equals(itemMatrixNum)){
				list.add(orderTask);
				
			}
		}
		return list;
	}

}
