package com.nhsoft.report.model;



/**
 * PolicyPromotionMoneyDetailId generated by hbm2java
 */
public class PolicyPromotionMoneyDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6881649179130885885L;
	private String promotionMoneyNo;
	private Integer promotionMoneyDetailNum;

	public PolicyPromotionMoneyDetailId() {
	}

	public PolicyPromotionMoneyDetailId(String promotionMoneyNo,
			Integer promotionMoneyDetailNum) {
		this.promotionMoneyNo = promotionMoneyNo;
		this.promotionMoneyDetailNum = promotionMoneyDetailNum;
	}

	public String getPromotionMoneyNo() {
		return this.promotionMoneyNo;
	}

	public void setPromotionMoneyNo(String promotionMoneyNo) {
		this.promotionMoneyNo = promotionMoneyNo;
	}

	public Integer getPromotionMoneyDetailNum() {
		return this.promotionMoneyDetailNum;
	}

	public void setPromotionMoneyDetailNum(Integer promotionMoneyDetailNum) {
		this.promotionMoneyDetailNum = promotionMoneyDetailNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PolicyPromotionMoneyDetailId))
			return false;
		PolicyPromotionMoneyDetailId castOther = (PolicyPromotionMoneyDetailId) other;

		return ((this.getPromotionMoneyNo() == castOther.getPromotionMoneyNo()) || (this
				.getPromotionMoneyNo() != null
				&& castOther.getPromotionMoneyNo() != null && this
				.getPromotionMoneyNo().equals(castOther.getPromotionMoneyNo())))
				&& ((this.getPromotionMoneyDetailNum() == castOther
						.getPromotionMoneyDetailNum()) || (this
						.getPromotionMoneyDetailNum() != null
						&& castOther.getPromotionMoneyDetailNum() != null && this
						.getPromotionMoneyDetailNum().equals(
								castOther.getPromotionMoneyDetailNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPromotionMoneyNo() == null ? 0 : this
						.getPromotionMoneyNo().hashCode());
		result = 37
				* result
				+ (getPromotionMoneyDetailNum() == null ? 0 : this
						.getPromotionMoneyDetailNum().hashCode());
		return result;
	}

}
