package com.nhsoft.report.model;



/**
 * PosMachineId generated by hbm2java
 */
public class PosMachineId implements java.io.Serializable {

	private static final long serialVersionUID = -5824953413303020371L;
	private String systemBookCode;
	private Integer branchNum;
	private Integer posMachineNum;

	public PosMachineId() {
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public Integer getPosMachineNum() {
		return this.posMachineNum;
	}

	public void setPosMachineNum(Integer posMachineNum) {
		this.posMachineNum = posMachineNum;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((branchNum == null) ? 0 : branchNum.hashCode());
		result = prime * result + ((posMachineNum == null) ? 0 : posMachineNum.hashCode());
		result = prime * result + ((systemBookCode == null) ? 0 : systemBookCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PosMachineId other = (PosMachineId) obj;
		if (branchNum == null) {
			if (other.branchNum != null)
				return false;
		} else if (!branchNum.equals(other.branchNum))
			return false;
		if (posMachineNum == null) {
			if (other.posMachineNum != null)
				return false;
		} else if (!posMachineNum.equals(other.posMachineNum))
			return false;
		if (systemBookCode == null) {
			if (other.systemBookCode != null)
				return false;
		} else if (!systemBookCode.equals(other.systemBookCode))
			return false;
		return true;
	}



}
