package com.nhsoft.report.model;



import java.util.Date;

/**
 * PosMachine generated by hbm2java
 */
public class PosMachine implements java.io.Serializable {

	private static final long serialVersionUID = -2826541279977752611L;
	private PosMachineId id;
	private Integer storehouseNum;
	private String posMachineName;
	private String posMachineTerminalId;
	private String posMachineMemo;
	private Boolean posMachineEnabled;
	private Date posMachineLastUpload;
	private String posMachineCpuId;
	private String posMachineType;
	private Boolean posMachineRpcFlag;
	private String posMachinePath;
	
	public PosMachine() {
	}

	public Boolean getPosMachineRpcFlag() {
		return posMachineRpcFlag;
	}

	public void setPosMachineRpcFlag(Boolean posMachineRpcFlag) {
		this.posMachineRpcFlag = posMachineRpcFlag;
	}

	public String getPosMachinePath() {
		return posMachinePath;
	}

	public void setPosMachinePath(String posMachinePath) {
		this.posMachinePath = posMachinePath;
	}

	public PosMachineId getId() {
		return this.id;
	}

	public void setId(PosMachineId id) {
		this.id = id;
	}

	public String getPosMachineCpuId() {
		return posMachineCpuId;
	}

	public void setPosMachineCpuId(String posMachineCpuId) {
		this.posMachineCpuId = posMachineCpuId;
	}

	public Integer getStorehouseNum() {
		return this.storehouseNum;
	}

	public void setStorehouseNum(Integer storehouseNum) {
		this.storehouseNum = storehouseNum;
	}

	public String getPosMachineName() {
		return this.posMachineName;
	}

	public void setPosMachineName(String posMachineName) {
		this.posMachineName = posMachineName;
	}

	public String getPosMachineTerminalId() {
		return this.posMachineTerminalId;
	}

	public void setPosMachineTerminalId(String posMachineTerminalId) {
		this.posMachineTerminalId = posMachineTerminalId;
	}

	public String getPosMachineMemo() {
		return this.posMachineMemo;
	}

	public void setPosMachineMemo(String posMachineMemo) {
		this.posMachineMemo = posMachineMemo;
	}

	public Date getPosMachineLastUpload() {
		return this.posMachineLastUpload;
	}

	public void setPosMachineLastUpload(Date posMachineLastUpload) {
		this.posMachineLastUpload = posMachineLastUpload;
	}

	public Boolean getPosMachineEnabled() {
		return posMachineEnabled;
	}

	public void setPosMachineEnabled(Boolean posMachineEnabled) {
		this.posMachineEnabled = posMachineEnabled;
	}

	public String getPosMachineType() {
		return posMachineType;
	}

	public void setPosMachineType(String posMachineType) {
		this.posMachineType = posMachineType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PosMachine other = (PosMachine) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}


}
