package com.nhsoft.report.model;


import com.nhsoft.report.util.DateUtil;
import org.apache.commons.lang3.BooleanUtils;
import org.dom4j.Element;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 * PosOrderDetail generated by hbm2java
 */
@SuppressWarnings("unchecked")
public class PosOrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 5073851881391338311L;
	private PosOrderDetailId id;
	private Integer itemNum;
	private String orderDetailType;
	private String orderDetailItem;
	private String orderDetailItemDepartment;
	private BigDecimal orderDetailStdPrice;
	private BigDecimal orderDetailPrice;
	private BigDecimal orderDetailAmount;
	private BigDecimal orderDetailMoney;
	private BigDecimal orderDetailAppendMoney;
	private BigDecimal orderDetailDiscount;
	private BigDecimal orderDetailTax;
	private BigDecimal orderDetailPaymentMoney;
	private Integer orderDetailStateCode;
	private String orderDetailStateName;
	private String orderDetailAuditor;
	private String orderDetailMemo;
	private Integer orderDetailItemMatrixNum;
	private String orderDetailItemSerialNumber;
	private BigDecimal orderDetailCommission;
	private Boolean orderDetailPolicyPromotionFlag;
	private Boolean orderDetailPolicyPromotionQuantityFlag;
	private Boolean orderDetailPolicyPromotionMoneyFlag;
	private Boolean orderDetailPolicyPresentFlag;
	private String orderDetailPolicyFid;
	private Integer orderDetailPolicyDetailNum;
	private BigDecimal orderDetailCost;
	private BigDecimal orderDetailGrossProfit;
	private Date orderDetailProducingDate;
	private String orderDetailLotNumber;
	private String orderDetailTicketUuid;
	private BigDecimal orderDetailAssistAmount;
	private Integer orderDetailPromotionType;
	private String orderDetailTicketActionId;
	private Boolean orderDetailPolicyDiscountFlag;
	private String orderDetailBookCode;
	private Integer orderDetailBranchNum;
	private String orderDetailBizday;
	private Integer orderDetailOrderState;
	private Integer itemGradeNum;
	private String orderDetailOnlineUnit;
	private BigDecimal orderDetailOnlineQty;
	private BigDecimal orderDetailOnlinePrice;
	private Boolean orderDetailHasKit;
	private String orderSource;
	private Integer supplierNum;
	private List<PosOrderKitDetail> posOrderKitDetails = new ArrayList<PosOrderKitDetail>();
	
	//临时属性
	private String orderDetailItemCode;

	public Integer getSupplierNum() {
		return supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public String getOrderSource() {
		return orderSource;
	}

	public void setOrderSource(String orderSource) {
		this.orderSource = orderSource;
	}

	public PosOrderDetail() {
	}

	public String getOrderDetailItemCode() {
		return orderDetailItemCode;
	}

	public void setOrderDetailItemCode(String orderDetailItemCode) {
		this.orderDetailItemCode = orderDetailItemCode;
	}

	public Boolean getOrderDetailHasKit() {
		return orderDetailHasKit;
	}

	public void setOrderDetailHasKit(Boolean orderDetailHasKit) {
		this.orderDetailHasKit = orderDetailHasKit;
	}

	public String getOrderDetailOnlineUnit() {
		return orderDetailOnlineUnit;
	}

	public void setOrderDetailOnlineUnit(String orderDetailOnlineUnit) {
		this.orderDetailOnlineUnit = orderDetailOnlineUnit;
	}

	public BigDecimal getOrderDetailOnlineQty() {
		return orderDetailOnlineQty;
	}

	public void setOrderDetailOnlineQty(BigDecimal orderDetailOnlineQty) {
		this.orderDetailOnlineQty = orderDetailOnlineQty;
	}

	public BigDecimal getOrderDetailOnlinePrice() {
		return orderDetailOnlinePrice;
	}

	public void setOrderDetailOnlinePrice(BigDecimal orderDetailOnlinePrice) {
		this.orderDetailOnlinePrice = orderDetailOnlinePrice;
	}

	public PosOrderDetailId getId() {
		return this.id;
	}

	public void setId(PosOrderDetailId id) {
		this.id = id;
	}

	public Integer getItemGradeNum() {
		return itemGradeNum;
	}

	public void setItemGradeNum(Integer itemGradeNum) {
		this.itemGradeNum = itemGradeNum;
	}

	public Integer getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Integer itemNum) {
		this.itemNum = itemNum;
	}

	public String getOrderDetailType() {
		return this.orderDetailType;
	}

	public void setOrderDetailType(String orderDetailType) {
		this.orderDetailType = orderDetailType;
	}

	public String getOrderDetailItem() {
		return this.orderDetailItem;
	}

	public void setOrderDetailItem(String orderDetailItem) {
		this.orderDetailItem = orderDetailItem;
	}

	public String getOrderDetailItemDepartment() {
		return this.orderDetailItemDepartment;
	}

	public void setOrderDetailItemDepartment(String orderDetailItemDepartment) {
		this.orderDetailItemDepartment = orderDetailItemDepartment;
	}

	public BigDecimal getOrderDetailStdPrice() {
		return this.orderDetailStdPrice;
	}

	public void setOrderDetailStdPrice(BigDecimal orderDetailStdPrice) {
		this.orderDetailStdPrice = orderDetailStdPrice;
	}

	public BigDecimal getOrderDetailPrice() {
		return this.orderDetailPrice;
	}

	public void setOrderDetailPrice(BigDecimal orderDetailPrice) {
		this.orderDetailPrice = orderDetailPrice;
	}

	public BigDecimal getOrderDetailAmount() {
		return this.orderDetailAmount;
	}

	public void setOrderDetailAmount(BigDecimal orderDetailAmount) {
		this.orderDetailAmount = orderDetailAmount;
	}

	public BigDecimal getOrderDetailMoney() {
		return this.orderDetailMoney;
	}

	public void setOrderDetailMoney(BigDecimal orderDetailMoney) {
		this.orderDetailMoney = orderDetailMoney;
	}

	public BigDecimal getOrderDetailAppendMoney() {
		return this.orderDetailAppendMoney;
	}

	public void setOrderDetailAppendMoney(BigDecimal orderDetailAppendMoney) {
		this.orderDetailAppendMoney = orderDetailAppendMoney;
	}

	public BigDecimal getOrderDetailDiscount() {
		return this.orderDetailDiscount;
	}

	public void setOrderDetailDiscount(BigDecimal orderDetailDiscount) {
		this.orderDetailDiscount = orderDetailDiscount;
	}

	public BigDecimal getOrderDetailTax() {
		return this.orderDetailTax;
	}

	public void setOrderDetailTax(BigDecimal orderDetailTax) {
		this.orderDetailTax = orderDetailTax;
	}

	public BigDecimal getOrderDetailPaymentMoney() {
		return this.orderDetailPaymentMoney;
	}

	public void setOrderDetailPaymentMoney(BigDecimal orderDetailPaymentMoney) {
		this.orderDetailPaymentMoney = orderDetailPaymentMoney;
	}

	public Integer getOrderDetailStateCode() {
		return this.orderDetailStateCode;
	}

	public void setOrderDetailStateCode(Integer orderDetailStateCode) {
		this.orderDetailStateCode = orderDetailStateCode;
	}

	public String getOrderDetailStateName() {
		return this.orderDetailStateName;
	}

	public void setOrderDetailStateName(String orderDetailStateName) {
		this.orderDetailStateName = orderDetailStateName;
	}

	public String getOrderDetailAuditor() {
		return this.orderDetailAuditor;
	}

	public void setOrderDetailAuditor(String orderDetailAuditor) {
		this.orderDetailAuditor = orderDetailAuditor;
	}

	public String getOrderDetailMemo() {
		return this.orderDetailMemo;
	}

	public void setOrderDetailMemo(String orderDetailMemo) {
		this.orderDetailMemo = orderDetailMemo;
	}

	public Integer getOrderDetailItemMatrixNum() {
		return this.orderDetailItemMatrixNum;
	}

	public void setOrderDetailItemMatrixNum(Integer orderDetailItemMatrixNum) {
		this.orderDetailItemMatrixNum = orderDetailItemMatrixNum;
	}

	public String getOrderDetailItemSerialNumber() {
		return this.orderDetailItemSerialNumber;
	}

	public void setOrderDetailItemSerialNumber(
			String orderDetailItemSerialNumber) {
		this.orderDetailItemSerialNumber = orderDetailItemSerialNumber;
	}

	public BigDecimal getOrderDetailCommission() {
		return this.orderDetailCommission;
	}

	public void setOrderDetailCommission(BigDecimal orderDetailCommission) {
		this.orderDetailCommission = orderDetailCommission;
	}

	public Boolean getOrderDetailPolicyPromotionFlag() {
		return this.orderDetailPolicyPromotionFlag;
	}

	public void setOrderDetailPolicyPromotionFlag(
			Boolean orderDetailPolicyPromotionFlag) {
		this.orderDetailPolicyPromotionFlag = orderDetailPolicyPromotionFlag;
	}

	public Boolean getOrderDetailPolicyPromotionQuantityFlag() {
		return this.orderDetailPolicyPromotionQuantityFlag;
	}

	public void setOrderDetailPolicyPromotionQuantityFlag(
			Boolean orderDetailPolicyPromotionQuantityFlag) {
		this.orderDetailPolicyPromotionQuantityFlag = orderDetailPolicyPromotionQuantityFlag;
	}

	public Boolean getOrderDetailPolicyPromotionMoneyFlag() {
		return this.orderDetailPolicyPromotionMoneyFlag;
	}

	public void setOrderDetailPolicyPromotionMoneyFlag(
			Boolean orderDetailPolicyPromotionMoneyFlag) {
		this.orderDetailPolicyPromotionMoneyFlag = orderDetailPolicyPromotionMoneyFlag;
	}

	public Boolean getOrderDetailPolicyPresentFlag() {
		return this.orderDetailPolicyPresentFlag;
	}

	public void setOrderDetailPolicyPresentFlag(
			Boolean orderDetailPolicyPresentFlag) {
		this.orderDetailPolicyPresentFlag = orderDetailPolicyPresentFlag;
	}

	public String getOrderDetailPolicyFid() {
		return this.orderDetailPolicyFid;
	}

	public void setOrderDetailPolicyFid(String orderDetailPolicyFid) {
		this.orderDetailPolicyFid = orderDetailPolicyFid;
	}

	public Integer getOrderDetailPolicyDetailNum() {
		return this.orderDetailPolicyDetailNum;
	}

	public void setOrderDetailPolicyDetailNum(Integer orderDetailPolicyDetailNum) {
		this.orderDetailPolicyDetailNum = orderDetailPolicyDetailNum;
	}

	public BigDecimal getOrderDetailCost() {
		return this.orderDetailCost;
	}

	public void setOrderDetailCost(BigDecimal orderDetailCost) {
		this.orderDetailCost = orderDetailCost;
	}

	public BigDecimal getOrderDetailGrossProfit() {
		return this.orderDetailGrossProfit;
	}

	public void setOrderDetailGrossProfit(BigDecimal orderDetailGrossProfit) {
		this.orderDetailGrossProfit = orderDetailGrossProfit;
	}

	public Date getOrderDetailProducingDate() {
		return this.orderDetailProducingDate;
	}

	public void setOrderDetailProducingDate(Date orderDetailProducingDate) {
		this.orderDetailProducingDate = orderDetailProducingDate;
	}

	public String getOrderDetailLotNumber() {
		return this.orderDetailLotNumber;
	}

	public void setOrderDetailLotNumber(String orderDetailLotNumber) {
		this.orderDetailLotNumber = orderDetailLotNumber;
	}

	public String getOrderDetailTicketUuid() {
		return this.orderDetailTicketUuid;
	}

	public void setOrderDetailTicketUuid(String orderDetailTicketUuid) {
		this.orderDetailTicketUuid = orderDetailTicketUuid;
	}

	public BigDecimal getOrderDetailAssistAmount() {
		return this.orderDetailAssistAmount;
	}

	public void setOrderDetailAssistAmount(BigDecimal orderDetailAssistAmount) {
		this.orderDetailAssistAmount = orderDetailAssistAmount;
	}

	public Integer getOrderDetailPromotionType() {
		return this.orderDetailPromotionType;
	}

	public void setOrderDetailPromotionType(Integer orderDetailPromotionType) {
		this.orderDetailPromotionType = orderDetailPromotionType;
	}

	public List<PosOrderKitDetail> getPosOrderKitDetails() {
		return posOrderKitDetails;
	}

	public void setPosOrderKitDetails(List<PosOrderKitDetail> posOrderKitDetails) {
		this.posOrderKitDetails = posOrderKitDetails;
	}

	public String getOrderDetailTicketActionId() {
		return orderDetailTicketActionId;
	}

	public void setOrderDetailTicketActionId(String orderDetailTicketActionId) {
		this.orderDetailTicketActionId = orderDetailTicketActionId;
	}

	public Boolean getOrderDetailPolicyDiscountFlag() {
		return orderDetailPolicyDiscountFlag;
	}

	public void setOrderDetailPolicyDiscountFlag(Boolean orderDetailPolicyDiscountFlag) {
		this.orderDetailPolicyDiscountFlag = orderDetailPolicyDiscountFlag;
	}

	public String getOrderDetailBookCode() {
		return orderDetailBookCode;
	}

	public void setOrderDetailBookCode(String orderDetailBookCode) {
		this.orderDetailBookCode = orderDetailBookCode;
	}

	public Integer getOrderDetailBranchNum() {
		return orderDetailBranchNum;
	}

	public void setOrderDetailBranchNum(Integer orderDetailBranchNum) {
		this.orderDetailBranchNum = orderDetailBranchNum;
	}

	public String getOrderDetailBizday() {
		return orderDetailBizday;
	}

	public void setOrderDetailBizday(String orderDetailBizday) {
		this.orderDetailBizday = orderDetailBizday;
	}

	public Integer getOrderDetailOrderState() {
		return orderDetailOrderState;
	}

	public void setOrderDetailOrderState(Integer orderDetailOrderState) {
		this.orderDetailOrderState = orderDetailOrderState;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PosOrderDetail other = (PosOrderDetail) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public static List<PosOrderDetail> readFromNode(Element root){
		List<PosOrderDetail> posOrderDetails = new ArrayList<PosOrderDetail>();
		Iterator<Element> iterator = root.elementIterator("POS_ORDER_DETAIL");
		while(iterator.hasNext()){
			Element element = iterator.next();
			PosOrderDetail detail = new PosOrderDetail();
			PosOrderDetailId id = new PosOrderDetailId();
			Element node = (Element)element.selectSingleNode("ORDER_NO");
			if(node != null){				
				id.setOrderNo(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_NUM");
			if(node != null){				
				id.setOrderDetailNum(Integer.parseInt(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_ITEM_MATRIX_NUM");
			if(node != null){				
				detail.setOrderDetailItemMatrixNum(Integer.parseInt(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ITEM_NUM");
			if(node != null){				
				detail.setItemNum(Integer.parseInt(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_TYPE");
			if(node != null){				
				detail.setOrderDetailType(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_ITEM");
			if(node != null){				
				detail.setOrderDetailItem(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_ITEM_DEPARTMENT");
			if(node != null){				
				detail.setOrderDetailItemDepartment(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_STD_PRICE");
			if(node != null){				
				detail.setOrderDetailStdPrice(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_AMOUNT");
			if(node != null){				
				detail.setOrderDetailAmount(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_MONEY");
			if(node != null){				
				detail.setOrderDetailMoney(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_APPEND_MONEY");
			if(node != null){				
				detail.setOrderDetailAppendMoney(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_DISCOUNT");
			if(node != null){				
				detail.setOrderDetailDiscount(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_TAX");
			if(node != null){				
				detail.setOrderDetailTax(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_PAYMENT_MONEY");
			if(node != null){				
				detail.setOrderDetailPaymentMoney(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_STATE_CODE");
			if(node != null){				
				detail.setOrderDetailStateCode(Integer.parseInt(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_STATE_NAME");
			if(node != null){				
				detail.setOrderDetailStateName(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_AUDITOR");
			if(node != null){				
				detail.setOrderDetailAuditor(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_MEMO");
			if(node != null){				
				detail.setOrderDetailMemo(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_PROMOTION_FLAG");
			if(node != null){				
				detail.setOrderDetailPolicyPromotionFlag(BooleanUtils.toBoolean(node.getText(), "1", "0"));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_PROMOTION_QUANTITY_FLAG");
			if(node != null){				
				detail.setOrderDetailPolicyPromotionQuantityFlag(BooleanUtils.toBoolean(node.getText(), "1", "0"));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_PROMOTION_MONEY_FLAG");
			if(node != null){				
				detail.setOrderDetailPolicyPromotionMoneyFlag(BooleanUtils.toBoolean(node.getText(), "1", "0"));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_PRESENT_FLAG");
			if(node != null){				
				detail.setOrderDetailPolicyPresentFlag(BooleanUtils.toBoolean(node.getText(), "1", "0"));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_FID");
			if(node != null){				
				detail.setOrderDetailPolicyFid(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_POLICY_DETAIL_NUM");
			if(node != null){				
				detail.setOrderDetailPolicyDetailNum(Integer.parseInt(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_COST");
			if(node != null){				
				detail.setOrderDetailCost(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_GROSS_PROFIT");
			if(node != null){				
				detail.setOrderDetailGrossProfit(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_PRODUCING_DATE");
			if(node != null){				
				detail.setOrderDetailProducingDate(DateUtil.getXmlDate(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_LOT_NUMBER");
			if(node != null){				
				detail.setOrderDetailLotNumber(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_TICKET_UUID");
			if(node != null){				
				detail.setOrderDetailTicketUuid(node.getText());
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_COMMISSION");
			if(node != null){				
				detail.setOrderDetailCommission(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_ASSIST_AMOUNT");
			if(node != null){				
				detail.setOrderDetailAssistAmount(new BigDecimal(node.getText()));
			}
			
			node = (Element)element.selectSingleNode("ORDER_DETAIL_PRICE");
			if(node != null){				
				detail.setOrderDetailPrice(new BigDecimal(node.getText()));
			}
			node = (Element)element.selectSingleNode("ORDER_DETAIL_STD_PRICE");
			if(node != null){				
				detail.setOrderDetailStdPrice(new BigDecimal(node.getText()));
			}
			
			node = (Element) element.selectSingleNode("POS_ORDER_KIT_DETAIL_LIST");
			if(node != null){
				detail.setPosOrderKitDetails(PosOrderKitDetail.readFromNode(node));
			}
			
			detail.setId(id);
			posOrderDetails.add(detail);
		}
		
		return posOrderDetails;
	}

	public static List<PosOrderDetail> find(
            List<PosOrderDetail> posOrderDetails, String orderNo) {
	    List<PosOrderDetail> list = new ArrayList<PosOrderDetail>();
	    for(int i = 0;i < posOrderDetails.size();i++){
	    	PosOrderDetail posOrderDetail = posOrderDetails.get(i);
	    	if(posOrderDetail.getId().getOrderNo().equals(orderNo)){
	    		list.add(posOrderDetail);
	    	}
	    }
	    return list;
    }
}
