package com.nhsoft.report.model;



import com.nhsoft.report.shared.State;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PreSettlement generated by hbm2java
 */
public class PreSettlement implements java.io.Serializable {

	private static final long serialVersionUID = 1842358228542339534L;
	private String preSettlementNo;
	private Integer supplierNum;
	private String systemBookCode;
	private Integer branchNum;
	private String preSettlementSupplierAddr;
	private String preSettlementTaxNo;
	private String preSettlementBank;
	private String preSettlementBankAccount;
	private String preSettlementSupplierName;
	private Date preSettlementDate;
	private String preSettlementPaymentType;
	private String preSettlementMemo;
	private String preSettlementCreator;
	private Date preSettlementCreatorTime;
	private String preSettlementAuditor;
	private Date preSettlementAuditTime;
	private State state;
	private String preSettlementRefBillNo;
	private BigDecimal preSettlementPaid;
	private BigDecimal preSettlementMoney;
	private Integer accountBankNum;
	private Boolean preSettlementSyncFlag;
	private String relationPreSettlementNo;
	private Boolean preSettlementReadFlag;
	private Boolean preSettlementSynchFlag;
	
	private List<PurchaseOrder> purchaseOrders = new ArrayList<PurchaseOrder>();

	public List<PurchaseOrder> getPurchaseOrders() {
		return purchaseOrders;
	}

	public void setPurchaseOrders(List<PurchaseOrder> purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

	public Boolean getPreSettlementSynchFlag() {
		return preSettlementSynchFlag;
	}

	public void setPreSettlementSynchFlag(Boolean preSettlementSynchFlag) {
		this.preSettlementSynchFlag = preSettlementSynchFlag;
	}

	public String getPreSettlementNo() {
		return this.preSettlementNo;
	}

	public void setPreSettlementNo(String preSettlementNo) {
		this.preSettlementNo = preSettlementNo;
	}

	public Integer getSupplierNum() {
		return this.supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getPreSettlementSupplierAddr() {
		return this.preSettlementSupplierAddr;
	}

	public void setPreSettlementSupplierAddr(String preSettlementSupplierAddr) {
		this.preSettlementSupplierAddr = preSettlementSupplierAddr;
	}

	public String getPreSettlementTaxNo() {
		return this.preSettlementTaxNo;
	}

	public void setPreSettlementTaxNo(String preSettlementTaxNo) {
		this.preSettlementTaxNo = preSettlementTaxNo;
	}

	public String getPreSettlementBank() {
		return this.preSettlementBank;
	}

	public void setPreSettlementBank(String preSettlementBank) {
		this.preSettlementBank = preSettlementBank;
	}

	public String getPreSettlementBankAccount() {
		return this.preSettlementBankAccount;
	}

	public void setPreSettlementBankAccount(String preSettlementBankAccount) {
		this.preSettlementBankAccount = preSettlementBankAccount;
	}

	public String getPreSettlementSupplierName() {
		return this.preSettlementSupplierName;
	}

	public void setPreSettlementSupplierName(String preSettlementSupplierName) {
		this.preSettlementSupplierName = preSettlementSupplierName;
	}

	public Date getPreSettlementDate() {
		return this.preSettlementDate;
	}

	public void setPreSettlementDate(Date preSettlementDate) {
		this.preSettlementDate = preSettlementDate;
	}

	public String getPreSettlementPaymentType() {
		return this.preSettlementPaymentType;
	}

	public void setPreSettlementPaymentType(String preSettlementPaymentType) {
		this.preSettlementPaymentType = preSettlementPaymentType;
	}

	public String getPreSettlementMemo() {
		return this.preSettlementMemo;
	}

	public void setPreSettlementMemo(String preSettlementMemo) {
		this.preSettlementMemo = preSettlementMemo;
	}

	public String getPreSettlementCreator() {
		return this.preSettlementCreator;
	}

	public void setPreSettlementCreator(String preSettlementCreator) {
		this.preSettlementCreator = preSettlementCreator;
	}

	public Date getPreSettlementCreatorTime() {
		return this.preSettlementCreatorTime;
	}

	public void setPreSettlementCreatorTime(Date preSettlementCreatorTime) {
		this.preSettlementCreatorTime = preSettlementCreatorTime;
	}

	public String getPreSettlementAuditor() {
		return this.preSettlementAuditor;
	}

	public void setPreSettlementAuditor(String preSettlementAuditor) {
		this.preSettlementAuditor = preSettlementAuditor;
	}

	public Date getPreSettlementAuditTime() {
		return this.preSettlementAuditTime;
	}

	public void setPreSettlementAuditTime(Date preSettlementAuditTime) {
		this.preSettlementAuditTime = preSettlementAuditTime;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getPreSettlementRefBillNo() {
		return this.preSettlementRefBillNo;
	}

	public void setPreSettlementRefBillNo(String preSettlementRefBillNo) {
		this.preSettlementRefBillNo = preSettlementRefBillNo;
	}

	public BigDecimal getPreSettlementPaid() {
		return this.preSettlementPaid;
	}

	public void setPreSettlementPaid(BigDecimal preSettlementPaid) {
		this.preSettlementPaid = preSettlementPaid;
	}

	public BigDecimal getPreSettlementMoney() {
		return this.preSettlementMoney;
	}

	public void setPreSettlementMoney(BigDecimal preSettlementMoney) {
		this.preSettlementMoney = preSettlementMoney;
	}

	public Integer getAccountBankNum() {
		return this.accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public String getRelationPreSettlementNo() {
		return this.relationPreSettlementNo;
	}

	public void setRelationPreSettlementNo(String relationPreSettlementNo) {
		this.relationPreSettlementNo = relationPreSettlementNo;
	}

	public Boolean getPreSettlementSyncFlag() {
		return preSettlementSyncFlag;
	}

	public Boolean getPreSettlementReadFlag() {
		return preSettlementReadFlag;
	}

	public void setPreSettlementReadFlag(Boolean preSettlementReadFlag) {
		this.preSettlementReadFlag = preSettlementReadFlag;
	}

	public void setPreSettlementSyncFlag(Boolean preSettlementSyncFlag) {
		this.preSettlementSyncFlag = preSettlementSyncFlag;
	}


}
