package com.nhsoft.report.model;



/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1323302784017264541L;
	private Integer regionNum;
	private String systemBookCode;
	private String regionName;
	private Integer regionParentNum;

	public Region() {
	}

	public Integer getRegionNum() {
		return this.regionNum;
	}

	public void setRegionNum(Integer regionNum) {
		this.regionNum = regionNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public Integer getRegionParentNum() {
		return this.regionParentNum;
	}

	public void setRegionParentNum(Integer regionParentNum) {
		this.regionParentNum = regionParentNum;
	}

}
