package com.nhsoft.report.model;



import com.nhsoft.report.shared.State;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Settlement generated by hbm2java
 */
public class Settlement implements java.io.Serializable {

	private static final long serialVersionUID = -4207162354864760550L;
	private String settlementNo;
	private Integer supplierNum;
	private String systemBookCode;
	private Integer branchNum;
	private String settlementSupplierAddr;
	private String settlementTaxNo;
	private String settlementBank;
	private String settlementBankAccount;
	private String settlementSupplierName;
	private Date settlementDate;
	private String settlementPaymentType;
	private String settlementMemo;
	private String settlementCreator;
	private Date settlementCreateTme;
	private String settlementAuditor;
	private Date settlementAuditTime;
	private State state;
	private String settlementRefBillNo;
	private BigDecimal settlementTotalMoney;
	private BigDecimal settlementTotalDiscount;
	private Integer accountBankNum;
	private Boolean settlementSyncFlag;
	private Boolean settlementReadFlag;
	private List<PreSettlementDetail> preSettlementDetails = new ArrayList<PreSettlementDetail>();
	private List<SettlementDetail> settlementDetails = new ArrayList<SettlementDetail>(0);

	public Settlement() {
	}

	public String getSettlementNo() {
		return this.settlementNo;
	}

	public void setSettlementNo(String settlementNo) {
		this.settlementNo = settlementNo;
	}

	public Integer getSupplierNum() {
		return this.supplierNum;
	}

	public void setSupplierNum(Integer supplierNum) {
		this.supplierNum = supplierNum;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getSettlementSupplierAddr() {
		return this.settlementSupplierAddr;
	}

	public void setSettlementSupplierAddr(String settlementSupplierAddr) {
		this.settlementSupplierAddr = settlementSupplierAddr;
	}

	public String getSettlementTaxNo() {
		return this.settlementTaxNo;
	}

	public void setSettlementTaxNo(String settlementTaxNo) {
		this.settlementTaxNo = settlementTaxNo;
	}

	public String getSettlementBank() {
		return this.settlementBank;
	}

	public void setSettlementBank(String settlementBank) {
		this.settlementBank = settlementBank;
	}

	public String getSettlementBankAccount() {
		return this.settlementBankAccount;
	}

	public void setSettlementBankAccount(String settlementBankAccount) {
		this.settlementBankAccount = settlementBankAccount;
	}

	public String getSettlementSupplierName() {
		return this.settlementSupplierName;
	}

	public void setSettlementSupplierName(String settlementSupplierName) {
		this.settlementSupplierName = settlementSupplierName;
	}

	public Date getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Date settlementDate) {
		this.settlementDate = settlementDate;
	}

	public String getSettlementPaymentType() {
		return this.settlementPaymentType;
	}

	public void setSettlementPaymentType(String settlementPaymentType) {
		this.settlementPaymentType = settlementPaymentType;
	}

	public String getSettlementMemo() {
		return this.settlementMemo;
	}

	public void setSettlementMemo(String settlementMemo) {
		this.settlementMemo = settlementMemo;
	}

	public String getSettlementCreator() {
		return this.settlementCreator;
	}

	public void setSettlementCreator(String settlementCreator) {
		this.settlementCreator = settlementCreator;
	}

	public Date getSettlementCreateTme() {
		return this.settlementCreateTme;
	}

	public void setSettlementCreateTme(Date settlementCreateTme) {
		this.settlementCreateTme = settlementCreateTme;
	}

	public String getSettlementAuditor() {
		return this.settlementAuditor;
	}

	public void setSettlementAuditor(String settlementAuditor) {
		this.settlementAuditor = settlementAuditor;
	}

	public Date getSettlementAuditTime() {
		return this.settlementAuditTime;
	}

	public void setSettlementAuditTime(Date settlementAuditTime) {
		this.settlementAuditTime = settlementAuditTime;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getSettlementRefBillNo() {
		return this.settlementRefBillNo;
	}

	public void setSettlementRefBillNo(String settlementRefBillNo) {
		this.settlementRefBillNo = settlementRefBillNo;
	}

	public BigDecimal getSettlementTotalMoney() {
		return this.settlementTotalMoney;
	}

	public void setSettlementTotalMoney(BigDecimal settlementTotalMoney) {
		this.settlementTotalMoney = settlementTotalMoney;
	}

	public BigDecimal getSettlementTotalDiscount() {
		return this.settlementTotalDiscount;
	}

	public void setSettlementTotalDiscount(BigDecimal settlementTotalDiscount) {
		this.settlementTotalDiscount = settlementTotalDiscount;
	}

	public Integer getAccountBankNum() {
		return this.accountBankNum;
	}

	public void setAccountBankNum(Integer accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public Boolean getSettlementSyncFlag() {
		return this.settlementSyncFlag;
	}

	public void setSettlementSyncFlag(Boolean settlementSyncFlag) {
		this.settlementSyncFlag = settlementSyncFlag;
	}

	public List<SettlementDetail> getSettlementDetails() {
		return settlementDetails;
	}

	public void setSettlementDetails(List<SettlementDetail> settlementDetails) {
		this.settlementDetails = settlementDetails;
	}

	public Boolean getSettlementReadFlag() {
		return settlementReadFlag;
	}

	public void setSettlementReadFlag(Boolean settlementReadFlag) {
		this.settlementReadFlag = settlementReadFlag;
	}

	public List<PreSettlementDetail> getPreSettlementDetails() {
		return preSettlementDetails;
	}

	public void setPreSettlementDetails(
			List<PreSettlementDetail> preSettlementDetails) {
		this.preSettlementDetails = preSettlementDetails;
	}

	public boolean checkMoney(){
		if(preSettlementDetails.size() == 0){
			return false;
		}
		BigDecimal preMoney = BigDecimal.ZERO;
		BigDecimal detailMoney = BigDecimal.ZERO;
		for(int i = 0;i < preSettlementDetails.size();i++){
			PreSettlementDetail preSettlementDetail = preSettlementDetails.get(i);
			preMoney = preMoney.add(preSettlementDetail.getPreSettlementDetailMoney().setScale(2, BigDecimal.ROUND_HALF_UP));
		}
		
		for(int i = 0;i < settlementDetails.size();i++){
			SettlementDetail settlementDetail = settlementDetails.get(i);
			detailMoney = detailMoney.add(settlementDetail.getSettlementDetailMoney().setScale(2, BigDecimal.ROUND_HALF_UP));
		}
		if(preMoney.compareTo(detailMoney) != 0){
			return true;
		}		
		return false;
	}
}
