package com.nhsoft.report.dto;

import java.util.List;


/**
 * GroupCustomer generated by hbm2java
 */
public class GroupCustomerDTO implements java.io.Serializable {

    //默认
    public static final String SUFFIX_CFM_01 = "_01";
    public static final String SUFFIX_CFM_02 = "_02";
    public static final String SUFFIX_CFM_03 = "_03";
    public static final String SUFFIX_CFM_04 = "_04";
    public static final String SUFFIX_SPM_05 = "_05";
    public static final String SUFFIX_SPM_06 = "_06";
    public static final String SUFFIX_SPM_07 = "_07";
    public static final String SUFFIX_SPM_08 = "_08";
    public static final String SUFFIX_LOC_09 = "_09";
    public static final String SUFFIX_LOC_10 = "_10";
    public static final String SUFFIX_LOC_11 = "_11";
    public static final String SUFFIX_LOC_12 = "_12";
	private static final long serialVersionUID = 6740735713486305592L;
	private String groupCustomerId;
	private String systemBookCode;
	private Integer branchNum;
	private String groupCustomerProperty;
	private String groupCustomerName;
	private String groupCustomerMemo;
	private String groupCustomerText;
	private String groupCustomerType;
	private GroupCustomerStatisticsDTO groupCustomerStatistics;

	public String getGroupCustomerType() {
		return groupCustomerType;
	}

	public void setGroupCustomerType(String groupCustomerType) {
		this.groupCustomerType = groupCustomerType;
	}

	public GroupCustomerStatisticsDTO getGroupCustomerStatistics() {
		return groupCustomerStatistics;
	}

	public void setGroupCustomerStatistics(GroupCustomerStatisticsDTO groupCustomerStatistics) {
		this.groupCustomerStatistics = groupCustomerStatistics;
	}

	public GroupCustomerDTO() {
	}

	public String getGroupCustomerId() {
		return this.groupCustomerId;
	}

	public void setGroupCustomerId(String groupCustomerId) {
		this.groupCustomerId = groupCustomerId;
	}

	public String getSystemBookCode() {
		return this.systemBookCode;
	}

	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}

	public Integer getBranchNum() {
		return this.branchNum;
	}

	public void setBranchNum(Integer branchNum) {
		this.branchNum = branchNum;
	}

	public String getGroupCustomerProperty() {
		return this.groupCustomerProperty;
	}

	public void setGroupCustomerProperty(String groupCustomerProperty) {
		this.groupCustomerProperty = groupCustomerProperty;
	}

	public String getGroupCustomerName() {
		return this.groupCustomerName;
	}

	public void setGroupCustomerName(String groupCustomerName) {
		this.groupCustomerName = groupCustomerName;
	}

	public String getGroupCustomerMemo() {
		return this.groupCustomerMemo;
	}

	public void setGroupCustomerMemo(String groupCustomerMemo) {
		this.groupCustomerMemo = groupCustomerMemo;
	}

	public String getGroupCustomerText() {
		return this.groupCustomerText;
	}

	public void setGroupCustomerText(String groupCustomerText) {
		this.groupCustomerText = groupCustomerText;
	}

	public static GroupCustomerDTO get(List<GroupCustomerDTO> groupCustomers, String groupCustomerId){
		for(int i = 0;i < groupCustomers.size();i++){
			GroupCustomerDTO groupCustomer = groupCustomers.get(i);
			if(groupCustomer.getGroupCustomerId().equals(groupCustomerId)){
				return groupCustomer;
			}
		}
		return null;
	}
	
}
